.TH deductionguidesforstd::weak_ptr 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
deductionguidesforstd::weak_ptr \- deductionguidesforstd::weak_ptr

.SH Synopsis
   Defined in header <memory>
   template<class T>                             \fI(since C++17)\fP
   weak_ptr(std::shared_ptr<T>) -> weak_ptr<T>;

   One deduction guide is provided for std::weak_ptr to account for the edge case
   missed by the implicit deduction guides.

.SH Example

   
// Run this code

 #include <memory>
  
 int main()
 {
     auto p = std::make_shared<int>(42);
     std::weak_ptr w{p};    // explicit deduction guide is used in this case
 }
