.TH operator<<(std::thread::id) 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   template< class CharT, class Traits >

   std::basic_ostream<CharT,Traits>&                                     \fI(since C++11)\fP

   operator<<( std::basic_ostream<CharT,Traits>&& ost, thread::id id );

   Writes a textual representation of a thread identifier id to the output stream ost.

   If two thread identifiers compare equal, they have identical textual
   representations; if they do not compare equal, their representations are distinct.

.SH Parameters

   ost - output stream to insert the data into
   id  - thread identifier

.SH Return value

   ost

.SH Exceptions

   \fI(none)\fP
