.TH std::shared_mutex::native_handle 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::shared_mutex::native_handle \- std::shared_mutex::native_handle

.SH Synopsis
   native_handle_type native_handle();  \fI(since C++17)\fP
                                        (optional)

   Returns the underlying implementation-defined native handle object.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Implementation-defined native handle object.

.SH Exceptions

   Implementation-defined.

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:

     * Todo no example
