.TH std::span::size_bytes 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::span::size_bytes \- std::span::size_bytes

.SH Synopsis
   constexpr index_type size_bytes() const noexcept;

   Returns the size of the sequence in bytes.

.SH Return value

   The size of the sequence in bytes, i.e., size() * sizeof(element_type).

.SH See also

   size returns the number of elements in the sequence
        \fI(public member function)\fP 
