.TH std::shuffle_order_engine::base 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::shuffle_order_engine::base \- std::shuffle_order_engine::base

.SH Synopsis
   const Engine& base() const noexcept;  \fI(since C++11)\fP

   Returns the underlying engine.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The underlying engine.
