.TH std::forward_list::clear 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::forward_list::clear \- std::forward_list::clear

.SH Synopsis
   void clear();  \fI(since C++11)\fP

   Removes all elements from the container.

   Invalidates any references, pointers, or iterators referring to contained elements.
   May invalidate any past-the-end iterators.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH Complexity

   Linear in the size of the container.

   clear is defined in terms of erase, which has linear complexity. \fI(until C++11)\fP
   complexity of clear is omitted                                   \fI(since C++11)\fP
   clear has linear complexity for sequence containers.             \fI(since C++14)\fP

.SH See also

   erase_after erases an element after an element
               \fI(public member function)\fP 
