.TH std::basic_string_view::rfind 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string_view::rfind \- std::basic_string_view::rfind

.SH Synopsis
   constexpr size_type rfind(basic_string_view v, size_type pos =     \fB(1)\fP \fI(since C++17)\fP
   npos) const noexcept;
   constexpr size_type rfind(CharT c, size_type pos = npos) const     \fB(2)\fP \fI(since C++17)\fP
   noexcept;
   constexpr size_type rfind(const CharT* s, size_type pos, size_type \fB(3)\fP \fI(since C++17)\fP
   count) const;
   constexpr size_type rfind(const CharT* s, size_type pos = npos)    \fB(4)\fP \fI(since C++17)\fP
   const;

   Finds the last substring equal to the given character sequence.

   1) Finds the last occurence of v in this view, starting at position pos.
   2) Equivalent to rfind(basic_string_view(&c, 1), pos).
   3) Equivalent to rfind(basic_string_view(s, count), pos).
   4) Equivalent to rfind(basic_string_view(s), pos).

.SH Parameters

   v     - view to search for
   pos   - position at which to start the search
   count - length of substring to search for
   s     - pointer to a character string to search for
   ch    - character to search for

.SH Return value

   Position of the first character of the found substring or npos if no such substring
   is found.

.SH Complexity

   O(size() * v.size()) at worst.

.SH See also

   find              find characters in the view
                     \fI(public member function)\fP 
   find_first_of     find first occurrence of characters
                     \fI(public member function)\fP 
   find_last_of      find last occurrence of characters
                     \fI(public member function)\fP 
   find_first_not_of find first absence of characters
                     \fI(public member function)\fP 
   find_last_not_of  find last absence of characters
                     \fI(public member function)\fP 
