.TH std::ranges::chunk_view::iterator::operator[] 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::chunk_view::iterator::operator[] \- std::ranges::chunk_view::iterator::operator[]

.SH Synopsis
   constexpr value_type operator[]( difference_type pos ) const  (since C++23)
       requires ranges::random_access_range<Base>;

   Returns an element at specified relative location.

   Equivalent to: return *(*this + pos);.

.SH Parameters

   pos - position relative to current location

.SH Return value

   The element (of type value_type) at displacement pos relative to the current
   location.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator* accesses the element
   (C++23)   \fI(public member function)\fP

.SH Category:
     * Todo no example
