.TH std::experimental::observer_ptr::operatorelement_type* 3 "2022.07.31" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::observer_ptr::operatorelement_type* \- std::experimental::observer_ptr::operatorelement_type*

.SH Synopsis
   constexpr explicit operator element_type*() const       (library fundamentals TS v2)
   noexcept;

   Provides an explicit conversion to the type of the stored pointer.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A pointer to the watched object, i.e., get()

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   get returns a pointer to the watched object
       \fI(public member function)\fP
