.TH std::error_condition::operatorbool 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   explicit operator bool() const;  \fI(since C++11)\fP

   Checks whether the stored error code is not zero.

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if value != 0, false otherwise.

.SH Exceptions

   noexcept specification:
   noexcept
.SH Category:

     * unconditionally noexcept
