.TH std::seed_seq::param 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   template< class OutputIt >          \fI(since C++11)\fP
   void param( OutputIt dest ) const;

   Outputs the initial seed sequence that's stored in the std::seed_seq object.

.SH Parameters

   dest - output iterator such that the expression *dest=rt is valid for a value rt of
          result_type
.SH Type requirements
   -
   OutputIt must meet the requirements of OutputIterator.

.SH Return value

   \fI(none)\fP

.SH Exceptions

   Throws only if an operation on dest throws.

.SH Example

   
// Run this code

 #include <random>
 #include <iostream>
 #include <iterator>
 int main()
 {
     std::seed_seq s1 = {-1, 0, 1};
     s1.param(std::ostream_iterator<int>(std::cout, " "));
 }

.SH Output:

 -1 0 1
