.TH std::nothrow_t 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::nothrow_t \- std::nothrow_t

.SH Synopsis
   Defined in header <new>
   struct nothrow_t {};

   std::nothrow_t is an empty class type used to disambiguate the overloads of throwing
   and non-throwing allocation functions.

.SH See also

                  an object of type nothrow_t used to select an non-throwing allocation
   nothrow        function
                  (constant)
   operator new   allocation functions
   operator new[] \fI(function)\fP
