.TH std::experimental::filesystem::path::concat,operator+= 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::filesystem::path::concat,operator+= \- std::experimental::filesystem::path::concat,operator+=

.SH Synopsis
   path& operator+=( const path& p );                       \fB(1)\fP (filesystem TS)
   path& operator+=( const string_type& x );                \fB(2)\fP (filesystem TS)
   path& operator+=( const value_type* x );                 \fB(3)\fP (filesystem TS)
   path& operator+=( value_type x );                        \fB(4)\fP (filesystem TS)
   template< class Source >                                 \fB(5)\fP (filesystem TS)
   path& operator+=( const Source& source );
   template< class CharT >                                  \fB(6)\fP (filesystem TS)
   path& operator+=( CharT x );
   template< class Source >                                 \fB(7)\fP (filesystem TS)
   path& concat( const Source& source );
   template< class InputIt >                                \fB(8)\fP (filesystem TS)
   path& concat( InputIterator first, InputIterator last );

   Concatenates the current path and the argument. Differently from append() or
   operator/=, separator is not appended.

   1) Concatenates the current path and p.native()
   2-4) Concatenates the current path and x
   5,7) Concatenates the current path and the effective argument. The argument is
   firstly converted to path::value_type if such conversion is necessary.
   6) Concatenates the current path and x.
   8) Concatenates the current path and the range [first, last).

.SH Parameters

   p                          -               path to append
   source                     -               effective argument to append
   first, last                -               the range to append
.SH Type requirements
   -
   InputIt must meet the requirements of InputIterator.
   -
   The value type of InputIt must be one of the encoded character types (char, wchar_t,
   char16_t and char32_t)
   -
   CharT must be one of the encoded character types (char, wchar_t, char16_t and
   char32_t)

.SH Return value

   *this

.SH Exceptions

    This section is incomplete

.SH See also

    This section is incomplete

.SH Category:

     * Todo without reason
