.TH std::experimental::latch::wait 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::latch::wait \- std::experimental::latch::wait

.SH Synopsis
   void wait() const; \fB(1)\fP (concurrency TS)

   Blocks the calling thread until the internal counter reaches 0. If it is zero
   already, returns immediately.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Exceptions

   Throws nothing.
