.TH std::chrono::year::operator+=,std::chrono::year::operator-= 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year::operator+=,std::chrono::year::operator-= \- std::chrono::year::operator+=,std::chrono::year::operator-=

.SH Synopsis
   constexpr std::chrono::year& operator+=(const std::chrono::years&  \fB(1)\fP \fI(since C++20)\fP
   y) noexcept;
   constexpr std::chrono::year& operator-=(const std::chrono::years&  \fB(2)\fP \fI(since C++20)\fP
   y) noexcept;

   Adds or subtracts y.count() years from the year value.

   1) Equivalent to *this = *this + y;
   2) Equivalent to *this = *this - y;

.SH Return value

   A reference to this year after modification.

.SH Notes

   If the result would be outside the range [-32767, 32767], the actual stored value is
   unspecified.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator++
   operator++(int) increments or decrements the year
   operator--      \fI(public member function)\fP 
   operator--(int)
   operator+       performs arithmetic on years
   operator-       \fI(public member function)\fP 

.SH Category:

     * Todo no example
