.TH std::ranges::binary_search 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::binary_search \- std::ranges::binary_search

.SH Synopsis
   Defined in header <algorithm>
   Call signature
   template< std::forward_iterator I, std::sentinel_for<I> S, class
   T,

             class Proj = std::identity,
             std::indirect_strict_weak_order<
                 const T*,                                            \fB(1)\fP \fI(since C++20)\fP
                 std::projected<I, Proj>> Comp = ranges::less >
   constexpr bool

   binary_search( I first, S last, const T& value, Comp comp = {},
   Proj proj = {} );
   template< ranges::forward_range R, class T, class Proj =
   std::identity,

             std::indirect_strict_weak_order<
                 const T*,
                 std::projected<ranges::iterator_t<R>, Proj>> Comp =  \fB(2)\fP \fI(since C++20)\fP
   ranges::less >
   constexpr bool

   binary_search( R&& r, const T& value, Comp comp = {}, Proj proj =
   {} );

   1) Checks if a projected element equivalent to value appears within the range
   [first, last).
   2) Same as \fB(1)\fP, but uses r as the source range, as if using ranges::begin(r) as
   first and ranges::end(r) as last.

   For ranges::binary_search to succeed, the range [first, last) must be at least
   partially ordered with respect to value, i.e. it must satisfy all of the following
   requirements:

     * partitioned with respect to std::invoke(comp, std::invoke(proj, element), value)
       (that is, all projected elements for which the expression is true precedes all
       elements for which the expression is false)
     * partitioned with respect to !std::invoke(comp, value, std::invoke(proj,
       element))
     * for all elements, if std::invoke(comp, std::invoke(proj, element), value) is
       true then !std::invoke(comp, value, std::invoke(proj, element)) is also true

   A fully-sorted range meets these criteria.

   The function-like entities described on this page are niebloids, that is:

     * Explicit template argument lists may not be specified when calling any of them.
     * None of them is visible to argument-dependent lookup.
     * When one of them is found by normal unqualified lookup for the name to the left
       of the function-call operator, it inhibits argument-dependent lookup.

   In practice, they may be implemented as function objects, or with special compiler
   extensions.

.SH Parameters

   first, last - the range of elements to examine
   r           - the range of elements to examine
   value       - value to compare the elements to
   comp        - comparison function to apply to the projected elements
   proj        - projection to apply to the elements

.SH Return value

   true if an element equal to value is found, false otherwise.

.SH Complexity

   The number of comparisons and projections performed is logarithmic in the distance
   between first and last (At most log
   2(last - first) + O(1) comparisons and projections). However, for iterator-sentinel
   pair that does not model std::random_access_iterator, number of iterator increments
   is linear.

.SH Possible implementation

struct binary_search_fn {
    template<std::forward_iterator I, std::sentinel_for<I> S, class T,
             class Proj = std::identity,
             std::indirect_strict_weak_order<
                 const T*,
                 std::projected<I, Proj>> Comp = ranges::less>
    constexpr bool
    operator()(I first, S last, const T& value, Comp comp = {}, Proj proj = {}) const
    {
        first = std::lower_bound(first, last, value, comp);
        return (!(first == last) && !(comp(value, *first)));
    }

    template<ranges::forward_range R, class T, class Proj = std::identity,
             std::indirect_strict_weak_order<
                const T*,
                std::projected<ranges::iterator_t<R>, Proj>> Comp = ranges::less>
    constexpr bool operator()(R&& r, const T& value, Comp comp = {}, Proj proj = {}) const
    {
        return (*this)(ranges::begin(r), ranges::end(r), value,
                       std::ref(comp), std::ref(proj));
    }
};

inline constexpr binary_search_fn binary_search;

.SH Example


// Run this code

 #include <iostream>
 #include <algorithm>
 #include <vector>

 int main()
 {
     std::vector<int> haystack {1, 3, 4, 5, 9};
     std::vector<int> needles {1, 2, 3};

     for (auto needle : needles) {
         std::cout << "Searching for " << needle << '\\n';
         if (ranges::binary_search(haystack, needle)) {
             std::cout << "Found " << needle << '\\n';
         } else {
             std::cout << "no dice!\\n";
         }
     }
 }

.SH Output:

 Searching for 1
 Found 1
 Searching for 2
 no dice!
 Searching for 3
 Found 3

.SH See also

   ranges::equal_range returns range of elements matching a specific key
   (C++20)             (niebloid)
   binary_search       determines if an element exists in a certain range
                       \fI(function template)\fP
