.TH std::piecewise_constant_distribution::param 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::piecewise_constant_distribution::param \- std::piecewise_constant_distribution::param

.SH Synopsis
   param_type param() const;               \fB(1)\fP \fI(since C++11)\fP
   void param( const param_type& params ); \fB(2)\fP \fI(since C++11)\fP

   Manages the associated distribution parameter set.

   1) Returns the associated parameter set.
   2) Sets the associated parameter set to params.

.SH Parameters

   params - new contents of the associated parameter set

.SH Return value

   1) The associated parameter set.
   2) \fI(none)\fP

.SH Complexity

   Constant.
