.TH std::alignment_of 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::alignment_of \- std::alignment_of

.SH Synopsis
   Defined in header <type_traits>
   template< class T >              \fI(since C++11)\fP
   struct alignment_of;

   Provides the member constant value equal to the alignment requirement of the type T,
   as if obtained by an alignof expression. If T is an array type, returns the
   alignment requirements of the element type. If T is a reference type, returns the
   alignment requirements of the type referred to.

   If alignof(T) is not a valid expression, the behavior is undefined.

.SH Member constants

   value    alignof(T)
   \fB[static]\fP \fI(public static member constant)\fP

.SH Member functions

   operator std::size_t converts the object to std::size_t, returns value
                        \fI(public member function)\fP
   operator()           returns value
   \fI(C++14)\fP              \fI(public member function)\fP

.SH Member types

   Type       Definition
   value_type std::size_t
   type       std::integral_constant<std::size_t, value>

.SH Possible implementation

   template< class T >
   struct alignment_of : std::integral_constant<
                             std::size_t,
                             alignof(T)
                          > {};

.SH Notes

   This type trait predates the alignof keyword, which can be used to obtain the same
   value with less verbosity.

.SH Example

   
// Run this code

 #include <iostream>
 #include <type_traits>
  
 class A {};
  
 int main()
 {
     std::cout << std::alignment_of<A>::value << '\\n';
     std::cout << std::alignment_of<int>() << '\\n'; // alt syntax
     std::cout << std::alignment_of_v<double> << '\\n'; // c++17 alt syntax
 }

.SH Output:

 1
 4
 8

.SH See also

   alignof operator queries alignment requirements of a type \fI(since C++11)\fP 
   aligned_storage  defines the type suitable for use as uninitialized storage for
   \fI(C++11)\fP          types of given size
                    \fI(class template)\fP 
   aligned_union    defines the type suitable for use as uninitialized storage for all
   \fI(C++11)\fP          given types
                    \fI(class template)\fP 
   max_align_t      trivial type with alignment requirement as great as any other
   \fI(C++11)\fP          scalar type
                    \fI(typedef)\fP 
