.TH std::experimental::pmr::monotonic_buffer_resource::release 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::pmr::monotonic_buffer_resource::release \- std::experimental::pmr::monotonic_buffer_resource::release

.SH Synopsis
   void release();  (library fundamentals TS)

   Releases all allocated memory by calling the deallocate function on the upstream
   memory resource as necessary.

   Memory is released back to the upstream resource even if deallocate has not been
   called for some of the allocated blocks.

.SH See also

   deallocate deallocates memory
              \fI(public member function of std::experimental::pmr::memory_resource)\fP
