.TH std::experimental::filesystem::directory_entry::assign 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::filesystem::directory_entry::assign \- std::experimental::filesystem::directory_entry::assign

.SH Synopsis
   void assign( const path& p, file_status status = file_status(),  (filesystem TS)
                file_status symlink_status = file_status() );

   Assigns new content to the directory entry object. Sets the path to p, file status
   to status and symlink status to symlink_status.

.SH Parameters

    This section is incomplete

.SH Return value

   \fI(none)\fP

.SH Exceptions

    This section is incomplete

.SH See also

   operator= assigns contents
             \fI(public member function)\fP 

.SH Category:

     * Todo without reason
