.TH std::error_code::clear 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_code::clear \- std::error_code::clear

.SH Synopsis
   void clear() noexcept;  \fI(since C++11)\fP

   Replaces the error code and error category with default values.

   Equivalent to *this = error_code(0, std::system_category()).

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP
