.TH std::thread::~thread 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::thread::~thread \- std::thread::~thread

.SH Synopsis
   ~thread();  \fI(since C++11)\fP

   Destroys the thread object. If *this still has an associated running thread (i.e.
   joinable() == true), std::terminate() is called.
