.TH std::basic_string::replace 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string::replace \- std::basic_string::replace

.SH Synopsis
   basic_string& replace( size_type pos, size_type count,

                          const basic_string& str );
                                                                  \fB(1)\fP
   basic_string& replace( const_iterator first, const_iterator
   last,

                          const basic_string& str );
   basic_string& replace( size_type pos, size_type count,

                          const basic_string& str,                        \fI(until C++14)\fP

                          size_type pos2, size_type count2 );
   basic_string& replace( size_type pos, size_type count,

                          const basic_string& str,                        \fI(since C++14)\fP

                          size_type pos2, size_type count2 = npos
   );
   template< class InputIt >

   basic_string& replace( const_iterator first, const_iterator        \fB(2)\fP
   last,

                          InputIt first2, InputIt last2 );
   basic_string& replace( size_type pos, size_type count,             \fB(3)\fP
                          const CharT* cstr, size_type count2 );  \fB(2)\fP
   basic_string& replace( const_iterator first, const_iterator
   last,                                                              \fB(3)\fP
                          const CharT* cstr, size_type count2 );
   basic_string& replace( size_type pos, size_type count,

                          const CharT* cstr );
                                                                      \fB(4)\fP
   basic_string& replace( const_iterator first, const_iterator
   last,

                          const CharT* cstr );
   basic_string& replace( size_type pos, size_type count,             \fB(5)\fP
                          size_type count2, CharT ch );
   basic_string& replace( const_iterator first, const_iterator
   last,                                                              \fB(5)\fP
                          size_type count2, CharT ch );
   basic_string& replace( const_iterator first, const_iterator
   last,                                                              \fB(6)\fP \fI(since C++11)\fP
                          std::initializer_list<CharT> ilist );

   Replaces the part of the string indicated by either [pos, pos + count) or [first,
   last) with a new string.

   The new string can be one of:

   1) string str;
   2) substring [pos2, pos2 + count2) of str or characters in the range [first2,
   last2);
   3) first count2 charcters of the character string pointed to by cstr;
   4) null-terminated character string pointed to by cstr;
   5) count2 copies of character ch;
   6) characters in the initializer list ilist;

.SH Parameters

   pos           - start of the substring that is going to be replaced
   count         - length of the substring that is going to be replaced
   first, last   - range of characters that is going to be replaced
   str           - string to use for replacement
   pos2          - start of the substring to replace with
   count2        - number of characters to replace with
   cstr          - pointer to the character string to use for replacement
   ch            - character value to use for replacement
   first2, last2 - range of characters to use for replacement
   init          - initializer list with the characters to use for replacement
.SH Type requirements
   -
   InputIt must meet the requirements of InputIterator.

.SH Return value

   *this

.SH Exceptions

   std::out_of_range if pos > length() or pos2 > str.length()

   std::length_error if the resulting string will exceed maximum possible string length
   (std::string::npos - 1)

   In any case, if an exception is thrown for any reason, this function has no effect
   \fI(strong exception guarantee)\fP.
   \fI(since C++11)\fP

.SH Example

   
// Run this code

 #include <iostream>
 #include <string>
  
 int main()
 {
     std::string str("The quick brown fox jumps over the lazy dog.");
  
     str.replace(10, 5, "red"); // (4)
  
     str.replace(str.begin(), str.begin() + 3, 1, 'A'); // (5)
  
     std::cout << str << '\\n';
 }

.SH Output:

 A quick red fox jumps over the lazy dog.
