.TH std::ostream_iterator::operator* 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   ostream_iterator& operator*();

   Does nothing, this member function is provided to satisfy the requirements of
   OutputIterator.

   It returns the iterator itself, which makes it possible to use code such as *iter =
   value to output (insert) the value into the underlying stream.

.SH Parameters

   \fI(none)\fP

.SH Return value

   *this
