.TH std::frexp 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   float       frexp( float arg, int* exp );
   double      frexp( double arg, int* exp );
   long double frexp( long double arg, int* exp );
   double      frexp( Integral arg, int* exp );     \fI(since C++11)\fP

   Decomposes given floating point value to significand and exponent.

.SH Parameters

   arg - floating point value
   exp - pointer to integer value to store the exponent to

.SH Return value

   Significand of the given floating point number in the range of [0.5; 1). The
   exponent is put into integer value pointed to by exp.

.SH See also

   ldexp   multiplies a number by 2 raised to a power
           \fI(function)\fP
   logb    extracts exponent of the number
   \fI(C++11)\fP \fI(function)\fP
   ilogb   extracts exponent of the number
   \fI(C++11)\fP \fI(function)\fP
   modf    decomposes a number into integer and fractional parts
           \fI(function)\fP
