.TH std::mdspan::size 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::mdspan::size \- std::mdspan::size

.SH Synopsis
   constexpr size_type size() const noexcept;  (since C++23)

   Returns the number of elements in mdspan.

   Equivalent to extents().fwd-prod-of-extents(rank()).

   If the size of the multidimensional index space extents() is not representable as a
   value of type size_type, the behavior of the program is undefined.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of elements.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

    This section is incomplete

.SH Categories:
     * Todo no example
     * Todo without reason
