.TH std::filesystem::path::root_path 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::path::root_path \- std::filesystem::path::root_path

.SH Synopsis
   path root_path() const;  \fI(since C++17)\fP

   Returns the root path of the path. If the path does not include root path, returns
   path().

   Effectively, returns the following: root_name() / root_directory()

.SH Parameters

   \fI(none)\fP

.SH Return value

   The root path of the path.

.SH Exceptions

   \fI(none)\fP

.SH Example

   
// Run this code

 #include <iostream>
 #include <filesystem>
 namespace fs = std::filesystem;
  
 int main()
 {
     std::cout << "Current root path is: " << fs::current_path().root_path() << '\\n';
 }

.SH Possible output:

 Current root path is: "C:\\"

.SH See also

   root_name      returns the root-name of the path, if present
                  \fI(public member function)\fP 
   root_directory returns the root directory of the path, if present
                  \fI(public member function)\fP 
