.TH std::unordered_map::bucket_size 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   size_type bucket_size( size_type n ) const;  \fI(since C++11)\fP

   Returns the number of elements in the bucket with index n.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Complexity
     * 4 See also

.SH Parameters

   n - the index of the bucket to examine

.SH Return value

   The number of elements in the bucket n.

.SH Complexity

   Constant.

.SH See also

   bucket_count returns the number of buckets
                \fI(public member function)\fP
