.TH std::experimental::function::get_memory_resource 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::function::get_memory_resource \- std::experimental::function::get_memory_resource

.SH Synopsis
                                                                  (library fundamentals
   std::experimental::pmr::memory_resource*                       TS)
   get_memory_resource() const noexcept;                          (removed in library
                                                                  fundamentals TS v3)

   Returns a pointer to the memory resource used by this object to allocate memory.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A pointer to the memory resource used by this object to allocate memory.

.SH See also

   constructor              constructs a new std::experimental::function instance
                            \fI(public member function)\fP
   get_allocator            retrieves a type-erased std::pmr::polymorphic_allocator
   (library fundamentals TS used by this object to allocate memory
   v3)                      \fI(public member function)\fP
