.TH std::experimental::ranges::SizedSentinel 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::SizedSentinel \- std::experimental::ranges::SizedSentinel

.SH Synopsis
   Defined in header <experimental/ranges/iterator>
   template <class S, class I>

   concept bool SizedSentinel() {
       return ranges::Sentinel<S, I>()
           && !ranges::disable_sized_sentinel<std::remove_cv_t<S>,
   std::remove_cv_t<I>>                                                     (ranges TS)
           && requires(const I& i, const S& s) {
                  { s - i } -> ranges::Same<ranges::difference_type_t<I>>;
                  { i - s } -> ranges::Same<ranges::difference_type_t<I>>;
              };

   }

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
