.TH std::chrono::operator<<(std::chrono::day) 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator<<(std::chrono::day) \- std::chrono::operator<<(std::chrono::day)

.SH Synopsis
   Defined in header <chrono>
   template< class CharT, class Traits >

   std::basic_ostream<CharT, Traits>&                                     \fI(since C++20)\fP

   operator<<( std::basic_ostream<CharT, Traits>& os, const
   std::chrono::day& d );

   Forms a std::basic_string<CharT> s consisting of the day value stored in d formatted
   as a decimal number, with a leading zero if the result would otherwise be a single
   decimal digit. Then, if !d.ok(), append " is not a valid day" to the formatted
   string. Inserts that string into os.

   Equivalent to

   return os << (d.ok() ?
   std::format(STATICALLY_WIDEN<CharT>("{:%d}"), d) :
   std::format(STATICALLY_WIDEN<CharT>("{:%d} is not a valid day"), d));

   where STATICALLY_WIDEN<CharT>("...") is "..." if CharT is char, and L"..." if CharT
   is wchar_t.

.SH Return value

   os.

.SH See also

   format                           stores formatted representation of the arguments in
   (C++20)                          a new string
                                    \fI(function template)\fP
   std::formatter<std::chrono::day> specialization of std::formatter that formats a day
   (C++20)                          according to the provided format
                                    \fI(class template specialization)\fP
