.TH std::discard_block_engine::operator() 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::discard_block_engine::operator() \- std::discard_block_engine::operator()

.SH Synopsis
   result_type operator()();  \fI(since C++11)\fP

   Generates a random value. The state of the underlying engine is advanced one or more
   times.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A pseudo-random number in [min(), max()].

.SH Exceptions

   \fI(none)\fP

.SH See also

   discard advances the adaptor's state by a specified amount
           \fI(public member function)\fP 
