.TH std::getwchar 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::getwchar \- std::getwchar

.SH Synopsis
   Defined in header <cwchar>
   wint_t getwchar();

   Reads the next wide character from stdin.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The obtained wide character or WEOF if an error has occurred or the end of file
   reached

.SH See also

   getchar reads a character from stdin
           \fI(function)\fP 
   fgetwc  gets a wide character from a file stream
   getwc   \fI(function)\fP 
   C documentation for
   getwchar
