.TH std::nan,std::nanf,std::nanl 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::nan,std::nanf,std::nanl \- std::nan,std::nanf,std::nanl

.SH Synopsis
   Defined in header <cmath>
   float nanf( const char* arg );        \fI(since C++11)\fP
   double nan( const char* arg );        \fI(since C++11)\fP
   long double nanl( const char* arg );  \fI(since C++11)\fP

   Converts the implementation-defined character string arg into the corresponding
   quiet NaN value. The call std::nan("string") is equivalent to the call
   std::strtod("NAN(string)", (char**)NULL);.

.SH Parameters

   arg - narrow character string identifying the contents of a NaN, or an empty string

.SH Return value

   The NaN value that corresponds to the identifying string arg or zero if the
   implementation does not support quiet NaNs.

.SH See also

   isnan     checks if the given number is NaN
   \fI(C++11)\fP   \fI(function)\fP 
   quiet_NaN returns a quiet NaN value of the given floating-point type
   \fB[static]\fP  \fI(public static member function of std::numeric_limits)\fP 
   C documentation for
   nanf,
   nan,
   nanl
