.TH std::experimental::simd_abi::compatible 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::simd_abi::compatible \- std::experimental::simd_abi::compatible

.SH Synopsis
   Defined in header <experimental/simd>
   namespace simd_abi {

   template < class T >
   using compatible = /*implementation-defined*/;

   }

   compatible<T> is an implementation-defined alias for an ABI tag.

.SH Notes

   The intent is to use the ABI tag producing the most efficient data-parallel
   execution for the element type T that ensures ABI compatibility between translation
   units on the target architecture.

.SH See also
