.TH std::ranges::zip_view::iterator::iterator 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::zip_view::iterator::iterator \- std::ranges::zip_view::iterator::iterator

.SH Synopsis
   /*iterator*/() = default;                                          \fB(1)\fP (since C++23)
   constexpr /*iterator*/( /*iterator*/<!Const> i )

       requires Const &&
           (std::convertible_to<ranges::iterator_t<Views>,            \fB(2)\fP (since C++23)


    ranges::iterator_t</*maybe-const*/<Const, Views>>> && ...);

   Construct an iterator.

   1) Default constructor. Value-initializes the underlying tuple of iterators to their
   default values.
   2) Conversion from /*iterator*/<false> to /*iterator*/<true>. Move constructs the
   underlying tuple of iterators current_ with std::move(i.current).

   This iterator also has a private constructor which is used by zip_view::begin and
   zip_view::end. This constructor is not accessible to users.

.SH Parameters

   i - an /*iterator*/<false>

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
