.TH std::basic_fstream::close 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_fstream::close \- std::basic_fstream::close

.SH Synopsis
   void close();

   Closes the associated file.

   Effectively calls rdbuf()->close(). If an error occurs during operation,
   setstate(failbit) is called.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Notes

   This function is called by the destructor of basic_fstream when the stream object
   goes out of scope and is not usually invoked directly.

.SH Example


// Run this code

 #include <string>
 #include <fstream>
 #include <iostream>

 int main()
 {
     std::fstream f1("example1", std::ios::out),
                  f2("example2", std::ios::out),
                  f3("example3", std::ios::out);

     std::cout << std::boolalpha
               << f1.is_open() << '\\n'
               << f2.is_open() << '\\n'
               << f3.is_open() << '\\n';

     f1.close();
     f2.close();

     std::cout << f1.is_open() << '\\n'
               << f2.is_open() << '\\n'
               << f3.is_open() << '\\n';
 }

.SH Possible output:

 true
 true
 true
 false
 false
 true

.SH See also

   is_open checks if the stream has an associated file
           \fI(public member function)\fP
   open    opens a file and associates it with the stream
           \fI(public member function)\fP
   close   flushes the put area buffer and closes the associated file
           \fI(public member function of std::basic_filebuf<CharT,Traits>)\fP
