.TH std::thread::hardware_concurrency 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   static unsigned hardware_concurrency();  \fI(since C++11)\fP

   Returns number of concurrent threads supported by the implementation. The value
   should be considered only a hint.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Exceptions
     * 4 Example

.SH Parameters

   \fI(none)\fP

.SH Return value

   number of concurrent threads supported. If the value is not well defined or not
   computable, returns 0.

.SH Exceptions

   noexcept specification:
   noexcept

.SH Example

   
// Run this code

 #include <iostream>
 #include <thread>

 int main() {
     unsigned int n = std::thread::hardware_concurrency();
     std::cout << n << " concurrent threads are supported.\\n";
 }

.SH Possible output:

 4 concurrent threads are supported.
