.TH std::fisher_f_distribution::m,n 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::fisher_f_distribution::m,n \- std::fisher_f_distribution::m,n

.SH Synopsis
   RealType m() const; \fB(1)\fP \fI(since C++11)\fP
   RealType n() const; \fB(2)\fP \fI(since C++11)\fP

   Returns the parameters the distribution was constructed with.

   1) Returns the m (the first degree of freedom) distribution parameter. The default
   value is 1.0.
   2) Returns the n (the second degree of freedom) distribution parameter. The default
   value is 1.0.

.SH Parameters

   \fI(none)\fP

.SH Return value

   1) The m (the first degree of freedom) distribution parameter.
   2) The n (the second degree of freedom) distribution parameter.

.SH Complexity

   Constant.

.SH See also

   param   gets or sets the distribution parameter object
   \fI(C++11)\fP \fI(public member function)\fP
