.TH std::chrono::month_weekday_last::ok 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month_weekday_last::ok \- std::chrono::month_weekday_last::ok

.SH Synopsis
   constexpr bool ok() const noexcept;  \fI(since C++20)\fP

   Checks if the contained month and weekday_last objects are valid.

.SH Return value

   month().ok() && weekday_last().ok()

.SH Example


// Run this code

 #include <iostream>
 #include <chrono>

 int main()
 {
     std::cout << std::boolalpha;

     auto mwdl {std::chrono::March/std::chrono::Wednesday[std::chrono::last]};
     std::cout << (mwdl.ok()) << ' ';
     mwdl = {std::chrono::month(3)/std::chrono::weekday(42)[std::chrono::last]};
     std::cout << (mwdl.ok()) << '\\n';
 }

.SH Output:

 true false
