.TH std::vector 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::vector \- std::vector

.SH Synopsis
   Defined in header <vector>
   template<class Allocator>
   class vector<bool, Allocator>;

   std::vector<bool> is a possibly space-efficient specialization of std::vector for
   the type bool.

   The manner in which std::vector<bool> is made space efficient (as well as whether it
   is optimized at all) is implementation defined. One potential optimization involves
   coalescing vector elements such that each element occupies a single bit instead of
   sizeof(bool) bytes.

   std::vector<bool> behaves similarly to std::vector, but in order to be space
   efficient, it:

     * Does not necessarily store its elements as a contiguous array.
     * Exposes class std::vector<bool>::reference as a method of accessing individual
       bits. In particular, objects of this class are returned by operator[] by value.
     * Does not use std::allocator_traits::construct to construct bit values.
     * Does not guarantee that different elements in the same container can be modified
       concurrently by different threads.

.SH Member types

   Member type            Definition
   value_type             bool
   allocator_type         Allocator
   size_type              implementation-defined
   difference_type        implementation-defined
   reference              proxy class representing a reference to a single bool
                          \fI(class)\fP
   const_reference        bool
   pointer                implementation-defined
   const_pointer          implementation-defined
   iterator               implementation-defined                   \fI(until C++20)\fP
                          implementation-defined ConstexprIterator \fI(since C++20)\fP
   const_iterator         implementation-defined                   \fI(until C++20)\fP
                          implementation-defined ConstexprIterator \fI(since C++20)\fP
   reverse_iterator       std::reverse_iterator<iterator>
   const_reverse_iterator std::reverse_iterator<const_iterator>

.SH Member functions

   constructor   constructs the vector
                 \fI(public member function of std::vector<T,Allocator>)\fP
   destructor    destructs the vector
                 \fI(public member function of std::vector<T,Allocator>)\fP
   operator=     assigns values to the container
                 \fI(public member function of std::vector<T,Allocator>)\fP
   assign        assigns values to the container
                 \fI(public member function of std::vector<T,Allocator>)\fP
   get_allocator returns the associated allocator
                 \fI(public member function of std::vector<T,Allocator>)\fP
.SH Element access
   at            access specified element with bounds checking
                 \fI(public member function of std::vector<T,Allocator>)\fP
   operator[]    access specified element
                 \fI(public member function of std::vector<T,Allocator>)\fP
   front         access the first element
                 \fI(public member function of std::vector<T,Allocator>)\fP
   back          access the last element
                 \fI(public member function of std::vector<T,Allocator>)\fP
.SH Iterators
   begin         returns an iterator to the beginning
   cbegin        \fI(public member function of std::vector<T,Allocator>)\fP
   \fI(C++11)\fP
   end           returns an iterator to the end
   cend          \fI(public member function of std::vector<T,Allocator>)\fP
   \fI(C++11)\fP
   rbegin        returns a reverse iterator to the beginning
   crbegin       \fI(public member function of std::vector<T,Allocator>)\fP
   \fI(C++11)\fP
   rend          returns a reverse iterator to the end
   crend         \fI(public member function of std::vector<T,Allocator>)\fP
   \fI(C++11)\fP
.SH Capacity
   empty         checks whether the container is empty
                 \fI(public member function of std::vector<T,Allocator>)\fP
   size          returns the number of elements
                 \fI(public member function of std::vector<T,Allocator>)\fP
   max_size      returns the maximum possible number of elements
                 \fI(public member function of std::vector<T,Allocator>)\fP
   reserve       reserves storage
                 \fI(public member function of std::vector<T,Allocator>)\fP
                 returns the number of elements that can be held in currently allocated
   capacity      storage
                 \fI(public member function of std::vector<T,Allocator>)\fP
.SH Modifiers
   clear         clears the contents
                 \fI(public member function of std::vector<T,Allocator>)\fP
   insert        inserts elements
                 \fI(public member function of std::vector<T,Allocator>)\fP
   emplace       constructs element in-place
   \fI(C++11)\fP       \fI(public member function of std::vector<T,Allocator>)\fP
   erase         erases elements
                 \fI(public member function of std::vector<T,Allocator>)\fP
   push_back     adds an element to the end
                 \fI(public member function of std::vector<T,Allocator>)\fP
   emplace_back  constructs an element in-place at the end
   \fI(C++11)\fP       \fI(public member function of std::vector<T,Allocator>)\fP
   pop_back      removes the last element
                 \fI(public member function of std::vector<T,Allocator>)\fP
   resize        changes the number of elements stored
                 \fI(public member function of std::vector<T,Allocator>)\fP
   swap          swaps the contents
                 \fI(public member function of std::vector<T,Allocator>)\fP
.SH vector<bool> specific modifiers
   flip          flips all the bits
                 \fI(public member function)\fP
   swap          swaps two std::vector<bool>::references
   \fB[static]\fP      \fI(public static member function)\fP

.SH Non-member functions

   operator==
   operator!=
   operator<
   operator<=
   operator>
   operator>=             lexicographically compares the values in the vector
   operator<=>            \fI(function template)\fP
   (removed in C++20)
   (removed in C++20)
   (removed in C++20)
   (removed in C++20)
   (removed in C++20)
   (C++20)
   std::swap(std::vector) specializes the std::swap algorithm
                          \fI(function template)\fP
   erase(std::vector)     Erases all elements satisfying specific criteria
   erase_if(std::vector)  \fI(function template)\fP
   (C++20)

.SH Helper classes

   std::hash<std::vector<bool>> hash support for std::vector<bool>
   \fI(C++11)\fP                      \fI(class template specialization)\fP

  Deduction guides \fI(C++17)\fP

.SH Notes

   If the size of the bitset is known at compile time, std::bitset may be used, which
   offers a richer set of member functions. In addition, boost::dynamic_bitset exists
   as an alternative to std::vector<bool>.

   Since its representation may be optimized, std::vector<bool> does not necessarily
   meet all Container or SequenceContainer requirements. For example, because
   std::vector<bool>::iterator is implementation-defined, it may not satisfy the
   LegacyForwardIterator requirement. Use of algorithms such as std::search that
   require LegacyForwardIterators may result in either compile-time or run-time errors.

   The Boost.Container version of vector does not specialize for bool.

  Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

      DR    Applied to              Behavior as published              Correct behavior
   LWG 2187 C++11      specializations for bool lacked emplace and     added
                       emplace_back member functions
