.TH std::swap(std::fs::path) 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   void swap( path& lhs, path& rhs );  (filesystem TS)

   Exchanges the state of lhs with that of rhs. Effectively calls lhs.swap(rhs).

.SH Parameters

   lhs, rhs - paths whose states to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH See also

   swap swaps two paths
        \fI(public member function)\fP 
