.TH std::ldexp 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   float       ldexp( float arg, int exp );
   double      ldexp( double arg, int exp );
   long double ldexp( long double arg, int exp );
   double      ldexp( Integral arg, int exp );     \fI(since C++11)\fP

   Multiplies an floating point value arg by 2 raised to power exp.

.SH Parameters

   arg - floating point value
   exp - integer value

.SH Return value

   returns arg × 2^exp

   If the result is too large for the underlying type, range error occurs and HUGE_VAL
   is returned.

.SH See also

   frexp   decomposes a number into significand and a power of 2
           \fI(function)\fP
   scalbn
   scalbln multiplies a number by FLT_RADIX raised to a power
   \fI(C++11)\fP \fI(function)\fP
   \fI(C++11)\fP
