.TH std::ranges::transform_view::size 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::transform_view::size \- std::ranges::transform_view::size

.SH Synopsis
   constexpr auto size() requires ranges::sized_range<V>;              \fI(since C++20)\fP
   constexpr auto size() const requires ranges::sized_range<const V>;  \fI(since C++20)\fP

   Returns the number of elements.

   Returns ranges::size(base_), where base_ is the underlying view.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of elements.

.SH Notes

   If V does not model forward_range, size() might not be well-defined after a call to
   begin().

.SH Example


// Run this code

 #include <iostream>
 #include <ranges>
 #include <string>
 #include <cctype>

 int main()
 {
     std::string s{"The length of this string is 42 characters"};
     auto tv = std::ranges::transform_view{s, [](char c) -> char {
         return std::toupper(c); }
     };
     for (auto x: tv) { std::cout << x; };
     std::cout << "\\nsize = " << tv.size() << '\\n';
 }

.SH Output:

 THE LENGTH OF THIS STRING IS 42 CHARACTERS
 size = 42
