.TH std::filesystem::path::swap 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::path::swap \- std::filesystem::path::swap

.SH Synopsis
   void swap( path& other ) noexcept; \fB(1)\fP \fI(since C++17)\fP

   Swaps the contents (both native and generic format) of *this and other.

.SH Parameters

   other - another path to exchange the contents with

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH See also

   swap(std::filesystem::path) swaps two paths
   \fI(C++17)\fP                     \fI(function)\fP
