.TH std::layout_left 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::layout_left \- std::layout_left

.SH Synopsis
   Defined in header <mdspan>
   struct layout_left;         (since C++23)

   layout_left is a LayoutMappingPolicy and trivial type which provides a layout
   mapping where the leftmost extent has stride 1, and strides increase left-to-right
   as the product of extents.

   Member class templates

   mapping a layout mapping of layout_left
           \fI(public member class template)\fP

.SH See also

   layout_right  row-major multidimensional array layout mapping policy; rightmost
   (C++23)       extent has stride 1
                 \fI(class)\fP
   layout_stride a layout mapping policy with user-defined strides
   (C++23)       \fI(class)\fP
