.TH std::chrono::time_of_day 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::time_of_day \- std::chrono::time_of_day

.SH Synopsis
   Defined in header <chrono>
   template< class Duration >                             \fB(1)\fP \fI(since C++20)\fP
   class time_of_day; // not defined
   template<>                                             \fB(2)\fP \fI(since C++20)\fP
   class time_of_day<std::chrono::hours>;
   template<>                                             \fB(3)\fP \fI(since C++20)\fP
   class time_of_day<std::chrono::minutes>;
   template<>                                             \fB(4)\fP \fI(since C++20)\fP
   class time_of_day<std::chrono::seconds>;
   template< class Rep, class Period >                    \fB(5)\fP \fI(since C++20)\fP
   class time_of_day<std::chrono::duration<Rep, Period>>;

   The class template time_of_day splits a std::chrono::duration representing time
   since midnight into a "broken down" time such as hours:minutes:seconds, with the
   precision of the split determined by the Duration template parameter. It also tracks
   whether it should be output in a 12-hour time format or a 24-hour time format. It is
   primarily a formatting tool.

   The primary template \fB(1)\fP is not defined; four specializations are provided to handle
   four different levels of precision.

   Each specialization of time_of_day is a TriviallyCopyable StandardLayoutType.

   The partial specialization \fB(5)\fP only exists if
   std::chrono::treat_as_floating_point_v<Rep> is false and std::chrono::duration<Rep,
   Period> is not convertible to std::chrono::seconds.

.SH Member types

   Member type Definition
   precision   Duration

.SH Member functions

   constructor        constructs a time_of_day
                      \fI(public member function)\fP 
   hours
   minutes            accesses components of the broken-down time
   seconds            \fI(public member function)\fP 
   subseconds
   operator precision accesses the stored std::chrono::duration
   to_duration        \fI(public member function)\fP 
   make12             changes the time format used for output
   make24             \fI(public member function)\fP 

   Nonmember functions

   operator<< outputs a time_of_day into a stream
              \fI(function template)\fP 
