.TH std::ranges::OutputRange 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::OutputRange \- std::ranges::OutputRange

.SH Synopsis
   Defined in header <ranges>
   template<class R, class T>
   concept OutputRange = Range<R> && OutputIterator<iterator_t<R>, T>;

   The OutputRange concept is a refinement of Range for which ranges::begin returns a
   model of OutputIterator.
