.TH std::experimental::observer_ptr<W>::operator*, 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::observer_ptr<W>::operator*, \- std::experimental::observer_ptr<W>::operator*,

.SH Synopsis

   constexpr std::add_lvalue_reference_t<element_type>        \fB(1)\fP (library fundamentals
   operator*() const;                                             TS v2)
   constexpr element_type* operator->() const noexcept;       \fB(2)\fP (library fundamentals
                                                                  TS v2)

   operator* and operator-> provide access to the object watched by *this.

   The behavior of operator* is undefined if get() == nullptr.

.SH Parameters

   \fI(none)\fP

.SH Return value

   1) Returns the object watched by *this, equivalent to *get().

   2) Returns a pointer to the object watched by *this, i.e. get().

.SH Exceptions

   1) Throws nothing.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   get returns a pointer to the watched object
       \fI(public member function)\fP
