.TH std::forward_list::before_begin,cbefore_begin 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::forward_list::before_begin,cbefore_begin \- std::forward_list::before_begin,cbefore_begin

.SH Synopsis
   iterator before_begin() noexcept;               \fI(since C++11)\fP
   const_iterator before_begin() const noexcept;   \fI(since C++11)\fP
   const_iterator cbefore_begin() const noexcept;  \fI(since C++11)\fP

   Returns an iterator to the element before the first element of the container. This
   element acts as a placeholder, attempting to access it results in undefined
   behavior. The only usage cases are in functions insert_after(), emplace_after(),
   erase_after(), splice_after() and the increment operator: incrementing the
   before-begin iterator gives exactly the same iterator as obtained from
   begin()/cbegin().

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the element before the first element.

.SH Complexity

   Constant.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   begin  returns an iterator to the beginning
   cbegin \fI(public member function)\fP
   end    returns an iterator to the end
   cend   \fI(public member function)\fP

.SH Category:
     * Todo no example
