.TH std::acos(std::complex) 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <complex>
   template< class T >                      \fI(since C++11)\fP
   complex<T> acos( const complex<T>& z );

   Computes complex arc cosine of a complex value z. Branch cut exists outside the
   interval [−1 ; +1] along the real axis.

.SH Parameters

   z - complex value

.SH Return value

   Complex arc cosine of z in the range [0 ; ∞) along the real axis and in the range
   [−iπ ; iπ] along the imaginary axis.

.SH See also

   asin(std::complex) computes arc sine of a complex number (arcsin(z))
   \fI(C++11)\fP            \fI(function template)\fP
   atan(std::complex) computes arc tangent of a complex number (arctan(z))
   \fI(C++11)\fP            \fI(function template)\fP
