.TH std::experimental::latch::is_ready 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::latch::is_ready \- std::experimental::latch::is_ready

.SH Synopsis
   bool is_ready() const noexcept; \fB(1)\fP (concurrency TS)

   Returns true if the internal counter equals zero.

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if the internal counter of *this latch equals zero.
