.TH std::chrono::operator<<(std::chrono::year_month) 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator<<(std::chrono::year_month) \- std::chrono::operator<<(std::chrono::year_month)

.SH Synopsis
   Defined in header <chrono>
   template< class CharT, class Traits >

   std::basic_ostream<CharT, Traits>&                                     \fI(since C++20)\fP

   operator<<( std::basic_ostream<CharT, Traits>& os, const
   std::chrono::year_month& ym );

   Outputs a textual representation of ym into the stream os, as if by

   os << std::format(os.getloc(), STATICALLY_WIDEN<CharT>("{}/{:L}"), ym.year(),
   ym.month())

   where STATICALLY_WIDEN<CharT>("{}/{:L}") is "{}/{:L}" if CharT is char, and
   L"{}/{:L}" if CharT is wchar_t.

.SH Return value

   os.

  Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to        Behavior as published               Correct behavior
   P2372R3 C++20      the given locale was used by default L is needed to use the given
                                                           locale

.SH See also

   format                                  stores formatted representation of the
   (C++20)                                 arguments in a new string
                                           \fI(function template)\fP
                                           specialization of std::formatter that
   std::formatter<std::chrono::year_month> formats a year_month according to the
   (C++20)                                 provided format
                                           \fI(class template specialization)\fP
