.TH std::any::~any 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::any::~any \- std::any::~any

.SH Synopsis
   ~any();  \fI(since C++17)\fP

   Destroys the contained object, if any, as if by a call to reset().

.SH See also

   reset destroys contained object
         \fI(public member function)\fP
