.TH std::swap(std::forward_list) 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::swap(std::forward_list) \- std::swap(std::forward_list)

.SH Synopsis
   template< class T, class Alloc >
                                                            \fI(since C++11)\fP
   void swap( forward_list<T,Alloc>& lhs,                   \fI(until C++17)\fP

   forward_list<T,Alloc>& rhs );
   template< class T, class Alloc >

   void swap( forward_list<T,Alloc>& lhs,                   \fI(since C++17)\fP

   forward_list<T,Alloc>& rhs ) noexcept(/* see below */);

   Specializes the std::swap algorithm for std::forward_list. Swaps the contents of lhs
   and rhs. Calls lhs.swap(rhs).

.SH Parameters

   lhs, rhs - containers whose contents to swap

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH Exceptions

   noexcept specification:           \fI(since C++17)\fP
   noexcept(noexcept(lhs.swap(rhs)))

.SH See also

   swap swaps the contents
        \fI(public member function)\fP
