.TH std::char_traits::not_eof 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::char_traits::not_eof \- std::char_traits::not_eof

.SH Synopsis
   static int_type not_eof( int_type e );                     \fI(until C++11)\fP
   static constexpr int_type not_eof( int_type e ) noexcept;  \fI(since C++11)\fP

   Checks whether e is not equivalent to eof value.

   Formally

     * if X::eq_int_type(e, X::eof()) is false, returns e
     * otherwise, returns a value f such that X::eq_int_type(f, X::eof()) is false

.SH Parameters

   e - value to analyze

.SH Return value

   e if e and eof value are not equivalent, returns some other non-eof value otherwise.

.SH Complexity

   Constant.

.SH See also

   eof      returns an eof value
   \fB[static]\fP \fI(public static member function)\fP 
