.TH std::bad_weak_ptr::bad_weak_ptr 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   bad_weak_ptr();

   Constructs new bad_weak_ptr object. what() returns "bad_weak_ptr" afterwards.

.SH Parameters

   \fI(none)\fP

.SH Exceptions

   \fI(none)\fP                    \fI(until C++11)\fP
   noexcept specification:  
   noexcept                  \fI(since C++11)\fP
     
