.TH std::match_results::max_size 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   size_type max_size() const;  \fI(since C++11)\fP

   Returns the maximum number of submatches the match_results type is able to hold due
   to system or library implementation limitations, i.e. std::distance(begin(), end())
   for the largest number of submatches.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Maximum number of submatches

.SH Exceptions

   noexcept specification:
   noexcept

.SH Complexity

   Constant.

.SH Category:

     * unconditionally noexcept
