.TH std::cosh(std::valarray) 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <valarray>
   template< class T >
   valarray<T> cosh( const valarray<T>& va );

   For each element in va computes hyperbolic cosine of the value of the element.

.SH Parameters

   va - value array to apply the operation to

.SH Return value

   Value array containing hyperbolic cosine of the values in va.

.SH Notes

   Unqualified function (cosh) is used to perform the computation. If such function is
   not available, std::cosh is used due to argument dependent lookup.

   The function can be implemented with the return type different from std::valarray.
   In this case, the replacement type has the following properties:

     * All const member functions of std::valarray are provided.
     * std::valarray, std::slice_array, std::gslice_array, std::mask_array and
       std::indirect_array can be constructed from the replacement type.
     * All functions accepting a arguments of type const std::valarray& should also
       accept the replacement type.
     * All functions accepting two arguments of type const std::valarray& should accept
       every combination of const std::valarray& and the replacement type.
     * The return type does not add more than two levels of template nesting over the
       most deeply-nested argument type.

.SH Possible implementation

   template<class T>
   valarray<T> cosh(const valarray<T>& va)
   {
       valarray<T> other = va;
       for (T &i : other) {
           i = cosh(i);
       }
   }

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   cosh computes hyperbolic cosine (ch(x))
        \fI(function)\fP 

.SH Category:

     * Todo no example
