.TH std::multimap::rbegin, 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::multimap::rbegin, \- std::multimap::rbegin,

.SH Synopsis

   reverse_iterator rbegin();                        \fI(until C++11)\fP
   reverse_iterator rbegin() noexcept;               \fI(since C++11)\fP
   const_reverse_iterator rbegin() const;            \fI(until C++11)\fP
   const_reverse_iterator rbegin() const noexcept;   \fI(since C++11)\fP
   const_reverse_iterator crbegin() const noexcept;  \fI(since C++11)\fP

   Returns a reverse iterator to the first element of the reversed multimap. It
   corresponds to the last element of the non-reversed multimap. If the multimap is
   empty, the returned iterator is equal to rend().

   range-rbegin-rend.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reverse iterator to the first element.

.SH Complexity

   Constant.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   rend    returns a reverse iterator to the end
   crend   \fI(public member function)\fP
   \fI(C++11)\fP

.SH Category:

     * Todo no example
