.TH std::experimental::basic_string_view::max_size 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::basic_string_view::max_size \- std::experimental::basic_string_view::max_size

.SH Synopsis
   constexpr size_type max_size() const;  (library fundamentals TS)

   The largest possible number of char-like objects that can be referred to by a
   basic_string_view.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Maximum number of characters.

.SH Exceptions

   noexcept specification:
   noexcept

.SH Complexity

   Constant.

.SH See also

   size   returns the number of characters
   length \fI(public member function)\fP
   empty  checks whether the view is empty
          \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept
