.TH std::use_facet 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <locale>
   template< class Facet >
   const Facet& use_facet( const std::locale& loc );

   Obtains a reference to a facet implemented by loc.

.SH Contents

     • 1 Parameters
     • 2 Return value
     • 3 Exceptions
     • 4 Example
     • 5 See also

.SH Parameters

   loc - the locale object to query

.SH Return value

   Returns a reference the facet. The reference returned by this function is valid as
   long as any std::locale object exists that implements Facet.

.SH Exceptions

   std::bad_cast if std::has_facet<Facet>(loc) == false.

.SH Example

   Display the 3-letter currency name used by the user's preferred locale

   
// Run this code

 #include <iostream>
 #include <locale>

 int main()
 {
     std::locale loc = std::locale(""); // user's preferred locale
     std::cout << "Your currency string is "
               << std::use_facet<std::moneypunct<char, true>>(loc).curr_symbol() << '\\n';
 }

.SH Output:

 Your currency string is USD

.SH See also

   locale    set of polymorphic facets that encapsulate cultural differences
             \fI(class)\fP
   has_facet checks if a locale implements a specific facet
             \fI(function template)\fP
