.TH std::experimental::filesystem::path::replace_filename 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::filesystem::path::replace_filename \- std::experimental::filesystem::path::replace_filename

.SH Synopsis
   path& replace_filename( const path& replacement ); \fB(1)\fP (filesystem TS)

   Replaces a single filename component with replacement. Equivalent to the following:

   remove_filename();
   operator/=(replacement);

.SH Parameters

   \fI(none)\fP

.SH Return value

   *this

.SH Exceptions

   \fI(none)\fP

.SH Example

   
// Run this code

 #include <filesystem>
 #include <iostream>
  
 int main()
 {
     std::cout << std::fs::path("/foo").replace_filename("bar") << '\\n';
     std::cout << std::fs::path("/").replace_filename("bar") << '\\n';
 }

.SH Output:

 /bar
 bar

.SH See also

   replace_extension replaces the extension
                     \fI(public member function)\fP 
