.TH std::ostrstream::rdbuf 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ostrstream::rdbuf \- std::ostrstream::rdbuf

.SH Synopsis
   strstreambuf* rdbuf() const;  (deprecated in C++98)
                                 (removed in C++26)

   Returns a pointer to the associated std::strstreambuf, casting away its constness
   (despite the const qualifier on the member function).

.SH Parameters

   \fI(none)\fP

.SH Return value

   Pointer to the associated std::strstreambuf, with constness cast away.

.SH Example


// Run this code

 #include <strstream>

 int main()
 {
     const std::ostrstream buf;
     std::strstreambuf* ptr = buf.rdbuf();
 }
