.TH std::isless 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::isless \- std::isless

.SH Synopsis
   Defined in header <cmath>
   bool isless( float x, float y );             \fB(1)\fP \fI(since C++11)\fP
   bool isless( double x, double y );           \fB(2)\fP \fI(since C++11)\fP
   bool isless( long double x, long double y ); \fB(3)\fP \fI(since C++11)\fP
   bool isless( Arithmetic x, Arithmetic y );   \fB(4)\fP \fI(since C++11)\fP

   1-3) Determines if the floating point number x is less than the floating-point
   number y, without setting floating-point exceptions.
   4) A set of overloads or a function template for all combinations of arguments of
   arithmetic type not covered by (1-3). If any argument has integral type, it is cast
   to double.

.SH Parameters

   x - floating point value
   y - floating point value

.SH Return value

   true if x < y, false otherwise

.SH Notes

   The built-in operator< for floating-point numbers may raise FE_INVALID if one or
   both of the arguments is NaN. This function is a "quiet" version of operator<.

.SH See also

   less      function object implementing x < y
             \fI(class template)\fP 
   isgreater checks if the first floating-point argument is greater than the second
   \fI(C++11)\fP   \fI(function)\fP 
   C documentation for
   isless
