.TH std::swap(std::basic_regex) 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::swap(std::basic_regex) \- std::swap(std::basic_regex)

.SH Synopsis
   template< class CharT, class Traits >
   void swap( basic_regex<CharT,Traits> &lhs, basic_regex<CharT,Traits>   \fI(since C++11)\fP
   &rhs );

   Overloads the std::swap algorithm for std::basic_regex. Exchanges the state of lhs
   with that of rhs. Effectively calls lhs.swap(rhs).

.SH Parameters

   lhs, rhs - regular expressions to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   swap swaps the contents
        \fI(public member function)\fP

   Categories:

     * unconditionally noexcept
     * Todo no example
