.TH std::array<T,N>::rbegin,std::array<T,N>::crbegin 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::array<T,N>::rbegin,std::array<T,N>::crbegin \- std::array<T,N>::rbegin,std::array<T,N>::crbegin

.SH Synopsis
   reverse_iterator rbegin() noexcept;                         \fI(until C++17)\fP
   constexpr reverse_iterator rbegin() noexcept;               \fI(since C++17)\fP
   const_reverse_iterator rbegin() const noexcept;             \fI(until C++17)\fP
   constexpr const_reverse_iterator rbegin() const noexcept;   \fI(since C++17)\fP
   const_reverse_iterator crbegin() const noexcept;            \fI(until C++17)\fP
   constexpr const_reverse_iterator crbegin() const noexcept;  \fI(since C++17)\fP

   Returns a reverse iterator to the first element of the reversed container. It
   corresponds to the last element of the non-reversed container. If the container is
   empty, the returned iterator is equal to rend().

   range-rbegin-rend.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reverse iterator to the first element.

.SH Complexity

   Constant.

.SH See also

   rend  returns a reverse iterator to the end
   crend \fI(public member function)\fP
