.TH std::ostreambuf_iterator::operator++ 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ostreambuf_iterator::operator++ \- std::ostreambuf_iterator::operator++

.SH Synopsis
   ostreambuf_iterator& operator++();
   ostreambuf_iterator& operator++( int );

   Does nothing. These operator overloads are provided to satisfy the requirements of
   LegacyOutputIterator. They make it possible for the expressions *iter++=value and
   *++iter=value to be used to output (insert) a value into the underlying stream.

.SH Parameters

   \fI(none)\fP

.SH Return value

   *this
