.TH std::experimental::flex_barrier::~flex_barrier 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::flex_barrier::~flex_barrier \- std::experimental::flex_barrier::~flex_barrier

.SH Synopsis
   ~flex_barrier();  (concurrency TS)

   Destroys the flex_barrier.

   The behavior is undefined if a thread is blocked at the synchronization point.
