.TH std::experimental::erase_if(std::basic_string) 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::erase_if(std::basic_string) \- std::experimental::erase_if(std::basic_string)

.SH Synopsis
   Defined in header <experimental/string>
   template <class CharT, class Traits, class Alloc, class
   Predicate>                                                      (library
   void erase_if(std::basic_string<CharT,Traits,Alloc>& c,         fundamentals TS v2)
   Predicate pred);

   Erases all elements that satisfy the predicate pred from the container. Equivalent
   to c.erase(std::remove_if(c.begin(), c.end(), pred), c.end());

.SH Parameters

   c    - container from which to erase
   pred - predicate that determines which elements should be erased

.SH Complexity

   Linear.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   remove                      removes elements satisfying specific criteria
   remove_if                   \fI(function template)\fP 
   erase (std::basic_string)   Erases all elements equal to a specific value from a
   (library fundamentals 2 TS) std::basic_string
                               \fI(function template)\fP 

.SH Category:

     * Todo no example
