.TH std::experimental::get_underlying 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::get_underlying \- std::experimental::get_underlying

.SH Synopsis
   template< class T >                                         (library fundamentals TS
   constexpr T& get_underlying(propagate_const<T>& pt);        v2)
   template< class T >                                         (library fundamentals TS
   constexpr const T& get_underlying(const                     v2)
   propagate_const<T>& pt);

   Retrieves a reference to the pointer-like object stored in a propagate_const.

.SH Parameters

   pt - a propagate_const object

.SH Return value

   A reference to the pointer-like object stored in pt.

.SH Exceptions

   noexcept specification:  
   noexcept
     
.SH Category:

     * unconditionally noexcept
