.TH std::deque::front 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::deque::front \- std::deque::front

.SH Synopsis
   reference front();
   const_reference front() const;

   Returns a reference to the first element in the container.

   Calling front on an empty container is undefined.

.SH Parameters

   \fI(none)\fP

.SH Return value

   reference to the first element

.SH Complexity

   Constant

.SH Notes

   For a container c, the expression c.front() is equivalent to *c.begin().

.SH Example

   The following code uses front to display the first element of a std::deque<char>:


// Run this code

 #include <deque>
 #include <iostream>

 int main()
 {
     std::deque<char> letters {'o', 'm', 'g', 'w', 't', 'f'};

     if (!letters.empty()) {
         std::cout << "The first character is '" << letters.front() << "'.\\n";
     }
 }

.SH Output:

 The first character is 'o'.

.SH See also

   back access the last element
        \fI(public member function)\fP
