.TH std::chrono::month_weekday_last::month,std::chrono::month_weekday_last::weekday_last 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month_weekday_last::month,std::chrono::month_weekday_last::weekday_last \- std::chrono::month_weekday_last::month,std::chrono::month_weekday_last::weekday_last

.SH Synopsis
   constexpr std::chrono::month month() const noexcept;               \fB(1)\fP \fI(since C++20)\fP
   constexpr std::chrono::weekday_last weekday_last() const noexcept; \fB(2)\fP \fI(since C++20)\fP

   Retrieves a copy of the month and weekday_last objects stored in *this.

.SH Return value

   1) a copy of the std::chrono::month object stored in *this
   2) a copy of the std::chrono::weekday_last object stored in *this
