.TH std::chrono::month_weekday::ok 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month_weekday::ok \- std::chrono::month_weekday::ok

.SH Synopsis
   constexpr bool ok() const noexcept;  \fI(since C++20)\fP

   Checks if the contained month and weekday_indexed objects are valid.

.SH Return value

   month().ok() && weekday_indexed().ok()

.SH Example


// Run this code

 #include <cassert>
 #include <chrono>

 int main()
 {
     auto mwdi{std::chrono::March/std::chrono::Friday[1]};
     assert(mwdi.ok());

     mwdi = {std::chrono::month(17)/std::chrono::Friday[1]};
     assert(not mwdi.ok());

     mwdi = {std::chrono::March/std::chrono::Friday[-4]};
     assert(not mwdi.ok());
 }
