.TH std::basic_filebuf::open 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   std::basic_filebuf<CharT, Traits>* open( const char* s,            \fB(1)\fP
   std::ios_base::openmode mode )
   std::basic_filebuf<CharT, Traits>* open( const std::string& str,   \fB(2)\fP \fI(since C++11)\fP
   std::ios_base::openmode mode )

   Opens the file with the given name - either s or str.c_str().

   The file is opened as if by calling std::fopen(s, modestring), where modestring is
   determined as follows:

   modestring openmode & ~ate
   "r"        in
   "w"        out, out|trunc
   "a"        app, out|app
   "r+"       out|in
   "w+"       out|in|trunc
   "a+"       out|in|app, in|app
   "rb"       binary|in
   "wb"       binary|out, binary|out|trunc
   "ab"       binary|app, binary|out|app
   "r+b"      binary|out|in
   "w+b"      binary|out|in|trunc
   "a+b"      binary|out|in|app, binary|in|app

   If openmode is not one of the modes listed, the open() fails.

   If the open operation succeeds and openmode & std::ios_base::ate != 0 (the ate bit
   is set), repositions the file position to the end of file, as if by calling
   std::fseek(file, 0, SEEK_END). If the repositioning fails, calls close() and returns
   a null pointer to indicate failure.

   If the associated file was already open, returns a null pointer right away.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Notes
     * 4 Example
     * 5 See also

.SH Parameters

   s, str   - the file name to open
   openmode - the file opening mode, a binary OR of the std::ios_base modes

.SH Return value

   *this on success, a null pointer on failure.

.SH Notes

   open() is typically called through the constructor or the open() member function of
   std::basic_fstream.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   is_open checks if the associated file is open
           \fI(public member function)\fP
   close   flushes the put area buffer and closes the associated file
           \fI(public member function)\fP

.SH Category:

     * Todo no example
