.TH std::filesystem::path::clear 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::path::clear \- std::filesystem::path::clear

.SH Synopsis
   void clear();  \fI(since C++17)\fP

   Clears the stored pathname. empty() is true after the call.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept
.SH Category:

     * unconditionally noexcept

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
