.TH std::type_info::~type_info 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   virtual ~type_info();

   Destructs an object of type std::type_info. This destructor is public virtual,
   allowing objects of classes, derived from std::type_info to be safely deleted
   through pointers to base class.
