.TH std::barrier::~barrier 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::barrier::~barrier \- std::barrier::~barrier

.SH Synopsis
   ~barrier();  \fI(since C++20)\fP

   Destroys the barrier.

.SH Notes

   The behavior is undefined if any thread is concurrently calling a member function of
   the barrier.
