.TH std::isgreater 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   bool isgreater( float x, float y );              \fI(since C++11)\fP
   bool isgreater( double x, double y );            \fI(since C++11)\fP
   bool isgreater( long double x, long double y );  \fI(since C++11)\fP

   Determines if the floating point number x is greater than the floating-point number
   (y), without setting floating-point exceptions.

.SH Parameters

   x - floating point value
   y - floating point value

.SH Return value

   true if x > y, false otherwise

.SH Notes

   The built-in operator> for floating-point numbers may set FE_INVALID if one or both
   of the arguments is NaN. This function is a "quiet" version of operator>.

.SH See also

   greater function object implementing x > y
           \fI(class template)\fP 
   isless  checks if the first floating-point argument is less than the second
   \fI(C++11)\fP \fI(function)\fP 
