.TH std::expm1 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::expm1 \- std::expm1

.SH Synopsis
   Defined in header <cmath>
   float       expm1( float arg );        \fI(since C++11)\fP
   double      expm1( double arg );       \fI(since C++11)\fP
   long double expm1( long double arg );  \fI(since C++11)\fP
   double      expm1( Integral arg );     \fI(since C++11)\fP

   Computes the e (Euler's number, 2.7182818) raised to the given power arg, minus 1.
   This function is more accurate than the expression std::exp(arg)-1 if arg is close
   to zero.

.SH Parameters

   arg - value of floating-point or Integral type

.SH Return value

   earg
   -1

   If the result is too large for the underlying type, range error occurs and HUGE_VAL
   is returned.

.SH See also

   exp     returns e raised to the given power (e^x)
           \fI(function)\fP 
   log1p   natural logarithm (to base e) of 1 plus the given number
   \fI(C++11)\fP \fI(function)\fP 
   exp2    returns 2 raised to the given power (2^x)
   \fI(C++11)\fP \fI(function)\fP 
   C documentation for
   expm1
