.TH std::ostream_iterator<T,CharT,Traits>::operator++ 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ostream_iterator<T,CharT,Traits>::operator++ \- std::ostream_iterator<T,CharT,Traits>::operator++

.SH Synopsis
   ostream_iterator& operator++();
   ostream_iterator& operator++( int );

   Does nothing. These operator overloads are provided to satisfy the requirements of
   LegacyOutputIterator. They make it possible for the expressions *iter++=value and
   *++iter=value to be used to output (insert) a value into the underlying stream.

.SH Parameters

   \fI(none)\fP

.SH Return value

   *this
