.TH std::experimental::ranges::Sentinel 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::Sentinel \- std::experimental::ranges::Sentinel

.SH Synopsis
   Defined in header <experimental/ranges/iterator>
   template < class S, class I >

   concept bool Sentinel =                             (ranges TS)
     ranges::Semiregular<S> && ranges::Iterator<I> &&

     ranges::WeaklyEqualityComparableWith<S, I>;

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
