.TH std::chrono::year_month_day_last::year,std::chrono::year_month_day_last::month, 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year_month_day_last::year,std::chrono::year_month_day_last::month, \- std::chrono::year_month_day_last::year,std::chrono::year_month_day_last::month,

.SH Synopsis

   constexpr std::chrono::year year() const noexcept;                 \fB(1)\fP \fI(since C++20)\fP
   constexpr std::chrono::month month() const noexcept;               \fB(2)\fP \fI(since C++20)\fP
   constexpr std::chrono::day day() const noexcept;                   \fB(3)\fP \fI(since C++20)\fP
   constexpr std::chrono::month_day_last month_day_last() const       \fB(4)\fP \fI(since C++20)\fP
   noexcept;

   Retrieves the field values stored in this year_month_day_last object.

.SH Return values

   1) Returns the stored std::chrono::year value.
   2) Returns the stored std::chrono::month value.
   3) A std::chrono::day value corresponding to the last day of the stored year and
   month.
   4) A std::chrono::month_day_last constructed from month().

.SH Notes

   The behavior of \fB(3)\fP when !this->ok() is not currently defined. It likely will be
   defined to return some invalid day in that case (such as std::chrono::day\fB(0)\fP).
