.TH std::experimental::reflect::Operator 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::reflect::Operator \- std::experimental::reflect::Operator

.SH Synopsis
   Defined in header <experimental/reflect>
   template< class T >                                 (reflection TS)
   concept Operator = Function<T> && /* see below */;

   The Operator concept is satisfied if and only if T reflects an operator function or
   a conversion function (Note: Some types that satisfy Operator also satisfy
   MemberFunction or SpecialMemberFunction).

.SH Example

    This section is incomplete
    Reason: examples

.SH See also

    This section is incomplete
    Reason: templatization

.SH Category:
     * Todo with reason
