.TH std::experimental::ranges::Permutable 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::Permutable \- std::experimental::ranges::Permutable

.SH Synopsis
   template< class I >

   concept bool Permutable =
       ForwardIterator<I> &&               (ranges TS)
       IndirectlyMovableStorable<I, I> &&

       IndirectlySwappable<I, I>;

   The Permutable concept specifies the common requirements of algorithms that reorder
   elements in place by moving or swapping them (for example, ranges::rotate).
