.TH std::ranges::chunk_view::iterator::base 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::chunk_view::iterator::base \- std::ranges::chunk_view::iterator::base

.SH Synopsis
   constexpr ranges::iterator_t<Base> base() const;  (since C++23)

   Returns the underlying iterator to the begin of current chunk.

   Equivalent to return current_;.

.SH Parameters

   \fI(none)\fP

.SH Return value

   An iterator.

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
