.TH std::ranges::join_view::iterator::operator*,-> 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::join_view::iterator::operator*,-> \- std::ranges::join_view::iterator::operator*,->

.SH Synopsis
   constexpr decltype(auto) operator*() const;                      \fB(1)\fP \fI(since C++20)\fP
   constexpr InnerIter operator->() const                           \fB(2)\fP \fI(since C++20)\fP
     requires /*has-arrow*/<InnerIter> && std::copyable<InnerIter>;

   Returns the element the underlying iterator inner_ points to.

   1) Equivalent to return *inner_;.
   2) Equivalent to return inner_;.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The current element.

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
