.TH std::experimental::filesystem::canonical 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::filesystem::canonical \- std::experimental::filesystem::canonical

.SH Synopsis
   Defined in header <experimental/filesystem>
   path canonical( const path& p, const path& base = current_path() \fB(1)\fP (filesystem TS)
   );
   path canonical( const path& p, error_code& ec );                 \fB(2)\fP (filesystem TS)
   path canonical( const path& p, const path& base, error_code& ec  \fB(3)\fP (filesystem TS)
   );

   Converts path p to a canonical absolute path, i.e. one that has no dot, dot-dot
   elements or symbolic links. p is optionally relative to base.

   p must resolve to an existing file, otherwise error occurs.

   The return path resolves to the same path as absolute(p, base (or absolute(p) for
   \fB(2)\fP}}.

    This section is incomplete
    Reason: errors

.SH Parameters

    This section is incomplete

   ec - error code to store error status to

.SH Return value

   The canonical absolute path of p, which is optionally relative to base.

.SH Exceptions

    This section is incomplete

.SH See also

    This section is incomplete

   Categories:

     * Todo with reason
     * Todo without reason
