.TH std::locale::operator==,operator!= 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <locale>
   bool operator==( const locale& other ) const; \fB(1)\fP
   bool operator!=( const locale& other ) const; \fB(2)\fP

   Tests two locales for equality. Named locales are considered equal if their names
   are equal. Unnamed locales are considered equal if they are copies of each other.

.SH Contents

     • 1 Parameters
     • 2 Return value
     • 3 Example
     • 4 See also

.SH Parameters

   other - a std::locale object to compare

.SH Return value

   1) true if other is a copy of *this or has an identical name, false otherwise.

   2) false if other is a copy of *this or has an identical name, true otherwise.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   constructor   constructs a new locale
                 \fI(public member function)\fP
   name          returns the name of the locale or "*" if unnamed
                 \fI(public member function)\fP

.SH Category:

     • Todo no example
