.TH std::erase_if(std::unordered_multimap) 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::erase_if(std::unordered_multimap) \- std::erase_if(std::unordered_multimap)

.SH Synopsis
   Defined in header <unordered_map>
   template< class Key, class T, class Hash, class KeyEqual, class Alloc,
   class Pred >                                                             \fB(1)\fP (since
   void erase_if(std::unordered_multimap<Key,T,Hash,KeyEqual,Alloc>& c,         C++20)
   Pred pred);

   Erases all elements that satisfy the predicate pred from the container. Equivalent
   to

 for (auto i = c.begin(), last = c.end(); i != last; ) {
   if (pred(*i)) {
     i = c.erase(i);
   } else {
     ++i;
   }
 }

.SH Parameters

   c    - container from which to erase
   pred - predicate that returns true if the element should be erased

.SH Complexity

   Linear.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   remove    removes elements satisfying specific criteria
   remove_if \fI(function template)\fP
