.TH std::tgamma 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   float tgamma( float arg );              \fI(since C++11)\fP
   double tgamma( double arg );            \fI(since C++11)\fP
   long double tgamma( long double arg );  \fI(since C++11)\fP
   double tgamma( Integral arg );          \fI(since C++11)\fP

   Computes the gamma function of arg.

.SH Contents

     • 1 Parameters
     • 2 Return value
     • 3 Exceptions
     • 4 Notes
     • 5 Example
     • 6 See also
     • 7 External links

.SH Parameters

   arg - value of a floating-point or Integral type

.SH Return value

   The value of the gamma function of arg, that is ∫∞
   0targ-1
   e^-t dt.

   If arg is a natural number, std::tgamma(arg) is the factorial of arg-1.

.SH Exceptions

   If arg is negative, domain error may occur and FE_INVALID may be raised.

   If arg is zero, pole error may occur and FE_DIVBYZERO may be raised.

   If arg is too large, range error may occur and FE_OVERFLOW may be raised.

   If arg is too small, range error may occur and FE_UNDERFLOW may be raised.

.SH Notes

   Many implementations calculate the exact integer-domain factorial if the argument is
   a sufficiently small integer.

.SH Example

   
// Run this code

 #include <iostream>
 #include <cmath>
 double factorial(double arg)
 {
     return std::tgamma(arg + 1);
 }
 int main()
 {
     std::cout << "The factorial of 5 is " << factorial(5) << '\\n'
               << "The factorial of 100 is " << factorial(100) << '\\n';
 }

.SH Output:

 The factorial of 5 is 120
 The factorial of 100 is 9.33262e+157

.SH See also

   lgamma  natural logarithm of the gamma function
   \fI(C++11)\fP \fI(function)\fP

.SH External links

   Weisstein, Eric W. "Gamma Function." From MathWorld--A Wolfram Web Resource.
