.TH std::pmr::polymorphic_allocator::select_on_container_copy_construction 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::pmr::polymorphic_allocator::select_on_container_copy_construction \- std::pmr::polymorphic_allocator::select_on_container_copy_construction

.SH Synopsis
   polymorphic_allocator select_on_container_copy_construction() const;  \fI(since C++17)\fP

   Returns a default-constructed polymorphic_allocator object.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A default-constructed polymorphic_allocator object.

.SH Notes

   polymorphic_allocators do not propagate on container copy construction.

.SH See also

                                         obtains the allocator to use after copying a
   select_on_container_copy_construction standard container
   \fB[static]\fP                              \fI\fI(public static member\fP function of\fP
                                         std::allocator_traits)
