.TH std::get_terminate 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <exception>
   std::terminate_handler get_terminate();  \fI(since C++11)\fP

   Returns the currently installed std::terminate_handler, which may be a null pointer.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Exceptions
     * 4 See also

.SH Parameters

   \fI(none)\fP

.SH Return value

   The currently installed std::terminate_handler.

.SH Exceptions

   noexcept specification:
   noexcept

.SH See also

   terminate_handler the type of the function called by std::terminate
                     \fI(typedef)\fP
   set_terminate     changes the function to be called by std::terminate
                     \fI(function)\fP
