.TH std::move_iterator::move_iterator 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   move_iterator();                                \fB(1)\fP
   explicit move_iterator( Iterator x );           \fB(2)\fP
   template< class U >                             \fB(3)\fP
   move_iterator( const move_iterator<U>& other );

   Constructs a new iterator adaptor.

   1) Default constructor. current is value-initialized. This makes sense only if
   operations on an value-initialized Iterator make also sense.
   2) current is initialized with x.
   3) Copy constructor. The underlying iterator is initialized with that of other.

.SH Parameters

   x     - iterator to adapt
   other - iterator adaptor to copy

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator= assigns another iterator
             \fI(public member function)\fP

.SH Category:

     * Todo no example
