.TH std::basic_ifstream::rdbuf 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_ifstream::rdbuf \- std::basic_ifstream::rdbuf

.SH Synopsis
   std::basic_filebuf<CharT, Traits>* rdbuf() const;  \fI(since C++11)\fP

   Returns pointer to the underlying raw file device object.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Pointer to the underlying raw file device.

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
