.TH std::filesystem::path::format 3 "2022.07.31" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::path::format \- std::filesystem::path::format

.SH Synopsis
   enum format {

   native_format,
   generic_format,  \fI(since C++17)\fP
   auto_format

   };

   Determines how string representations of pathnames are interpreted by the
   constructors of std::filesystem::path that accept strings.

.SH Constants

   Value          Explanation
   native_format  Native pathname format
   generic_format Generic pathname format
   auto_format    Implementation-defined pathname format, auto-detected where possible

.SH Notes

   On POSIX systems, there is no difference between native and generic format.

.SH See also

   constructor   constructs a path
                 \fI(public member function)\fP
