.TH std::weibull_distribution::a,b 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::weibull_distribution::a,b \- std::weibull_distribution::a,b

.SH Synopsis
   RealType a() const; \fB(1)\fP \fI(since C++11)\fP
   RealType b() const; \fB(2)\fP \fI(since C++11)\fP

   Returns the parameters the distribution was constructed with.

   1) Returns the a parameter. It defines the shape of the distribution. The default
   value is 1.0.
   2) Returns the b parameter. It defines the scale of the distribution. The default
   value is 1.0.

.SH Parameters

   \fI(none)\fP

.SH Return value

   1) The value of the a parameter.
   2) The value of the b parameter.

.SH Complexity

   Constant.

.SH See also

   param gets or sets the distribution parameter object
         \fI(public member function)\fP 
