.TH std::basic_regex::getloc 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_regex::getloc \- std::basic_regex::getloc

.SH Synopsis
   locale_type getloc() const;  \fI(since C++11)\fP

   Returns the current locale associated with the regular expression.

   Effectively calls traits_i.getloc() where traits_i is a default initialized instance
   of the type Traits, stored within the regular expression object.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The current locale associated with the regular expression.

.SH Exceptions

   May throw implementation-defined exceptions.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   imbue set locale information
         \fI(public member function)\fP

.SH Category:

     * Todo no example
