.TH std::generator::operator= 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::generator::operator= \- std::generator::operator=

.SH Synopsis
   generator& operator=( generator other ) noexcept;  (since C++23)

   Replaces the contents of the generator object.

   Equivalent to:

 std::swap(coroutine_, other.coroutine_);
 std::swap(active_, other.active_);

.SH Parameters

   other - another generator to be moved from

.SH Return value

   *this

.SH Complexity

    This section is incomplete

.SH Notes

   Iterators previously obtained from other are not invalidated – they become iterators
   into *this.

   This assignment operator is technically a copy assignment operator, although
   std::generator is only move assignable.

.SH Example

    This section is incomplete
    Reason: no example

.SH Categories:
     * Todo without reason
     * Todo no example
