.TH std::list::rbegin,std::list::crbegin 3 "Nov 25 2015" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::list::rbegin,std::list::crbegin \- std::list::rbegin,std::list::crbegin

.SH Synopsis
   reverse_iterator rbegin();
   const_reverse_iterator rbegin() const;
   const_reverse_iterator crbegin() const;  \fI(since C++11)\fP

   Returns a reverse iterator to the first element of the reversed container. It
   corresponds to the last element of the non-reversed container.

   range-rbegin-rend.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reverse iterator to the first element.

.SH Exceptions

   \fI(none)\fP                    \fI(until C++11)\fP
   noexcept specification:  
   noexcept                  \fI(since C++11)\fP
     

.SH Complexity

   Constant.

.SH See also

   rend  returns a reverse iterator to the end
   crend \fI(public member function)\fP 

.SH Category:

     * unconditionally noexcept
