.TH std::putchar 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::putchar \- std::putchar

.SH Synopsis
   Defined in header <cstdio>
   int putchar( int ch );

   Writes a character ch to stdout. Internally, the character is converted to unsigned
   char just before being written.

   Equivalent to std::putc(ch, stdout).

.SH Parameters

   ch - character to be written

.SH Return value

   On success, returns the written character.

   On failure, returns EOF and sets the error indicator (see std::ferror()) on stdout.

.SH Example


// Run this code

 #include <cstdio>

 int main()
 {
     for (char c = 'a'; c != 'z'; ++c)
         std::putchar(c);

     // putchar return value is not equal to the argument
     int r = 0x1024;
     std::printf("\\nr = 0x%x\\n", r);
     r = std::putchar(r);
     std::printf("\\nr = 0x%x\\n", r);
 }

.SH Possible output:

 abcdefghijklmnopqrstuvwxy
 r = 0x1024
 $
 r = 0x24

.SH See also

   fputc writes a character to a file stream
   putc  \fI(function)\fP
   C documentation for
   putchar
