.TH std::chrono::operator+,std::chrono::operator-(std::chrono::year_month_weekday) 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator+,std::chrono::operator-(std::chrono::year_month_weekday) \- std::chrono::operator+,std::chrono::operator-(std::chrono::year_month_weekday)

.SH Synopsis
   constexpr std::chrono::year_month_weekday
   operator+(const std::chrono::year_month_weekday& ymwd, const       \fB(1)\fP \fI(since C++20)\fP
   std::chrono::months& dm) noexcept;
   constexpr std::chrono::year_month_weekday
   operator+(const std::chrono::months& dm, const                     \fB(2)\fP \fI(since C++20)\fP
   std::chrono::year_month_weekday& ymwd) noexcept;
   constexpr std::chrono::year_month_weekday
   operator+(const std::chrono::year_month_weekday& ymwd, const       \fB(3)\fP \fI(since C++20)\fP
   std::chrono::years& dy) noexcept;
   constexpr std::chrono::year_month_weekday
   operator+(const std::chrono::years& dy, const                      \fB(4)\fP \fI(since C++20)\fP
   std::chrono::year_month_weekday& ymwd) noexcept;
   constexpr std::chrono::year_month_weekday
   operator-(const std::chrono::year_month_weekday& ymwd, const       \fB(5)\fP \fI(since C++20)\fP
   std::chrono::months& dm) noexcept;
   constexpr std::chrono::year_month_weekday
   operator-(const std::chrono::year_month_weekday& ymwd, const       \fB(6)\fP \fI(since C++20)\fP
   std::chrono::years& dy) noexcept;

   1-2) Adds dm.count() months to the date represented by ymwd. The result has the same
   year() and month() as std::chrono::year_month(ymwd.year(), ymwd.month()) + dm and
   the same weekday() and index() as ymwd.
   3-4) Adds dy.count() years to the date represented by ymwd. The result is equivalent
   to std::chrono::year_month_weekday(ymwd.year() + dy, ymwd.month(),
   ymwd.weekday_indexed()).
   5) Subtracts dm.count() months from the date represented by ymwd. Equivalent to ymwd
   + -dm.
   6) Subtracts dy.count() years from the date represented by ymwd. Equivalent to ymwd
   + -dy.

.SH Notes

   Even if ymwd.ok() is true, the resulting year_month_weekday may not represent a
   valid date if ymwd.index() is 5.
