.TH std::free 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cstdlib>
   void free( void* ptr );

   Deallocates the space previously allocated by std::malloc(), std::calloc() or
   std::realloc(). If ptr is null-pointer, the function does nothing.

   The behavior is undefined if ptr does not match a pointer returned earlier by
   std::malloc(), std::calloc() or std::realloc(). Also, the behavior is undefined if
   the memory area referred to by ptr has already been deallocated, that is, free() or
   std::realloc() has already been called with ptr as the argument and no calls to
   std::malloc(), std::calloc() or std::realloc() resulted in a pointer equal to ptr
   afterwards.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Example
     * 4 See also

.SH Parameters

   ptr - pointer to the memory to deallocate

.SH Return value

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   C documentation for
   free

.SH Category:

     * Todo no example
