.TH std::make_error_condition(std::errc) 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <system_error>
   std::error_condition make_error_condition( std::errc e );  \fI(since C++11)\fP

   Creates an error condition for an errc value e. Sets the error code to int(e) and
   error category to std::generic_category.

.SH Parameters

   e - standard error code

.SH Return value

   Error condition for e.

.SH Exceptions

   noexcept specification:
   noexcept
