.TH std::basic_ofstream::close 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_ofstream::close \- std::basic_ofstream::close

.SH Synopsis
   void close();

   Closes the associated file.

   Effectively calls rdbuf()->close(). If an error occurs during operation,
   setstate(failbit) is called.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   is_open checks if the stream has an associated file
           \fI(public member function)\fP 
   open    opens a file and associates it with the stream
           \fI(public member function)\fP 

.SH Category:

     * Todo no example
