.TH std::timespec 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::timespec \- std::timespec

.SH Synopsis
   Defined in header <ctime>
   struct timespec;           \fI(since C++17)\fP

   Structure holding an interval broken down into seconds and nanoseconds.

.SH Member objects

   std::time_t tv_sec whole seconds – >= 0
   long tv_nsec       nanoseconds – [0, 999999999]

.SH See also

   timespec_get returns the calendar time based on a given time base
   \fI(C++17)\fP      \fI(function)\fP
   tm           calendar time type
                \fI(class)\fP
   C documentation for
   timespec
