.TH std::experimental::erase(std::basic_string) 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::erase(std::basic_string) \- std::experimental::erase(std::basic_string)

.SH Synopsis
   Defined in header <experimental/string>
   template <class charT, class traits, class A, class U>      (library fundamentals TS
   void erase(std::basic_string<charT, traits, A>& c, const    v2)
   U& value);

   Erases all elements that compare equal to value from the container. Equivalent to
   c.erase(std::remove(c.begin(), c.end(), value), c.end());

.SH Parameters

   c     - container from which to erase
   value - value to be removed

.SH Complexity

   Linear.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   remove                       removes elements satisfying specific criteria
   remove_if                    \fI(function template)\fP 
   erase_if (std::basic_string) Erases all elements satisfying a predicate from a
   (library fundamentals 2 TS)  std::basic_string
                                \fI(function template)\fP 

.SH Category:

     * Todo no example
