.TH std::chrono::operator<<(std::chrono::hh_mm_ss) 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator<<(std::chrono::hh_mm_ss) \- std::chrono::operator<<(std::chrono::hh_mm_ss)

.SH Synopsis
   Defined in header <chrono>
   template< class CharT, class Traits, class Duration >

   std::basic_ostream<CharT, Traits>&                           \fI(since C++20)\fP
       operator<<( std::basic_ostream<CharT, Traits>& os,

                   const std::chrono::hh_mm_ss<Duration>& t );

   Outputs t into the stream os.

   Equivalent to return os << std::format(os.getloc(),
   STATICALLY_WIDEN<CharT>("{:L%T}"), hms); where STATICALLY_WIDEN<CharT>("{:L%T}") is
   "{:L%T}" if CharT is char, and L"{:L%T}" if CharT is wchar_t.

.SH Parameters

   os - the output stream
   t  - the time of day to be output

.SH Return value

   os

.SH Example

    This section is incomplete
    Reason: no example

   Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to        Behavior as published               Correct behavior
   P2372R3 C++20      the given locale was used by default L is needed to use the given
                                                           locale

.SH See also

   format                                stores formatted representation of the
   (C++20)                               arguments in a new string
                                         \fI(function template)\fP
   std::formatter<std::chrono::hh_mm_ss> formatting support for hh_mm_ss
   (C++20)                               \fI(class template specialization)\fP

.SH Category:
     * Todo no example
