.TH std::chrono::weekday_last::ok 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::weekday_last::ok \- std::chrono::weekday_last::ok

.SH Synopsis
   constexpr bool ok() const noexcept;  \fI(since C++20)\fP

   Checks if the weekday object stored in *this is valid.

.SH Return value

   weekday().ok()
