.TH std::basic_osyncstream<CharT,Traits,Allocator>::rdbuf 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_osyncstream<CharT,Traits,Allocator>::rdbuf \- std::basic_osyncstream<CharT,Traits,Allocator>::rdbuf

.SH Synopsis
   syncbuf_type* rdbuf() const noexcept;

   Returns a pointer to the underlying std::basic_syncbuf.

.SH Parameters

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   get_wrapped obtains a pointer to the final destination stream buffer
               \fI(public member function)\fP
