.TH std::map::clear 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::map::clear \- std::map::clear

.SH Synopsis
   void clear();

   Removes all elements from the container.

   Invalidates any references, pointers, or iterators referring to contained elements.
   May invalidate any past-the-end iterators.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Exceptions

   \fI(none)\fP                    \fI(until C++11)\fP
   noexcept specification:  
   noexcept                  \fI(since C++11)\fP
     

.SH Complexity

   Linear in the size of the container.

.SH See also

   erase erases elements
         \fI(public member function)\fP 
