.TH std::experimental::filesystem::directory_entry::operator==,!=,<,<=,>,>= 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Compares the path with the directory entry rhs.

.SH Parameters

    This section is incomplete

.SH Return value

    This section is incomplete

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH See also

    This section is incomplete

   bool operator==( const directory_entry& rhs ) const;  (filesystem TS)
   bool operator!=( const directory_entry& rhs ) const;  (filesystem TS)
   bool operator<( const directory_entry& rhs ) const;   (filesystem TS)
   bool operator<=( const directory_entry& rhs ) const;  (filesystem TS)
   bool operator>( const directory_entry& rhs ) const;   (filesystem TS)
   bool operator>=( const directory_entry& rhs ) const;  (filesystem TS)

.SH Category:

     * Todo without reason
