.TH std::signbit 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::signbit \- std::signbit

.SH Synopsis
   Defined in header <cmath>
   bool signbit( float arg );        \fI(since C++11)\fP
   bool signbit( double arg );       \fI(since C++11)\fP
   bool signbit( long double arg );  \fI(since C++11)\fP

   Determines if the given floating point number arg is negative.

.SH Parameters

   arg - floating point value

.SH Return value

   true if arg is negative, false otherwise

.SH See also

   abs(float) absolute value of a floating point value (|x|)
   fabs       \fI(function)\fP 
   copysign   copies the sign of a floating point value
   \fI(C++11)\fP    \fI(function)\fP 
