.TH std::unexpect_t,std::unexpect 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unexpect_t,std::unexpect \- std::unexpect_t,std::unexpect

.SH Synopsis
   Defined in header <expected>
   struct unexpect_t {

       explicit unexpect_t() = default;    \fB(1)\fP (since C++23)

   };
   inline constexpr unexpect_t unexpect{}; \fB(2)\fP (since C++23)

   1) A tag type for in-place construction of an unexpected value in an std::expected
   object.
   2) A constant of type const std::unexpect_t which is usually directly passed to a
   constructor of std::expected to construct an unexpected value.

.SH Notes

   Like other construction tag types, unexpect_t is a trivial, empty class with an
   explicit default constructor.

.SH See also

   constructor      constructs the expected object
                    \fI(public member function)\fP
   in_place
   in_place_type
   in_place_index   in-place construction tag
   in_place_t       (tag)
   in_place_type_t
   in_place_index_t
   \fI(C++17)\fP
