.TH std::error_code::operatorbool 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   explicit operator bool() const;  \fI(since C++11)\fP

   Checks if the error value is valid, i.e. non-zero.

.SH Parameters

   \fI(none)\fP

.SH Return value

   false if value() == 0, true otherwise.

.SH Exceptions

   noexcept specification:
   noexcept
.SH Category:

     * unconditionally noexcept
