.TH std::swap(std::tuple) 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::swap(std::tuple) \- std::swap(std::tuple)

.SH Synopsis
   template< class... Types >                                             \fI(since C++11)\fP
   void swap( tuple<Types...>& lhs, tuple<Types...>& rhs ) noexcept(/*    \fI(until C++20)\fP
   see below */);
   template< class... Types >

   constexpr void                                                         \fI(since C++20)\fP

   swap( tuple<Types...>& lhs, tuple<Types...>& rhs ) noexcept(/* see
   below */);

   Swaps the contents of lhs and rhs. Equivalent to lhs.swap(rhs).

   This function does not participate in overload resolution unless       \fI(since C++17)\fP
   std::is_swappable_v<Ti> is true for all i from 0 to sizeof...(Types).

.SH Parameters

   lhs, rhs - tuples whose contents to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept(noexcept(lhs.swap(rhs)))

.SH See also
