.TH std::error_category::~error_category 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_category::~error_category \- std::error_category::~error_category

.SH Synopsis
   virtual ~error_category();  \fI(since C++11)\fP

   Destroys the object.

.SH Parameters

   \fI(none)\fP
