.TH std::ranges::output_range 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::output_range \- std::ranges::output_range

.SH Synopsis
   Defined in header <ranges>
   template<class R, class T>

     concept output_range =                                               \fI(since C++20)\fP

       ranges::range<R> && std::output_iterator<ranges::iterator_t<R>,
   T>;

   The output_range concept is a refinement of range for which ranges::begin returns a
   model of output_iterator.
