.TH std::ratio_not_equal 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <ratio>
   template< class R1, class R2 >
   struct ratio_not_equal : std::integral_constant;

   If the ratios R1 and R2 are not equal, provides the member constant value equal
   true. Otherwise, value is false.

.SH Contents

     • 1 Inherited from
       std::integral_constant

          • 1.1 Member constants
          • 1.2 Member functions
          • 1.3 Member types
          • 1.4 Possible implementation
          • 1.5 Example

Inherited from std::integral_constant

.SH Member constants

   value    true if R1::num != R2::num || R1::den != R2::den , false otherwise
   \fB[static]\fP \fI(public static member constant)\fP

.SH Member functions

   operator bool converts the object to bool, returns value
                 \fI(public member function)\fP

.SH Member types

   Type       Definition
   value_type bool
   type       std::integral_constant<bool, value>

.SH Possible implementation

   template< class R1, class R2 >
   struct ratio_not_equal : std::integral_constant <
                                 bool,
                                 !std::ratio_equal<R1, R2>
                            > {};

.SH Example

   
// Run this code

 #include <iostream>
 #include <ratio>

 int main()
 {
     if(std::ratio_not_equal<std::ratio<2,3>, std::ratio<1,3>>::value) {
         std::cout << "2/3 != 1/3\\n";
     } else {
         std::cout << "2/3 == 1/3\\n";
     }
 }

.SH Output:

 2/3 != 1/3
