.TH std::basic_string_view::operator[] 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string_view::operator[] \- std::basic_string_view::operator[]

.SH Synopsis
   constexpr const_reference operator[](size_type pos) const;  \fI(since C++17)\fP

   Returns a const reference to the character at specified location pos.

   No bounds checking is performed: the behavior is undefined if pos >= size().

.SH Parameters

   pos - position of the character to return

.SH Return value

   Const reference to the requested character

.SH Exceptions

   Does not throw

.SH Complexity

   Constant.

.SH Notes

   Unlike std::basic_string::operator[], std::basic_string_view::operator[](size()) has
   undefined behavior instead of returning CharT().

.SH Example


// Run this code

 #include <iostream>
 #include <string_view>
 int main()
 {
     std::string str = "Exemplar";
     std::string_view v = str;
     std::cout << v[2] << '\\n';
 //  v[2] = 'y'; // Error: cannot modify through a string view
     str[2] = 'y';
     std::cout << v[2] << '\\n';
 }

.SH Output:

 e
 y

.SH See also

   at accesses the specified character with bounds checking
      \fI(public member function)\fP
