.TH std::list::pop_back 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::list::pop_back \- std::list::pop_back

.SH Synopsis
   void pop_back();

   Removes the last element of the container.

   References and iterators to the erased element are invalidated.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH See also

   pop_front removes the first element
             \fI(public member function)\fP 
   push_back adds elements to the end
             \fI(public member function)\fP 
