.TH std::priority_queue::push 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   void push( const T& value );  (since {std})
   void push( T&& value );       \fI(since C++11)\fP

   Pushes the given element value to the priority queue.

   1) Effectively calls c.push_back(value); std::push_heap(c.begin(), c.end(), comp);
   2) Effectively calls c.push_back(std::move(value)); std::push_heap(c.begin(),
   c.end(), comp);

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Complexity
     * 4 See also

.SH Parameters

   value - the value of the element to push

.SH Return value

   \fI(none)\fP

.SH Complexity

   Logarithmic number of comparisons plus the complexity of Container::push_back.

.SH See also

   emplace constructs element in-place and sorts the underlying container
   \fI(C++11)\fP \fI(public member function)\fP
   pop     removes the top element
           \fI(public member function)\fP
