.TH std::filesystem::recursive_directory_iterator::operator= 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::recursive_directory_iterator::operator= \- std::filesystem::recursive_directory_iterator::operator=

.SH Synopsis
   recursive_directory_iterator& operator=( const                         \fI(since C++17)\fP
   recursive_directory_iterator& other ) = default;
   recursive_directory_iterator& operator=(                               \fI(since C++17)\fP
   recursive_directory_iterator&& other ) = default;

   Assigns a recursive directory iterator.

.SH Parameters

   other - another directory iterator to assign

.SH Return value

   *this

.SH Exceptions

   May throw implementation-defined exceptions.

    This section is incomplete

.SH Category:
     * Todo without reason
