.TH std::list::push_back 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   void push_back( const T& value ); \fB(1)\fP
   void push_back( T&& value );      \fB(2)\fP \fI(since C++11)\fP

   Appends the given element value to the end of the container.

   1) The new element is initialized as a copy of value.
   2) value is moved into the new element.

   No iterators or references are invalidated.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Complexity
     * 4 Exceptions
     * 5 Example
     * 6 See also

.SH Parameters

   value             -            the value of the element to append
.SH Type requirements
   -
   T must meet the requirements of CopyInsertable in order to use overload \fB(1)\fP.
   -
   T must meet the requirements of MoveInsertable in order to use overload \fB(2)\fP.

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH Exceptions

   If an exception is thrown, this function has no effect \fI(strong exception guarantee)\fP.

.SH Example

   The following code uses push_back to add several integers to a std::list<int>:

   
// Run this code

 #include <list>
 #include <iostream>

 int main()
 {
     std::list<int> numbers;

     numbers.push_back(42);
     numbers.push_back(314159);

     for (int i : numbers) { // c++11 range-based for loop
         std::cout << i << '\\n';
     }

     return 0;
 }

.SH Output:

 42
 314159

.SH See also

   emplace_back constructs elements in-place at the end
   \fI(C++11)\fP      \fI(public member function)\fP
   push_front   inserts elements to the beginning
                \fI(public member function)\fP
   pop_back     removes the last element
                \fI(public member function)\fP
