.TH std::experimental::scope_exit::~scope_exit 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::scope_exit::~scope_exit \- std::experimental::scope_exit::~scope_exit

.SH Synopsis
   ~scope_exit() noexcept;  (library fundamentals TS v3)

   Calls the exit function if the scope_exit is active, then destroys the stored EF (if
   it is a function object) and any other non-static data members.

.SH See also

   release makes the scope_exit inactive
           \fI(public member function)\fP
