.TH std::ranges::chunk_view::outer-iterator::operator* 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::chunk_view::outer-iterator::operator* \- std::ranges::chunk_view::outer-iterator::operator*

.SH Synopsis
   constexpr value_type operator*() const;  (since C++23)

   Returns the current chunk in the chunk_view.

   Let parent_ be the underlying pointer, and value_type be a nested class that is the
   value type of the iterator.

   Equivalent to: return value_type(*parent_);.

   Before invocation of this operator the expression *this == std::default_sentinel
   must be false.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The current element (a chunk).

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
