.TH std::chrono::time_zone_link::name,std::chrono::time_zone_link::target 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::time_zone_link::name,std::chrono::time_zone_link::target \- std::chrono::time_zone_link::name,std::chrono::time_zone_link::target

.SH Synopsis
   std::string_view name() const noexcept;   \fB(1)\fP
   std::string_view target() const noexcept; \fB(2)\fP

   Accesses the name and target of this time_zone_link object.

.SH Return value

   1) The alternative name this time_zone_link object represents.
   2) The name of the std::chrono::time_zone for which this time_zone_link object
   provides an alternative name.
