.TH std::promise::swap 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::promise::swap \- std::promise::swap

.SH Synopsis
   void swap( promise& other ) noexcept;  \fI(since C++11)\fP

   Exchanges the shared states of two promise objects.

.SH Parameters

   other - the promise to swap with

.SH Return value

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   std::swap(std::promise) specializes the std::swap algorithm
   \fI(C++11)\fP                 \fI(function template)\fP 

.SH Category:

     * Todo no example
