.TH std::thread::id::id 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::thread::id::id \- std::thread::id::id

.SH Synopsis
   id() noexcept;  \fI(since C++11)\fP

   Default-constructs a new thread identifier. The identifier does not represent a
   thread.

.SH Parameters

   \fI(none)\fP
