.TH std::chrono::weekday_indexed 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::weekday_indexed \- std::chrono::weekday_indexed

.SH Synopsis
   Defined in header <chrono>
   class weekday_indexed;      \fI(since C++20)\fP

   The class weekday_indexed combines a weekday, representing a day of the week in the
   Gregorian calendar, with a small index n in the range [1, 5]. It represents the
   first, second, third, fourth, or fifth weekday of some month.

   weekday_indexed is a TriviallyCopyable StandardLayoutType.

.SH Member functions

   constructor   constructs a weekday_indexed
                 \fI(public member function)\fP 
   weekday       access the stored weekday
                 \fI(public member function)\fP 
   index         access the stored index
                 \fI(public member function)\fP 
   ok            checks if the weekday and index are both valid
                 \fI(public member function)\fP 

   Nonmember functions

   operator== compares two weekday_indexed objects
   operator!= \fI(function)\fP 
   operator<< outputs a weekday_indexed into a stream
              \fI(function template)\fP 
