.TH std::getchar 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cstdio>
   int getchar();

   Reads the next character from stdin.

   Equivalent to std::getc(stdin).

.SH Parameters

   \fI(none)\fP

.SH Return value

   The obtained character on success or EOF on failure.

   If the failure has been caused by end of file condition, additionally sets the eof
   indicator (see feof()) on stdin. If the failure has been caused by some other error,
   sets the error indicator (see ferror()) on stdin.

.SH See also

   fgetc gets a character from a file stream
   getc  \fI(function)\fP 
   C documentation for
   getchar
