.TH std::sinh 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   float       sinh( float arg );
   double      sinh( double arg );
   long double sinh( long double arg );
   double      sinh( Integral arg );     \fI(since C++11)\fP

   Computes hyperbolic sine of arg

.SH Parameters

   arg - value of a floating-point or Integral type

.SH Return value

   Hyperbolic sine of arg.

.SH See also

   cosh                computes hyperbolic cosine (ch(x))
                       \fI(function)\fP 
   tanh                hyperbolic tangent
                       \fI(function)\fP 
   asinh               area hyperbolic sine
   \fI(C++11)\fP             \fI(function)\fP 
   sinh(std::complex)  computes hyperbolic sine of a complex number (sh(z))
                       \fI(function template)\fP 
   sinh(std::valarray) applies the function std::sinh to each element of valarray
                       \fI(function template)\fP 
   C documentation for
   sinh
