.TH std::unordered_multimap::begin,std::unordered_multimap::cbegin 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_multimap::begin,std::unordered_multimap::cbegin \- std::unordered_multimap::begin,std::unordered_multimap::cbegin

.SH Synopsis
   iterator begin() noexcept;               \fI(since C++11)\fP
   const_iterator begin() const noexcept;   \fI(since C++11)\fP
   const_iterator cbegin() const noexcept;  \fI(since C++11)\fP

   Returns an iterator to the first element of the container.

   If the container is empty, the returned iterator will be equal to end().

   range-begin-end.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the first element

.SH Complexity

   Constant

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   end  returns an iterator to the end
   cend \fI(public member function)\fP 

.SH Category:

     * Todo no example
