.TH std::swap(std::pair) 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   template< class T1, class T2 >
   void swap( pair<T1,T2>& lhs, pair<T1,T2>& rhs );

   Swaps the contents of lhs and rhs. Equivalent to lhs.swap(rhs).

.SH Parameters

   lhs, rhs - pairs whose contents to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   \fI(none)\fP                                 \fI(until C++11)\fP
   noexcept specification:  \fI(since C++11)\fP (since C++11)
   noexcept(noexcept(x.swap(y)))

.SH See also
