.TH std::map::end,std::map::cend 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::map::end,std::map::cend \- std::map::end,std::map::cend

.SH Synopsis
   iterator end();
   const_iterator end() const;
   const_iterator cend() const;  \fI(since C++11)\fP

   Returns an iterator to the element following the last element of the container.

   This element acts as a placeholder; attempting to access it results in undefined
   behavior.

   range-begin-end.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the element following the last element.

.SH Exceptions

   \fI(none)\fP                  \fI(until C++11)\fP
   noexcept specification: \fI(since C++11)\fP
   noexcept

.SH Complexity

   Constant.

.SH See also

   begin  returns an iterator to the beginning
   cbegin \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept
