.TH std::experimental::promise(concurrencyTS) 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::promise(concurrencyTS) \- std::experimental::promise(concurrencyTS)

.SH Synopsis
   Defined in header <experimental/future>
   template< class R > class promise;       \fB(1)\fP (concurrency TS)
   template< class R > class promise<R&>;   \fB(2)\fP (concurrency TS)
   template<>          class promise<void>; \fB(3)\fP (concurrency TS)

   std::experimental::concurrency_v1::promise is a modified version of std::promise
   provided by the concurrency TS that works with std::experimental::future.

   The only change from std::promise is that the get_future() member function returns a
   std::experimental::future.
