.TH std::poisson_distribution::mean 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   double mean() const;  \fI(since C++11)\fP

   Returns the μ parameter the distribution was constructed with. The parameter defines
   mean number of occurrences of the event. The default value is 1.0.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Floating point value identifying the μ distribution parameter.

.SH See also

   param gets or sets the distribution parameter object
         \fI(public member function)\fP
