.TH std::vector::pop_back 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::vector::pop_back \- std::vector::pop_back

.SH Synopsis
   void pop_back();            \fI(until C++20)\fP
   constexpr void pop_back();  \fI(since C++20)\fP

   Removes the last element of the container.

   Calling pop_back on an empty container results in undefined behavior.

   Iterators and references to the last element, as well as the end() iterator, are
   invalidated.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH Exceptions

   Throws nothing.

.SH Example


// Run this code

 #include <vector>
 #include <iostream>

 template<typename T>
 void print(T const & xs)
 {
     std::cout << "[ ";
     for(auto const & x : xs) {
         std::cout << x << ' ';
     }
     std::cout << "]\\n";
 }

 int main()
 {
     std::vector<int> numbers;

     print(numbers);

     numbers.push_back(5);
     numbers.push_back(3);
     numbers.push_back(4);

     print(numbers);

     numbers.pop_back();

     print(numbers);
 }

.SH Output:

 [ ]
 [ 5 3 4 ]
 [ 5 3 ]

.SH See also

   push_back adds an element to the end
             \fI(public member function)\fP
