.TH std::basic_ios::~basic_ios 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_ios::~basic_ios \- std::basic_ios::~basic_ios

.SH Synopsis
   virtual ~basic_ios();

   Destroys the basic_ios object. No operations on rdbuf are performed, it is not
   destroyed.

.SH Notes

   This destructor is virtual because the base class destructor, ios_base::~ios_base is
   virtual.
