.TH std::match_results::operator= 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <regex>
   match_results& operator=( const match_results& other ); \fB(1)\fP \fI(since C++11)\fP
   match_results& operator=( match_results&& other );      \fB(2)\fP \fI(since C++11)\fP

   Assigns the contents.

   1) Copy assignment operator. Assigns the contents of other.
   2) Move assignment operator. Assigns the contents of other using move semantics.
   other is in valid, but unspecified state after the operation.

.SH Parameters

   other - another match results object

.SH Return value

   *this.

.SH Exceptions

   1) \fI(none)\fP
   2)
   noexcept specification:  
   noexcept
     
