.TH std::accumulate 3 "Nov 25 2015" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::accumulate \- std::accumulate

.SH Synopsis
   Defined in header <numeric>
   template< class InputIt, class T >                        \fB(1)\fP
   T accumulate( InputIt first, InputIt last, T init );
   template< class InputIt, class T, class BinaryOperation >

   T accumulate( InputIt first, InputIt last, T init,        \fB(2)\fP

                 BinaryOperation op );

   Computes the sum of the given value init and the elements in the range [first,
   last). The first version uses operator+ to sum up the elements, the second version
   uses the given binary function op.

   op must not have side effects.                                         \fI(until C++11)\fP
   op must not invalidate any iterators, including the end iterators, or  \fI(since C++11)\fP
   modify any elements of the range involved.

.SH Parameters

   first, last - the range of elements to sum
   init        - initial value of the sum
                 binary operation function object that will be applied.

                 The signature of the function should be equivalent to the following:

                  Ret fun(const Type1 &a, const Type2 &b);
   op          -
                 The signature does not need to have const &.
                 The type Type1 must be such that an object of type T can be implicitly
                 converted to Type1. The type Type2 must be such that an object of type
                 InputIt can be dereferenced and then implicitly converted to Type2.
                 The type Ret must be such that an object of type T can be assigned a
                 value of type Ret. 
.SH Type requirements
   -
   InputIt must meet the requirements of InputIterator.
   -
   T must meet the requirements of CopyAssignable and CopyConstructible.

.SH Return value

   1) The sum of the given value and elements in the given range.
   2) The result of left fold of the given range over op

.SH Notes

   Although std::accumulate performs left fold by default, right fold may be achieved
   by using reverse iterators, e.g. std::accumulate(v.rbegin(), v.rend(), init, binop)

.SH Possible implementation

.SH First version
   template<class InputIt, class T>
   T accumulate(InputIt first, InputIt last, T init)
   {
       for (; first != last; ++first) {
           init = init + *first;
       }
       return init;
   }
.SH Second version
   template<class InputIt, class T, class BinaryOperation>
   T accumulate(InputIt first, InputIt last, T init,
                BinaryOperation op)
   {
       for (; first != last; ++first) {
           init = op(init, *first);
       }
       return init;
   }

.SH Example

   
// Run this code

 #include <iostream>
 #include <vector>
 #include <numeric>
 #include <string>
 #include <functional>
  
 int main()
 {
     std::vector<int> v{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
  
     int sum = std::accumulate(v.begin(), v.end(), 0);
  
     int product = std::accumulate(v.begin(), v.end(), 1, std::multiplies<int>());
  
     std::string s = std::accumulate(v.begin()+1, v.end(), std::to_string(v[0]),
                          [](const std::string& a, int b) {
                                return a + '-' + std::to_string(b);
                          });
  
     std::cout << "sum: " << sum << '\\n'
               << "product: " << product << '\\n'
               << "dash-separated string: " << s << '\\n';
 }

.SH Output:

 sum: 55
 product: 3628800
 dash-separated string: 1-2-3-4-5-6-7-8-9-10

.SH See also

   adjacent_difference computes the differences between adjacent elements in a range
                       \fI(function template)\fP 
   inner_product       computes the inner product of two ranges of elements
                       \fI(function template)\fP 
   partial_sum         computes the partial sum of a range of elements
                       \fI(function template)\fP 
   reduce              similar to std::accumulate, except out of order
   (parallelism TS)    \fI(function template)\fP 
