.TH std::map::rend,std::map::crend 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::map::rend,std::map::crend \- std::map::rend,std::map::crend

.SH Synopsis
   reverse_iterator rend();                        \fI(until C++11)\fP
   reverse_iterator rend() noexcept;               \fI(since C++11)\fP
   const_reverse_iterator rend() const;            \fI(until C++11)\fP
   const_reverse_iterator rend() const noexcept;   \fI(since C++11)\fP
   const_reverse_iterator crend() const noexcept;  \fI(since C++11)\fP

   Returns a reverse iterator to the element following the last element of the reversed
   container. It corresponds to the element preceding the first element of the
   non-reversed container. This element acts as a placeholder, attempting to access it
   results in undefined behavior.

   range-rbegin-rend.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reverse iterator to the element following the last element.

.SH Complexity

   Constant.

.SH See also

   rbegin  returns a reverse iterator to the beginning
   crbegin \fI(public member function)\fP 
