.TH std::promise::operator= 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   promise& operator=( promise&& other );             \fB(1)\fP \fI(since C++11)\fP
   promise& operator=( const promise& rhs ) = delete; \fB(2)\fP \fI(since C++11)\fP

   Assigns the contents.

   1) Move assignment operator. First, abandons the shared state (as in ~promise()),
   then assigns the shared state of other as if by executing
   std::promise(std::move(other)).swap(*this).
   2) promise is not copy-assignable.

.SH Parameters

   other - another promise to acquire the state from

.SH Return value

   *this

.SH Exceptions

   1)
   noexcept specification:  
   noexcept
     
