.TH std::barrier::arrive 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::barrier::arrive \- std::barrier::arrive

.SH Synopsis
   [[nodiscard]] arrival_token arrive( std::ptrdiff_t n = 1 );  \fI(since C++20)\fP

   Constructs an arrival_token object associated with the phase synchronization point
   for the current phase. Then, decrements the expected count by n.

   This function executes atomically. The call to this function strongly happens-before
   the start of the phase completion step for the current phase.

   The behavior is undefined if n is less than or equal to 0 or greater than the
   expected count for the current barrier phase.

.SH Parameters

   n - the value by which the expected count is decreased

.SH Return value

   The constructed arrival_token object.

.SH Exceptions

   Throws std::system_error with an error code allowed for mutex types on error.

.SH Notes

   This function can cause the completion step for the current phase to start.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

        blocks at the phase synchronization point until its phase completion step is
   wait run
        \fI(public member function)\fP
