.TH std::basic_string::front 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string::front \- std::basic_string::front

.SH Synopsis
   CharT& front();             \fB(1)\fP (constexpr since C++20)
   const CharT& front() const; \fB(2)\fP (constexpr since C++20)

   Returns reference to the first character in the string. The behavior is undefined if
   empty() is true.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reference to the first character, equivalent to operator[]\fB(0)\fP.

.SH Complexity

   Constant.

.SH Notes

   In libstdc++, front() is not available in C++98 mode.

.SH Example


// Run this code

 #include <iostream>
 #include <string>

 int main()
 {
     std::string s("Exemplary");
     char& f1 = s.front();
     f1 = 'e';
     std::cout << s << '\\n'; // "exemplary"

     std::string const c("Exemplary");
     char const& f2 = c.front();
     std::cout << &f2 << '\\n'; // "Exemplary"
 }

.SH Output:

 exemplary
 Exemplary

   Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to              Behavior as published               Correct behavior
   LWG 534 C++98      std::basic_string did not have the member        added
                      function front()

.SH See also

   back  accesses the last character
   (DR*) \fI(public member function)\fP
   front accesses the first character
         \fI(public member function of std::basic_string_view<CharT,Traits>)\fP
