.TH std::unordered_multimap::max_size 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_multimap::max_size \- std::unordered_multimap::max_size

.SH Synopsis
   size_type max_size() const;  \fI(since C++11)\fP

   Returns the maximum number of elements the container is able to hold due to system
   or library implementation limitations, i.e. std::distance(begin(), end()) for the
   largest container.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Maximum number of elements.

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH Complexity

   Constant.

.SH Notes

   This value typically reflects the theoretical limit on the size of the container. At
   runtime, the size of the container may be limited to a value smaller than max_size()
   by the amount of RAM available.

.SH Example

   
// Run this code

 #include <iostream>
 #include <unordered_map>
  
 int main()
 {
     std::unordered_multimap<char,char> s;
     std::cout << "Maximum size of a 'unordered_multimap' is " << s.max_size() << "\\n";
 }

.SH Possible output:

 Maximum size of a 'unordered_multimap' is 18446744073709551615

.SH See also

   size returns the number of elements
        \fI(public member function)\fP 

.SH Category:

     * unconditionally noexcept
