.TH std::experimental::ostream_joiner::operator* 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ostream_joiner::operator* \- std::experimental::ostream_joiner::operator*

.SH Synopsis
   ostream_joiner& operator*() noexcept;  (library fundamentals TS v2)

   Does nothing, this member function is provided to satisfy the requirements of
   LegacyOutputIterator.

   It returns the iterator itself, which makes it possible to use code such as *iter =
   value to output (insert) the value into the underlying stream.

.SH Parameters

   \fI(none)\fP

.SH Return value

   *this
