.TH std::make_tuple 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <tuple>
   template< class... Types >                                 \fI(since C++11)\fP
   tuple<VTypes...> make_tuple( Types&&... args );            \fI(until C++14)\fP
   template< class... Types >                                 \fI(since C++14)\fP
   constexpr tuple<VTypes...> make_tuple( Types&&... args );

   Creates a tuple object, deducing the target type from the types of arguments.

   For each Ti in Types..., the corresponding type Vi in Vtypes... is
   std::decay<Ti>::type unless application of std::decay results in
   std::reference_wrapper<X> for some type X, in which case the deduced type is X&.

.SH Contents

     • 1 Parameters
     • 2 Return value
     • 3 Possible implementation
     • 4 Example

.SH Parameters

   args - zero or more arguments to construct the tuple from

.SH Return value

   A std::tuple object containing the given values, created as if by
   std::tuple<VTypes...>(std::forward<Types>(t)...).

.SH Possible implementation

   template <class T>
   struct special_decay
   {
       using type = typename std::decay<T>::type;
   };

   template <class T>
   struct special_decay<std::reference_wrapper<T>>
   {
       using type = T&;
   };

   template <class T>
   using special_decay_t = typename special_decay<T>::type;

   template <class... Types>
   auto make_tuple(Types&&... args)
   {
       return std::tuple<special_decay_t<Types>...>(std::forward<Types>(args)...);
   }

.SH Example

   
// Run this code

 #include <iostream>
 #include <tuple>
 #include <functional>

 int main()
 {
     auto t1 = std::make_tuple(10, "Test", 3.14);
     std::cout << "The value of t1 is "
               << "(" << std::get<0>(t1) << ", " << std::get<1>(t1)
               << ", " << std::get<2>(t1) << ")\\n";

     int n = 1;
     auto t2 = std::make_tuple(std::ref(n), n);
     n = 7;
     std::cout << "The value of t2 is "
               << "(" << std::get<0>(t2) << ", " << std::get<1>(t2) << ")\\n";
 }

.SH Output:

 The value of t1 is (10, Test, 3.14)
 The value of t2 is (7, 1)

                    creates a tuple of lvalue references or unpacks a tuple into
   tie              individual objects
                    \fI(function template)\fP
   forward_as_tuple creates a tuple of rvalue references
                    \fI(function template)\fP
   tuple_cat        creates a tuple by concatenating any number of tuples
                    \fI(function template)\fP
