.TH std::function::swap 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   void swap( function& other );  \fI(since C++11)\fP

   Exchanges the stored callable objects of *this and other.

.SH Parameters

   other - function wrapper to exchange the stored callable object with

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:  
   noexcept
     
