.TH std::experimental::ranges::IndirectPredicate 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::IndirectPredicate \- std::experimental::ranges::IndirectPredicate

.SH Synopsis
   Defined in header <experimental/ranges/iterator>
   template <class F, class I>

   concept bool IndirectPredicate() {
   return ranges::Readable<I>()
   && ranges::Predicate<F, ranges::value_type_t<I>>()
   && ranges::Predicate<F, ranges::reference_t<I>>()
   && ranges::Predicate<F, ranges::iter_common_reference_t<I>>();
   }
   template <class F, class I1, class I2>
   concept bool IndirectPredicate() {
   return ranges::Readable<I1>() && ranges::Readable<I2>()
   && ranges::Predicate<F, ranges::value_type_t<I1>,                        (ranges TS)
   ranges::value_type_t<I2>>()
   && ranges::Predicate<F, ranges::value_type_t<I1>,
   ranges::reference_t<I2>>()
   && ranges::Predicate<F, ranges::reference_t<I1>,
   ranges::value_type_t<I2>>()
   && ranges::Predicate<F, ranges::reference_t<I1>,
   ranges::reference_t<I2>>()
   && ranges::Predicate<F, ranges::iter_common_reference_t<I1>,
   ranges::iter_common_reference_t<I2>>();

   }

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
