.TH std::expected::operatorbool,std::expected::has_value 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::expected::operatorbool,std::expected::has_value \- std::expected::operatorbool,std::expected::has_value

.SH Synopsis
   constexpr explicit operator bool() const noexcept;  (since C++23)
   constexpr bool has_value() const noexcept;          (since C++23)

   Checks whether *this contains an expected value.

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if *this contains an expected value, false if *this contains an unexpected
   value.

.SH Notes

   A std::expected object is never empty. If has_value() returns true, operator* can be
   used to access the contained value; otherwise, error() can be used.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator-> accesses the expected value
   operator*  \fI(public member function)\fP
   error      returns the unexpected value
              \fI(public member function)\fP

.SH Category:
     * Todo no example
