.TH std::experimental::erase_if(std::unordered_map) 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <experimental/unordered_map>
   template <class K, class T, class H, class P, class A,
   class Predicate>                                            (library fundamentals TS
   void erase_if(std::unordered_map<K, T, H, P, A>& c,         v2)
   Predicate pred);

   Erases all elements that satisfy the predicate pred from the container. Equivalent
   to

 for (auto i = c.begin(), last = c.end(); i != last; ) {
   if (pred(*i)) {
     i = c.erase(i);
   } else {
     ++i;
   }
 }

.SH Parameters

   c    - container from which to erase
   pred - predicate that determines which elements should be erased

.SH Complexity

   Linear.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   remove    removes elements satisfying specific criteria
   remove_if \fI(function template)\fP

.SH Category:

     * Todo no example
