.TH std::swap(std::basic_ifstream) 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   template< class T >
   void swap( basic_ifstream<T> &lhs, basic_ifstream<T> &rhs );

   Specializes the std::swap algorithm for std::basic_ifstream. Exchanges the state of
   lhs with that of rhs. Effectively calls lhs.swap(rhs).

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Exceptions
     * 4 Example
     * 5 See also

.SH Parameters

   lhs, rhs - streams whose state to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   swap    swaps two file streams
   \fI(C++11)\fP \fI(public member function)\fP

.SH Category:

     * Todo no example
