.TH std::experimental::basic_string_view::remove_suffix 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::basic_string_view::remove_suffix \- std::experimental::basic_string_view::remove_suffix

.SH Synopsis
   constexpr void remove_suffix(size_type n);  (library fundamentals TS)

   Moves the end of the view back by n characters.

   The behavior is undefined if n > size().

.SH Parameters

   n - number of characters to remove from the end of the view

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH Example

   
// Run this code

 #include <iostream>
 #include <experimental/string_view>
 int main()
 {
     char arr[] = {'a', 'b', 'c', '\\0', '\\0', '\\0'};
     std::experimental::string_view v(arr, sizeof arr);
     v.remove_suffix(v.find('\\0'));
     std::cout << "Array: '" << arr << "', size=" << sizeof arr << '\\n'
               << "View : '" << v << "', size=" << v.size() << '\\n';
 }

.SH Output:

 Array: 'abc', size=6
 View : 'abc', size=3

.SH See also

   remove_prefix Shrinks the view by moving its start forward
                 \fI(public member function)\fP 
