.TH std::istream_iterator::operator*,operator-> 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::istream_iterator::operator*,operator-> \- std::istream_iterator::operator*,operator->

.SH Synopsis
   const T& operator*() const;  \fB(1)\fP
   const T* operator->() const; \fB(2)\fP

   Returns a pointer or a reference to the current element.

   The behavior is undefined if the iterator is end-of-stream iterator.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A pointer or a reference to the current element.

.SH Exceptions

   May throw implementation-defined exceptions.
