.TH std::sub_match::sub_match 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   constexpr sub_match();

   Default constructs a std::sub_match. The matched member is set to false and the
   value of other members is undefined.

   This is the only publicly accessible and defined constructor.

.SH Parameters

   \fI(none)\fP
