.TH std::experimental::overaligned_tag,std::experimental::overaligned 3 "2022.07.31" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::overaligned_tag,std::experimental::overaligned \- std::experimental::overaligned_tag,std::experimental::overaligned

.SH Synopsis
   Defined in header <experimental/simd>
   template < std::size_t N >

   struct overaligned_tag {};
                                                       (parallelism TS v2)
   template < std::size_t N >

   inline constexpr overaligned_tag<N> overaligned{};

   This tag type indicates that the buffer of copy_from and copy_to is aligned to N.

.SH Template parameters

   N - the alignment in bytes the memory access may assume.

.SH See also

   vector_aligned_tag  tag type that indicates the alignment of the vector type
   vector_aligned      \fI(class)\fP
   (parallelism TS v2)
   element_aligned_tag tag type that indicates the alignment of the elements
   element_aligned     \fI(class)\fP
   (parallelism TS v2)
