.TH std::make_error_condition(std::errc) 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::make_error_condition(std::errc) \- std::make_error_condition(std::errc)

.SH Synopsis
   Defined in header <system_error>
   std::error_condition make_error_condition( std::errc e );  \fI(since C++11)\fP

   Creates an error condition for an errc value e. Sets the error code to int(e) and
   error category to std::generic_category.

.SH Parameters

   e - standard error code

.SH Return value

   Error condition for e.

.SH Exceptions

   noexcept specification:  
   noexcept
     
