.TH std::array::end,std::array::cend 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::array::end,std::array::cend \- std::array::end,std::array::cend

.SH Synopsis
   iterator end();                         \fI(until C++17)\fP
   constexpr iterator end();               \fI(since C++17)\fP
   const_iterator end() const;             \fI(until C++17)\fP
   constexpr const_iterator end() const;   \fI(since C++17)\fP
   const_iterator cend() const;            \fI(until C++17)\fP
   constexpr const_iterator cend() const;  \fI(since C++17)\fP

   Returns an iterator to the element following the last element of the container.

   This element acts as a placeholder; attempting to access it results in undefined
   behavior.

   range-begin-end.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the element following the last element.

.SH Exceptions

   noexcept specification:
   noexcept

.SH Complexity

   Constant.

.SH See also

   begin  returns an iterator to the beginning
   cbegin \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept
