.TH std::fwide 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cwchar>
   int fwide( FILE *stream, int mode );

   If mode > 0, attempts to make stream wide-oriented. If mode < 0, attempts to make
   stream byte-oriented. If mode==0, only queries the current orientation of the
   stream.

.SH Parameters

   stream - pointer to the C I/O stream to modify or query
   mode   - integer value greater than zero to set the stream wide, less than zero to
            set the stream narrow, or zero to query only

.SH Return value

   An integer greater than zero if the stream is wide-oriented after this call, less
   than zero if the stream is byte-oriented after this call, and zero if the stream has
   no orientation.

.SH See also

   fopen  opens a file
          \fI(function)\fP
   C documentation for
   fwide
