.TH std::atomic_ref::operatorT 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::atomic_ref::operatorT \- std::atomic_ref::operatorT

.SH Synopsis
   operator T() const noexcept;  \fI(since C++20)\fP

   Atomically loads and returns the current value of the referenced object. Equivalent
   to load().

.SH Parameters

   \fI(none)\fP

.SH Return value

   The current value of the referenced object.

.SH See also

   load atomically obtains the value of the referenced object
        \fI(public member function)\fP
