.TH std::rend,std::crend 3 "Nov 25 2015" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::rend,std::crend \- std::rend,std::crend

.SH Synopsis
   Defined in header <iterator>
   template< class C >                                 \fB(1)\fP \fI(since C++14)\fP
   auto rend( C& c ) -> decltype(c.rend());
   template< class C >                                 \fB(1)\fP \fI(since C++14)\fP
   auto rend( const C& c ) -> decltype(c.rend());
   template< class T, size_t N >                       \fB(2)\fP \fI(since C++14)\fP
   reverse_iterator<T*> rend( T (&array)[N] );
   template< class C >                                 \fB(3)\fP \fI(since C++14)\fP
   auto crend( const C& c ) -> decltype(std::rend(c));

   Returns an iterator to the reverse-end of the given container c or array array.

   1) Returns a possibly const-qualified iterator to the reverse-end of the container
   c.
   2) Returns std::reverse_iterator<T*> to the reverse-end of the array array.
   3) Returns a const-qualified iterator to the reverse-end of the container c.

   range-rbegin-rend.svg

.SH Parameters

   c     - a container with a rend method
   array - an array of arbitrary type

.SH Return value

   An iterator to the reverse-end of c or array

.SH Notes

   In addition to being included in <iterator>, std::rend is guaranteed to become
   available if any of the following headers are included: <array>, <deque>,
   <forward_list>, <list>, <map>, <regex>, <set>, <string>, <unordered_map>,
   <unordered_set>, and <vector>.

.SH Specializations

   Custom specializations of std::rend may be provided for classes that do not expose a
   suitable rend() member function, yet can be iterated. The following specializations
   are already provided by the standard library:

   rend(std::initializer_list) specializes std::rend
   \fI(C++14)\fP                     \fI(function)\fP 

.SH Example

   
// Run this code

 #include <iostream>
 #include <vector>
 #include <iterator>
 #include <algorithm>
  
 int main()
 {
     int a[] = {4, 6, -3, 9, 10};
     std::cout << "Array backwards: ";
     std::copy(std::rbegin(a), std::rend(a), std::ostream_iterator<int>(std::cout, " "));
  
     std::cout << "\\nVector backwards: ";
     std::vector<int> v = {4, 6, -3, 9, 10};
     std::copy(std::rbegin(v), std::rend(v), std::ostream_iterator<int>(std::cout, " "));
 }

.SH Output:

 Array backwards: 10 9 -3 6 4
 Vector backwards: 10 9 -3 6 4

.SH See also

   end
   cend    returns an iterator to the end of a container or array
   \fI(C++11)\fP \fI(function)\fP 
   \fI(C++14)\fP
   rbegin  returns a reverse iterator to a container or array
   crbegin \fI(function)\fP 
   \fI(C++14)\fP
   begin
   cbegin  returns an iterator to the beginning of a container or array
   \fI(C++11)\fP \fI(function)\fP 
   \fI(C++14)\fP
