.TH std::experimental::nonesuch 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <experimental/type_traits>
   struct nonesuch {

   nonesuch() = delete;
   ~nonesuch() = delete;                         (library fundamentals TS v2)
   nonesuch(nonesuch const&) = delete;
   void operator=(nonesuch const&) = delete;

   };

   std::experimental::nonesuch is a class type used by std::experimental::detected_t to
   indicate detection failure.

.SH Notes

   nonesuch is not constructible, destructible, or copyable.
