.TH std::swap_ranges 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <algorithm>
   template< class ForwardIt1, class ForwardIt2 >
   ForwardIt2 swap_ranges( ForwardIt1 first1, ForwardIt1 last1, ForwardIt2 first2 )

   Exchanges elements between range [first1, last1) and another range starting at
   first2.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Possible implementation
     * 4 Example
     * 5 Complexity
     * 6 See also

.SH Parameters

   first1, last1       -       the first range of elements to swap
   first2              -       beginning of the second range of elements to swap
.SH Type requirements
   -
   ForwardIt1, ForwardIt2 must meet the requirements of ForwardIterator.
   -
   The types of dereferenced ForwardIt1 and ForwardIt2 must meet the requirements of
   Swappable

.SH Return value

   Iterator to the element past the last element exchanged in the range beginning with
   first2.

.SH Possible implementation

   template<class ForwardIt1, class ForwardIt2>
   ForwardIt2 swap_ranges(ForwardIt1 first1,
                                ForwardIt1 last1,
                                ForwardIt2 first2)
   {
       while (first1 != last1) {
           std::iter_swap(first1++, first2++);
       }
       return first2;
   }

.SH Example

   Demonstrates swapping of subranges from different containers

   
// Run this code

 #include <algorithm>
 #include <list>
 #include <vector>
 #include <iostream>
 int main()
 {
     std::vector<int> v = {1, 2, 3, 4, 5};
     std::list<int> l = {-1, -2, -3, -4, -5};

     std::swap_ranges(v.begin(), v.begin()+3, l.begin());

     for(int n : v)
        std::cout << n << ' ';
     std::cout << '\\n';
     for(int n : l)
        std::cout << n << ' ';
     std::cout << '\\n';
 }

.SH Output:

 -1 -2 -3 4 5
 1 2 3 -4 -5

.SH Complexity

   linear in the distance between first and last

.SH See also

   iter_swap swaps the elements pointed to by two iterators
             \fI(function template)\fP
   swap      swaps the values of two objects
             \fI(function template)\fP
