.TH std::unordered_set::max_load_factor 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   float max_load_factor() const;    \fB(1)\fP \fI(since C++11)\fP
   void max_load_factor( float ml ); \fB(2)\fP \fI(since C++11)\fP

   Manages the maximum load factor (number of elements per bucket). The container
   automatically increases the number of buckets if the load factor exceeds this
   threshold.

   1) Returns current maximum load factor.

   2) Sets the maximum load factor to ml.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Complexity
     * 4 See also

.SH Parameters

   ml - new maximum load factor setting

.SH Return value

   1) current maximum load factor.

   2) none.

.SH Complexity

   Constant

.SH See also

   load_factor returns average number of elements per bucket
               \fI(public member function)\fP
