.TH std::floating_point 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::floating_point \- std::floating_point

.SH Synopsis
   Defined in header <concepts>
   template < class T >                                   \fI(since C++20)\fP
   concept floating_point = std::is_floating_point_v<T>;

   The concept floating_point<T> is satisfied if and only if T is a floating-point
   type.

.SH See also

   is_floating_point checks if a type is a floating-point type
   \fI(C++11)\fP           \fI(class template)\fP
