.TH std::basic_ifstream::native_handle 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_ifstream::native_handle \- std::basic_ifstream::native_handle

.SH Synopsis
   native_handle_type native_handle() const noexcept;  (since C++26)

   Returns the implementation defined underlying handle associated with basic_filebuf.
   The behavior is undefined if is_open() is false.

.SH Return value

   rdbuf()->native_handle()

.SH Notes

         Feature-test macro         Value    Std          Feature
   __cpp_lib_fstream_native_handle 202306L (C++26) native handles support

.SH Example

    This section is incomplete
    Reason: example

.SH Category:
     * Todo with reason
