.TH std::experimental::ranges::UniformRandomNumberGenerator 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::UniformRandomNumberGenerator \- std::experimental::ranges::UniformRandomNumberGenerator

.SH Synopsis
   Defined in header <experimental/ranges/random>
   template <class G>

   concept bool UniformRandomNumberGenerator() {
       return requires(G g) {
                  { g() } -> ranges::UnsignedIntegral; /* not required to
   be equality preserving */                                                (ranges TS)
                  { G::min() } -> ranges::Same<std::result_of_t<G&()>>;
                  { G::max() } -> ranges::Same<std::result_of_t<G&()>>;
       };

   }

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
