.TH std::experimental::optional::value 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::optional::value \- std::experimental::optional::value

.SH Synopsis
   constexpr const T& value() const;  (library fundamentals TS)
   T& value();                        (library fundamentals TS)

   Returns the contained value.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A reference to the contained value.

.SH Exceptions

   std::bad_optional_access if *this is in disengaged state.

.SH See also

   value_or returns the contained value if engaged, another value otherwise
            \fI(public member function)\fP 
