.TH std::regex_iterator::operator*,operator-> 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   const value_type& operator*() const;  \fB(1)\fP \fI(since C++11)\fP
   const value_type* operator->() const; \fB(2)\fP \fI(since C++11)\fP

   Extracts the current std::regex_match from a regex_iterator:

   1) Returns a reference to the current std::regex_match.
   2) Returns a pointer to the current std::regex_match.

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:

     * Todo no example
