.TH std::priority_queue::empty 3 "2022.07.31" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::priority_queue::empty \- std::priority_queue::empty

.SH Synopsis
   bool empty() const;                \fI(until C++20)\fP
   [[nodiscard]] bool empty() const;  \fI(since C++20)\fP

   Checks if the underlying container has no elements, i.e. whether c.empty().

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if the underlying container is empty, false otherwise

.SH Complexity

   Constant

.SH Example


// Run this code

 #include <algorithm>
 #include <iostream>
 #include <queue>

 int main()
 {
     std::cout << std::boolalpha;

     std::priority_queue<int> container;

     std::cout << "Initially, container.empty(): " << container.empty() << '\\n';

     container.push(42);
     std::cout << "After adding elements, container.empty(): " << container.empty() << '\\n';
 }

.SH Output:

 Initially, container.empty(): true
 After adding elements, container.empty(): false

.SH See also

   size returns the number of elements
        \fI(public member function)\fP
