.TH std::is_signed 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::is_signed \- std::is_signed

.SH Synopsis
   Defined in header <type_traits>
   template< class T >              \fI(since C++11)\fP
   struct is_signed;

   If T is an arithmetic type, provides the member constant value equal true if T(-1) <
   T\fB(0)\fP: this results in true for the floating-point types and the signed integer
   types, and in false for the unsigned integer types and the type bool.

   For any other type, value is false.

.SH Template parameters

   T - a type to check

  Helper variable template

   template< class T >                                \fI(since C++17)\fP
   constexpr bool is_signed_v = is_signed<T>::value;

Inherited from std::integral_constant

.SH Member constants

   value    true if T is a signed arithmetic type , false otherwise
   \fB[static]\fP \fI(public static member constant)\fP

.SH Member functions

   operator bool converts the object to bool, returns value
                 \fI(public member function)\fP
   operator()    returns value
   \fI(C++14)\fP       \fI(public member function)\fP

.SH Member types

   Type       Definition
   value_type bool
   type       std::integral_constant<bool, value>

.SH Possible implementation

   namespace detail {
   template<typename T,bool = std::is_arithmetic<T>::value>
   struct is_signed : std::integral_constant<bool, T(-1) < T\fB(0)\fP> {};

   template<typename T>
   struct is_signed<T,false> : std::false_type {};
   } // namespace detail

   template<typename T>
   struct is_signed : detail::is_signed<T>::type {};

.SH Example

   
// Run this code

 #include <iostream>
 #include <type_traits>

 class A {};
 enum B : int {};
 enum class C : int {};

 int main()
 {
     std::cout << std::boolalpha;
     std::cout << std::is_signed<A>::value << '\\n';
     std::cout << std::is_signed<float>::value << '\\n';
     std::cout << std::is_signed<signed int>::value << '\\n';
     std::cout << std::is_signed<unsigned int>::value << '\\n';
     std::cout << std::is_signed<B>::value << '\\n';
     std::cout << std::is_signed<C>::value << '\\n';

     // shorter:
     std::cout << std::is_signed<signed int>() << '\\n';
     std::cout << std::is_signed<unsigned int>() << '\\n';
 }

.SH Output:

 false
 true
 true
 false
 false
 false
 true
 false

.SH See also

   is_unsigned                    checks if a type is unsigned arithmetic type
   \fI(C++11)\fP                        \fI(class template)\fP
   is_signed                      identifies signed types
   \fB[static]\fP                       \fI\fI(public static member\fP constant of\fP
                                  std::numeric_limits)
   is_arithmetic                  checks if a type is arithmetic type
   \fI(C++11)\fP                        \fI(class template)\fP
   make_signed                    makes the given integral type signed
   \fI(C++11)\fP                        \fI(class template)\fP
   make_unsigned                  makes the given integral type unsigned
   \fI(C++11)\fP                        \fI(class template)\fP
   std::experimental::is_signed_v variable template alias of std::is_signed::value
   (library fundamentals TS)      (variable template)
