.TH std::future_error::future_error 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::future_error::future_error \- std::future_error::future_error

.SH Synopsis
   future_error( const future_error& other ) noexcept; \fB(1)\fP \fI(since C++11)\fP
   explicit future_error( std::future_errc ec );       \fB(2)\fP \fI(since C++17)\fP

   1) Copy constructor. Initializes the contents of the new future_error object with
   those of other. If *this and other both have dynamic type std::future_error then
   std::strcmp(what(), other.what()) == 0.
   2) Constructs a new future_error object containing the error code
   std::make_error_code(ec).

.SH Parameters

   other - another future_error object to copy
   ec    - error code

.SH Notes

   There is no standard-compliant way for the user to construct a future_error other
   than copying from another future_error prior to C++17. C++11 and C++14 depict an
   exposition-only public constructor taking a std::error_code, and some
   implementations provide such a constructor.
