.TH std::basic_string::push_back 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string::push_back \- std::basic_string::push_back

.SH Synopsis
   void push_back( CharT ch );

   Appends the given character ch to the end of the string.

.SH Parameters

   ch - the character to append

.SH Return value

   \fI(none)\fP

.SH Complexity

   Amortized constant.

.SH Exceptions

   If an exception is thrown for any reason, this function has no effect (strong
   exception guarantee).
   \fI(since C++11)\fP

   If the operation would result in size() > max_size(), throws std::length_error.

.SH See also

   pop_back removes the last character
   \fI(C++11)\fP  \fI(public member function)\fP 
