.TH std::chrono::month::operator+=,std::chrono::month::operator-= 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month::operator+=,std::chrono::month::operator-= \- std::chrono::month::operator+=,std::chrono::month::operator-=

.SH Synopsis
   constexpr std::chrono::month& operator+=(const                     \fB(1)\fP \fI(since C++20)\fP
   std::chrono::months& m) noexcept;
   constexpr std::chrono::month& operator+=(const                     \fB(2)\fP \fI(since C++20)\fP
   std::chrono::months& m) noexcept;

   Adds or subtracts m.count() from the month value, reducing the result modulo 12 to
   an integer in the range [1, 12].

   1) Performs *this = *this + m;
   2) Performs *this = *this - m;

.SH Return value

   A reference to this month after modification.

.SH Notes

   After a call to one of these functions, ok() is always true if no overflow occurred
   during the operation.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator++
   operator++(int) increments or decrements the month
   operator--      \fI(public member function)\fP 
   operator--(int)
   operator+       performs arithmetic on months
   operator-       \fI(function)\fP 

.SH Category:

     * Todo no example
