.TH std::invalid_argument 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <stdexcept>
   class invalid_argument;

   Defines a type of object to be thrown as exception. It reports errors that arise
   because an argument value has not been accepted.

   std-invalid argument-inheritance.svg
   About this image

                                   Inheritance diagram

.SH Contents

     • 1 Member functions
     • 2
       std::invalid_argument::invalid_argument

          • 2.1 Parameters
          • 2.2 Exceptions
          • 2.3 Inherited from
            std::exception

               • 2.3.1 Member functions

.SH Member functions

   constructor   constructs the exception object
                 \fI(public member function)\fP

                         std::invalid_argument::invalid_argument

   explicit invalid_argument( const std::string& what_arg ); \fB(1)\fP
   explicit invalid_argument( const char* what_arg );        \fB(2)\fP \fI(since C++11)\fP

   Constructs the exception object with what_arg as explanatory string that can be
   accessed through what().

.SH Parameters

   what_arg - explanatory string

.SH Exceptions

   \fI(none)\fP

Inherited from std::exception

.SH Member functions

   destructor   destructs the exception object
   \fB[virtual]\fP    \fI(virtual public member function of std::exception)\fP
   what         returns an explanatory string
   \fB[virtual]\fP    \fI(virtual public member function of std::exception)\fP
