.TH std::atomic_flag::operator= 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <atomic>
   atomic_flag& operator=( const atomic_flag& ) = delete;          \fB(1)\fP \fI(since C++11)\fP
   atomic_flag& operator=( const atomic_flag& ) volatile = delete; \fB(2)\fP \fI(since C++11)\fP

   std::atomic_flag is not assignable, its assignment operators are deleted.
