.TH std::multimap::max_size 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   size_type max_size() const;

   Returns the maximum number of elements the container is able to hold due to system
   or library implementation limitations, i.e. std::distance(begin(), end()) for the
   largest container.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Maximum number of elements.

.SH Exceptions

   \fI(none)\fP                    \fI(until C++11)\fP
   noexcept specification:  
   noexcept                  \fI(since C++11)\fP
     

.SH Complexity

   Constant.

.SH Notes

   This value is typically equal to std::numeric_limits<size_type>::max(), and reflects
   the theoretical limit on the size of the container. At runtime, the size of the
   container may be limited to a value smaller than max_size() by the amount of RAM
   available.

.SH See also

   size returns the number of elements
        \fI(public member function)\fP 
