.TH std::regex_token_iterator::operator*,operator-> 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::regex_token_iterator::operator*,operator-> \- std::regex_token_iterator::operator*,operator->

.SH Synopsis
   const value_type& operator*() const;  \fB(1)\fP \fI(since C++11)\fP
   const value_type* operator->() const; \fB(2)\fP \fI(since C++11)\fP

   Returns a pointer or reference to the current match.

.SH Return value

   1) Returns a reference to the current match.
   2) Returns a pointer to the current match.

   The behavior is undefined if the iterator is end-of-sequence iterator.
