.TH std::sig_atomic_t 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::sig_atomic_t \- std::sig_atomic_t

.SH Synopsis
   Defined in header <csignal>
   typedef /* unspecified */ sig_atomic_t;

   An integer type which can be accessed as an atomic entity even in the presence of
   asynchronous interrupts made by signals.

.SH Notes

   Until C++11, which introduced std::atomic and std::atomic_signal_fence, about the
   only thing a strictly conforming program could do in a signal handler was to assign
   a value to a volatile static std::sig_atomic_t variable and promptly return.

.SH See also

   signal              sets a signal handler for particular signal
                       \fI(function)\fP 
   C documentation for
   sig_atomic_t
   atomic_signal_fence fence between a thread and a signal handler executed in the same
   \fI(C++11)\fP             thread
                       \fI(function)\fP 
