.TH std::unordered_multimap::end,std::unordered_multimap::cend 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_multimap::end,std::unordered_multimap::cend \- std::unordered_multimap::end,std::unordered_multimap::cend

.SH Synopsis
   iterator end();               \fI(since C++11)\fP
   const_iterator end() const;   \fI(since C++11)\fP
   const_iterator cend() const;  \fI(since C++11)\fP

   Returns an iterator to the element following the last element of the container.

   This element acts as a placeholder; attempting to access it results in undefined
   behavior.

   range-begin-end.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the element following the last element.

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH Complexity

   Constant.

.SH See also

   begin  returns an iterator to the beginning
   cbegin \fI(public member function)\fP 

.SH Category:

     * unconditionally noexcept
