.TH std::partial_order 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::partial_order \- std::partial_order

.SH Synopsis
   Defined in header <compare>
   template< class T >
   constexpr std::partial_ordering partial_order(const T& a, const T&     \fI(since C++20)\fP
   b);

   Compares two values using 3-way comparison and produces a result of type
   std::partial_ordering

   Specifically,

     * If the expression a <=> b is well-formed and its result is convertible to
       std::partial_ordering, returns that result.
     * Otherwise, if the expression a <=> b is well-formed, but its result is not
       convertible to std::partial_ordering, then the function is defined as deleted.
     * Otherwise, if the expression a <=> b is ill-formed, but the expressions a == b
       and a < b are both well-formed and convertible to bool,

     * if a == b is true, returns std::partial_ordering::equivalent
     * otherwise, if a < b is true, returns std::partial_ordering::less
     * otherwise, returns std::partial_ordering::greater

     * Otherwise, the function is defined as deleted.

.SH Parameters

   a, b - values to compare

.SH Return value

   A value of type std::partial_ordering, as described above.

.SH Notes

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   partial_ordering the result type of 3-way comparison that supports all 6 operators,
   (C++20)          is not substitutable, and allows incomparable values
                    \fI(class)\fP 
   strong_order     performs 3-way comparison and produces a result of type
   (C++20)          std::strong_ordering
                    \fI(function template)\fP 
   weak_order       performs 3-way comparison and produces a result of type
   (C++20)          std::weak_ordering
                    \fI(function template)\fP 
   weak_equal       performs 3-way comparison and produces a result of type
   (C++20)          std::weak_equality
                    \fI(function template)\fP 

.SH Category:

     * Todo no example
