.TH std::basic_string::npos 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   static const size_type npos = -1;

   This is a special value equal to the maximum value representable by the type
   size_type. The exact meaning depends on context, but it is generally used either as
   end of string indicator by the functions that expect a string index or as the error
   indicator by the functions that return a string index.

.SH Example

   
// Run this code

 #include <iostream>
 #include <bitset>
 #include <string>

 int main()
 {
     // string search functions return npos if nothing is found
     std::string s = "test";
     if(s.find('a') == std::string::npos)
         std::cout << "no 'a' in 'test'\\n";

     // functions that take string subsets as arguments
     // use npos as the "all the way to the end" indicator
     std::string s2(s, 2, std::string::npos);
     std::cout << s2 << '\\n';

     std::bitset<5> b("aaabb", std::string::npos, 'a', 'b');
     std::cout << b << '\\n';
 }

.SH Output:

 no 'a' in 'test'
 st
 00011
