.TH std::chrono::day::operator+=,std::chrono::day::operator-= 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::day::operator+=,std::chrono::day::operator-= \- std::chrono::day::operator+=,std::chrono::day::operator-=

.SH Synopsis
   constexpr std::chrono::day& operator+=(const std::chrono::days& d) \fB(1)\fP \fI(since C++20)\fP
   noexcept;
   constexpr std::chrono::day& operator-=(const std::chrono::days& d) \fB(2)\fP \fI(since C++20)\fP
   noexcept;

   Adds or subtracts d.count() days from the day value.

   1) Equivalent to *this = *this + d;
   2) Equivalent to *this = *this - d;

.SH Return value

   A reference to this day after modification

.SH Notes

   If the result would be outside the range [0, 255], the actual stored value is
   unspecified.

.SH Example


// Run this code

 #include <iostream>
 #include <chrono>

 int main()
 {

     std::chrono::day d {15};

     d += std::chrono::days(2);
     if (d == std::chrono::day(17)) {
         std::cout << "Days added correctly" << "\\n";
     } else {
         std::cout << "Days not added correctly" << "\\n";
     }

     d -= std::chrono::days(3);
     if (d == std::chrono::day(14)) {
         std::cout << "Days subtracted correctly" << "\\n";
     } else {
         std::cout << "Days not subtracted correctly" << "\\n";
     }

 }

.SH Output:

 Days added correctly
 Days subtracted correctly

.SH See also

   operator++
   operator++(int) increments or decrements the day
   operator--      \fI(public member function)\fP
   operator--(int)
   operator+       adds or subtracts a number of days and a day, or find the difference
   operator-       between two days
                   \fI(function)\fP
