.TH std::strcspn 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cstring>
   size_t strcspn( const char *dest, const char *src );

   Returns the length of the maximum initial segment of the byte string pointed to by
   dest, that consists of only the characters not found in byte string pointed to by
   src.

.SH Parameters

   dest - pointer to the null-terminated byte string to be analyzed
   src  - pointer to the null-terminated byte string that contains the characters to
          search for

.SH Return value

   The length of the maximum initial segment that contains only characters not found in
   the byte string pointed to by src

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

           returns the length of the maximum initial segment that consists
   strspn  of only the characters found in another byte string
           \fI(function)\fP 
   strpbrk finds the first location of any character in one string, in another string
           \fI(function)\fP 
   C documentation for
   strcspn

.SH Category:

     * Todo no example
