.TH std::chrono::time_zone 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::time_zone \- std::chrono::time_zone

.SH Synopsis
   Defined in header <chrono>
   class time_zone;            \fI(since C++20)\fP

   The class time_zone represents all time zone transitions for a specific geographic
   area.

   Users cannot construct time_zone objects. The library implementation creates
   time_zone objects when it initializes the time zone database and provides const
   access to these objects.

   time_zone is not copyable but does have a defaulted move constructor and a defaulted
   move assignment operator. However, as users have only const access to time_zone
   objects, these functions cannot be called in user code without invoking undefined
   behavior.

.SH Member functions

   name     obtains the name of this time_zone
            \fI(public member function)\fP
   get_info obtain information associated with a sys_time or local_time
            \fI(public member function)\fP
   to_sys   converts a local_time in this time zone to a sys_time
            \fI(public member function)\fP
   to_local converts a sys_time to a local_time in this time zone
            \fI(public member function)\fP

   Nonmember functions

   operator==  compares two time_zone objects
   operator<=> \fI(function)\fP
