.TH std::ranges::chunk_view::iterator 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::chunk_view::iterator \- std::ranges::chunk_view::iterator

.SH Synopsis
   template< bool Const >  (since C++23)
   class /*iterator*/      (exposition only*)

   The return type of chunk_view::begin, and of chunk_view::end when the underlying
   view V is a common_range.

   Present only if V models forward_range.

   The type /*iterator*/<true> is returned by the const-qualified overloads. The type
   /*iterator*/<false> is returned by the non-const-qualified overloads.

.SH Member types

   Member type       Definition
   Parent (private)  const chunk_view if Const is true, otherwise chunk_view.
                     (exposition-only member type*)
   Base (private)    const V if Const is true, otherwise V.
                     (exposition-only member type*)
   iterator_category std::input_iterator_tag
                       * std::random_access_iterator_tag, if Base models
                         random_access_range. Otherwise,
   iterator_concept    * std::bidirectional_iterator_tag, if Base models
                         bidirectional_range. Otherwise,
                       * std::forward_iterator_tag.
   value_type        decltype(views::take(ranges::subrange(current_, end_), n_));.
   difference_type   ranges::range_difference_t<Base>

   Data members

   Member object      Definition
                      ranges::iterator_t<Base>, holds an iterator to the first element
   current_ (private) of current chunk in the underlying sequence (i.e. the begin of a
                      chunk).
                      (exposition-only member object*)
                      ranges::sentinel_t<Base>, holds a sentinel to the end of the
   end_ (private)     underlying sequence.
                      (exposition-only member object*)
                      ranges::range_difference_t<Base>, holds initial number of
   n_ (private)       elements in the chunk (the last chunk can be smaller).
                      (exposition-only member object*)
                      ranges::range_difference_t<Base>, usually equals to
   missing_ (private) ranges::advance(current_, n_, end_);.
                      (exposition-only member object*)

.SH Member functions

   constructor     constructs an iterator
   (C++23)         \fI(public member function)\fP
   base            returns an iterator to current element
   (C++23)         \fI(public member function)\fP
   operator*       accesses the element
   (C++23)         \fI(public member function)\fP
   operator[]      accesses an element by index
   (C++23)         \fI(public member function)\fP
   operator++
   operator++(int)
   operator--      advances or decrements the underlying iterator
   operator--(int) \fI(public member function)\fP
   operator+=
   operator-=
   (C++23)

.SH Non-member functions

   operator==
   operator<
   operator>   compares the underlying iterators
   operator<=  \fI(function)\fP
   operator>=
   operator<=>
   (C++23)
   operator+   performs iterator arithmetic
   operator-   \fI(function)\fP
   (C++23)

.SH Example

    This section is incomplete
    Reason: no example

.SH References

     * C++23 standard (ISO/IEC 14882:2023):

     * 26.7.28.7 Class template chunk_view::iterator for forward ranges
       [range.chunk.fwd.iter]

.SH See also


.SH Category:
     * Todo no example
