.TH std::ranges::chunk_view::size 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::chunk_view::size \- std::ranges::chunk_view::size

.SH Synopsis
   constexpr auto size() requires ranges::sized_range<V>;             \fB(1)\fP (since C++23)
   constexpr auto size() const requires ranges::sized_range<const V>; \fB(2)\fP (since C++23)

   Returns the number of elements, which is the smallest integer value that is not less
   than the quotient of dividing the size of underlying view base_ by the underlying
   data member n_, that holds the number passed to the constructor (0 if default
   constructed). Equivalent to

 return __to_unsigned_like(__div_ceil(ranges::distance(base_), n_));

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of elements.

.SH Example


// Run this code

 #include <ranges>

 int main()
 {
     constexpr static auto v = {1, 2, 3, 4, 5};
     constexpr auto w{ std::ranges::chunk_view(v, 2) };
     static_assert(w.size() == (5 / 2 + (5 % 2 ? 1 : 0)));
 }

.SH See also

   ranges::size  returns an integer equal to the size of a range
   (C++20)       (customization point object)
   ranges::ssize returns a signed integer equal to the size of a range
   (C++20)       (customization point object)
