.TH std::ctype::scan_not,std::ctype::do_scan_not 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ctype::scan_not,std::ctype::do_scan_not \- std::ctype::scan_not,std::ctype::do_scan_not

.SH Synopsis
   Defined in header <locale>
   public:                                                                         \fB(1)\fP
   const CharT* scan_not( mask m, const CharT* beg, const CharT* end ) const;
   protected:
   virtual const CharT* do_scan_not( mask m, const CharT* beg, const CharT* end)   \fB(2)\fP
   const;

   1) public member function, calls the protected virtual member function do_scan_not
   of the most derived class.
   2) Locates the first character in the character array [beg, end) that does not
   satisfy the classification mask m, that is, the first character c such that is(m, c)
   would return false.

.SH Parameters

   m   - mask to search for
   beg - pointer to the first character in an array of characters to search
   end - one past the end pointer for the array of characters to search

.SH Return value

   Pointer to the first character in [beg, end) that doesn't satisfy the mask, or end
   if no such character was found.

.SH Example

   
// Run this code

 #include <locale>
 #include <clocale>
 #include <iostream>
 #include <iterator>
  
 int main()
 {
     std::setlocale(LC_ALL, "en_US.utf8");
     std::wcout.imbue(std::locale("en_US.utf8"));
     auto& f = std::use_facet<std::ctype<wchar_t>>(std::wcout.getloc());
  
     // skip leading whitespace
     wchar_t s1[] = L"      \\t\\t\\n  Кошка";
     const wchar_t* p1 = f.scan_not(std::ctype_base::space, std::begin(s1), std::end(s1));
     std::wcout << "'" << p1 << "'\\n";
  
     // skip leading digits
     wchar_t s2[] = L"123456789ネプネプ";
     const wchar_t* p2 = f.scan_not(std::ctype_base::digit, std::begin(s2), std::end(s2));
     std::wcout << "'" << p2 << "'\\n";
 }

.SH Output:

 'Кошка'
 'ネプネプ'

.SH See also

              locates the first character in a sequence that fails given
   scan_not   classification, using the classification table
              \fI(public member function of std::ctype<char>)\fP 
   do_scan_is locates the first character in a sequence that conforms to given
   \fB[virtual]\fP  classification
              \fI(virtual protected member function)\fP 
