.TH std::scalbn,std::scalbln 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   float scalbn( float x, int exp );                \fI(since C++11)\fP
   double scalbn( double x, int exp );              \fI(since C++11)\fP
   long double scalbn( long double x, int exp );    \fI(since C++11)\fP
   double scalbn( Integral x, int exp );            \fI(since C++11)\fP
   float scalbln( float x, long exp );              \fI(since C++11)\fP
   double scalbln( double x, long exp );            \fI(since C++11)\fP
   long double scalbln( long double x, long exp );  \fI(since C++11)\fP
   double scalbln( Integral x, long exp );          \fI(since C++11)\fP

   Multiplies an floating point value x by FLT_RADIX raised to power exp. On binary
   system it is equivalent to std::ldexp()

.SH Parameters

   arg - floating point value
   exp - integer value

.SH Return value

   Returns x×FLT_RADIX^exp.

   If the result is too large for the underlying type, range error occurs and HUGE_VAL
   is returned.

.SH See also

   frexp decomposes a number into significand and a power of 2
         \fI(function)\fP
   ldexp multiplies a number by 2 raised to a power
         \fI(function)\fP
