.TH std::vwscanf,std::vfwscanf,std::vswscanf 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cwchar>
   int vwscanf( const wchar_t* format, va_list vlist );               \fB(1)\fP \fI(since C++11)\fP
   int vfwscanf( std::FILE* stream, const wchar_t* format, va_list    \fB(2)\fP \fI(since C++11)\fP
   vlist );
   int vswscanf( const wchar_t* buffer, const wchar_t* format,        \fB(3)\fP \fI(since C++11)\fP
   va_list vlist );

   Reads data from the a variety of sources, interprets it according to format and
   stores the results into locations defined by vlist.

   1) Reads the data from stdin
   2) Reads the data from file stream stream
   3) Reads the data from null-terminated wide string buffer

.SH Parameters

   stream - input file stream to read from
   buffer - pointer to a null-terminated wide string to read from
            pointer to a null-terminated wide string specifying how to read the input.
   format -
             This section is incomplete
   vlist  - variable argument list containing the receiving arguments

.SH Return value

   Number of arguments successfully read, or EOF if failure occurs.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   wscanf  reads formatted wide character input from stdin, a file stream or a buffer
   fwscanf \fI(function)\fP 
   swscanf
   C documentation for
   vwscanf,
   vfwscanf,
   vswscanf

   Categories:

     * Todo without reason
     * Todo no example
