.TH std::vector::get_allocator 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::vector::get_allocator \- std::vector::get_allocator

.SH Synopsis
   allocator_type get_allocator() const;  (noexcept since C++11)
                                          (constexpr since C++20)

   Returns the allocator associated with the container.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The associated allocator.

.SH Complexity

   Constant.
