.TH std::raw_storage_iterator::raw_storage_iterator 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   explicit raw_storage_iterator( OutputIt it );

   Initializes the iterator to point to the same value as it points.

.SH Parameters

   it - location to point to
