.TH std::optional::reset 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::optional::reset \- std::optional::reset

.SH Synopsis
   void reset();  \fI(since C++17)\fP

   If *this contains a value, destroy that value as if by value().T::~T(). Otherwise,
   there are no effects.

   *this does not contain a value after this call.

.SH Exceptions

   noexcept specification:
   noexcept

.SH See also

   operator= assigns contents
             \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept
