.TH std::experimental::latch::count_down 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::latch::count_down \- std::experimental::latch::count_down

.SH Synopsis
   void count_down( ptrdiff_t n = 1 ); \fB(1)\fP (concurrency TS)

   Atomically decrements the internal counter by n without blocking the caller.

   If n is greater than the value of the internal counter or is negative, the behavior
   is undefined.

   This operation synchronizes with all calls that block on this latch and all is_ready
   calls on this latch that returns true.

.SH Parameters

   n - the value by which the internal counter is decreased

.SH Return value

   \fI(none)\fP

.SH Exceptions

   Throws nothing.
