.TH std::experimental::reflect::SpecialMemberFunction 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::reflect::SpecialMemberFunction \- std::experimental::reflect::SpecialMemberFunction

.SH Synopsis
   Defined in header <experimental/reflect>
   template< class T >                                                  (reflection TS)
   concept SpecialMemberFunction = RecordMember<T> && /* see below */;

   The SpecialMemberFunction concept is satisfied if and only if T reflects a special
   member function.

.SH Example

    This section is incomplete
    Reason: examples

.SH See also

    This section is incomplete
    Reason: templatization

.SH Category:
     * Todo with reason
