.TH std::move_iterator::operator= 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   template< class U >
   move_iterator& operator=( const move_iterator<U>& other );

   Copy assignment operator. The underlying iterator is assigned the value of the
   underlying iterator of other, i.e. other.base().

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Example
     * 4 See also

.SH Parameters

   other - iterator adaptor to assign

.SH Return value

   *this

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   constructor   constructs a new iterator adaptor
                 \fI(public member function)\fP

.SH Category:

     * Todo no example
