.TH std::future_error::operator= 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::future_error::operator= \- std::future_error::operator=

.SH Synopsis
   future_error& operator=( const future_error& other ) noexcept;  \fI(since C++11)\fP

   Assigns the contents with those of other. If *this and other both have dynamic type
   std::future_error then std::strcmp(what(), other.what()) == 0 after assignment.

.SH Parameters

   other - another future_error object to assign with

.SH Return value

   *this

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
