.TH std::pmr::polymorphic_allocator<T>::deallocate_object 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::pmr::polymorphic_allocator<T>::deallocate_object \- std::pmr::polymorphic_allocator<T>::deallocate_object

.SH Synopsis
   template <class u>           \fI(since C++20)\fP
   void delete_object( U* p );

   Destroys the object of type U and deallocates storage allocated for it.

   Equivalent to

 destroy(p);
 deallocate_object(p);

.SH Parameters

   p - pointer to the object to destroy and deallocate

.SH Exceptions

   Throws nothing.

.SH Notes

   This function was introduced for use with the fully-specialized allocator
   std::polymorphic_allocator<>, but it may be useful in any specialization.

.SH See also

   deallocate_bytes  Free raw memory obtained from allocate_bytes
   (C++20)           \fI(public member function)\fP
   deallocate_object Frees raw memory obtained by allocate_object
   (C++20)           \fI(public member function)\fP
   deallocate        deallocates storage using the allocator
   \fB[static]\fP          \fI(public static member function of std::allocator_traits<Alloc>)\fP
   deallocate        deallocates memory
                     \fI(public member function of std::pmr::memory_resource)\fP
