.TH std::cosh(std::complex) 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::cosh(std::complex) \- std::cosh(std::complex)

.SH Synopsis
   Defined in header <complex>
   template< class T >                      \fI(since C++11)\fP
   complex<T> cosh( const complex<T>& z );

   Computes complex hyperbolic cosine of a complex value z.

.SH Parameters

   z - complex value

.SH Return value

   Complex hyperbolic cosine of z

.SH See also

   cos(std::complex)  computes cosine of a complex number (cos(z))
                      \fI(function template)\fP 
   acos(std::complex) computes arc cosine of a complex number (arccos(z))
   \fI(C++11)\fP            \fI(function template)\fP 
