.TH std::chrono::month_day_last::month 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month_day_last::month \- std::chrono::month_day_last::month

.SH Synopsis
   constexpr std::chrono::month month() const noexcept;  \fI(since C++20)\fP

   Retrieves a copy of the std::chrono::month object stored in *this.

.SH Return value

   A copy of the std::chrono::month object stored in *this.

.SH Example


// Run this code

 #include <chrono>
 #include <iostream>

 using namespace std::chrono;

 int main()
 {
     std::cout << std::boolalpha;

     auto mdl{February/last}; // Last day of a February
     auto ymdl{year(2020) / mdl};
     std::cout << (year_month_day{ymdl} == year_month_day{February/29/2020}) << ' ';

     mdl = (mdl.month() + months(1)) / last; // Last day of the next month, in 2020
     ymdl = year(2020) / mdl;
     std::cout << (year_month_day{ymdl} == year_month_day{March/31/2020}) << '\\n';
 }

.SH Output:

 true true
