.TH std::experimental::reflect::Named 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::reflect::Named \- std::experimental::reflect::Named

.SH Synopsis
   Defined in header <experimental/reflect>
   template< class T >                            (reflection TS)
   concept Named = Object<T> && /* see below */;

   The Named concept is satisfied if and only if T has an associated (possibly empty)
   name.

.SH Example

    This section is incomplete
    Reason: examples

.SH See also

    This section is incomplete
    Reason: templatization

.SH Category:
     * Todo with reason
