.TH std::subtract_with_carry_engine::discard 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::subtract_with_carry_engine::discard \- std::subtract_with_carry_engine::discard

.SH Synopsis
   void discard( unsigned long long z );  \fI(since C++11)\fP

   Advances the internal state by z times. Equivalent to calling operator() z times and
   discarding the result

.SH Parameters

   z - integer value specifying the number of times to advance the state by

.SH Return value

   \fI(none)\fP

.SH Complexity

    This section is incomplete

.SH Notes

   For some engines, "fast jump" algorithms are known, which advancing the state by
   many steps (order of millions) without calculating intermediate state transitions.

.SH See also

   operator() advances the engine's state and returns the generated value
              \fI(public member function)\fP 

.SH Category:

     * Todo without reason
