.TH std::generator::generator 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::generator::generator \- std::generator::generator

.SH Synopsis
   generator( const generator& ) = delete;  \fB(1)\fP (since C++23)
   generator( generator&& other ) noexcept; \fB(2)\fP (since C++23)

   Constructs a generator.

   1) The copy-constructor is deleted.
   2) The move-constructor that initializes the underlying coroutine_ with
   std::exchange(other.coroutine_, {}), and the underlying stack of coroutine handles
   (active_) with std::exchange(other.active_, nullptr). Note, that the iterators,
   previously obtained from other, are not invalidated, but become iterators into
   *this.

.SH Parameters

   other - a generator object to be moved in

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
