.TH std::experimental::latch::latch 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::latch::latch \- std::experimental::latch::latch

.SH Synopsis
   explicit latch( ptrdiff_t value ); \fB(1)\fP (concurrency TS)
   latch( const latch & ) = delete;   \fB(2)\fP (concurrency TS)

   1) Constructs a latch and initializes its internal counter.
   2) Copy constructor is deleted. latch is not copyable.

.SH Parameters

   value - the initial value of the internal counter; must be non-negative
