.TH std::reference_wrapper::operator= 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   reference_wrapper& operator=( const reference_wrapper<T>& other );  \fI(since C++11)\fP

   Copy assignment operator. Drops the current reference and stores a reference to
   other.get().

.SH Parameters

   other - reference wrapper to copy

.SH Return values

   *this

.SH Exceptions

   noexcept specification:  
   noexcept
     
