.TH std::experimental::ranges::SignedIntegral 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::SignedIntegral \- std::experimental::ranges::SignedIntegral

.SH Synopsis
   Defined in header <experimental/ranges/concepts>
   template < class T >
   concept bool SignedIntegral() { return Integral<T>() &&                  (ranges TS)
   std::is_signed<T>::value; }

   The concept SignedIntegral<T>() is satisfied if and only if T is an integral type
   and std::is_signed<T>::value is true.

.SH Notes

   SignedIntegral<T>() may be satisfied by a type that is not a signed integer type,
   for example, char (on a system where char is signed).

.SH See also

   is_integral checks if a type is integral type
   \fI(C++11)\fP     \fI(class template)\fP
   is_signed   checks if a type is signed arithmetic type
   \fI(C++11)\fP     \fI(class template)\fP
