.TH std::hash<std::experimental::optional> 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <optional>
   template<class T>                             (library fundamentals TS)
   struct hash<std::experimental::optional<T>>;

   The template specialization of std::hash for the std::experimental::optional class
   allows users to obtain hashes of the values contained in optional objects.

.SH Template parameters

   T - the type of the value contained in optional object. The specialization
       std::hash<T> must meet the requirements of class template hash.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   hash    hash function object
   \fI(C++11)\fP \fI(class template)\fP 

.SH Category:

     * Todo no example
