.TH std::move_only_function::~move_only_function 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::move_only_function::~move_only_function \- std::move_only_function::~move_only_function

.SH Synopsis
   ~move_only_function();  (since C++23)

   Destroys the std::move_only_function object. If the std::move_only_function is not
   empty, its target is also destroyed.

.SH See also

   destructor   destroys a std::function instance
                \fI(public member function of std::function<R(Args...)>)\fP
