.TH std::error_category::error_category 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_category::error_category \- std::error_category::error_category

.SH Synopsis
   constexpr error_category() noexcept;              \fB(1)\fP \fI(since C++11)\fP
   error_category( const error_category& ) = delete; \fB(2)\fP \fI(since C++11)\fP

   1) Constructs the error category object.
   2) Copy constructor is deleted. error_category is neither MoveConstructible nor
   CopyConstructible.

.SH Parameters

   \fI(none)\fP

   Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

      DR    Applied to        Behavior as published             Correct behavior
   LWG 2145 C++11      error_category was not constructible default constructor added
