.TH std::unique_lock::operator= 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   unique_lock& operator=( unique_lock&& other );  \fI(since C++11)\fP

   Move assignment operator. Replaces the contents with those of other using move
   semantics.

   If prior to the call *this has an associated mutex and has acquired ownership of it,
   the mutex is unlocked.

.SH Parameters

   other - another unique_lock to replace the state with

.SH Return value

   *this

.SH Exceptions

   noexcept specification:  
   noexcept
     
