.TH std::multimap::clear 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::multimap::clear \- std::multimap::clear

.SH Synopsis
   void clear();  (noexcept since C++11)

   Erases all elements from the container. After this call, size() returns zero.

   Invalidates any references, pointers, and iterators referring to contained elements.
   Any past-the-end iterator remains valid.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Complexity

   Linear in the size of the container, i.e., the number of elements.

.SH Example


// Run this code

 #include <iostream>
 #include <string_view>
 #include <map>

 void print_info(std::string_view rem, const std::multimap<int, char>& v)
 {
     std::cout << rem << "{ ";
     for (const auto& [key, value] : v)
         std::cout << '[' << key << "]:" << value << ' ';
     std::cout << "}\\n";
     std::cout << "Size=" << v.size() << '\\n';
 }

 int main()
 {
     std::multimap<int, char> container{{1, 'x'}, {2, 'y'}, {3, 'z'}};
     print_info("Before clear: ", container);
     container.clear();
     print_info("After clear: ", container);
 }

.SH Output:

 Before clear: { [1]:x [2]:y [3]:z }
 Size=3
 After clear: { }
 Size=0

  Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to           Behavior as published              Correct behavior
   LWG 224 C++98      the complexity was log(size()) + N, but N corrected to 'linear in
                      was not defined                           size()'

.SH See also

   erase erases elements
         \fI(public member function)\fP
