.TH std::wcscmp 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::wcscmp \- std::wcscmp

.SH Synopsis
   Defined in header <cwchar>
   int wcscmp( const wchar_t* lhs, const wchar_t* rhs );

   Compares two null-terminated wide strings lexicographically.

   The sign of the result is the sign of the difference between the values of the first
   pair of wide characters that differ in the strings being compared.

   The behavior is undefined if lhs or rhs are not pointers to null-terminated wide
   strings.

.SH Parameters

   lhs, rhs - pointers to the null-terminated wide strings to compare

.SH Return value

   Negative value if lhs appears before rhs in lexicographical order.

   Zero if lhs and rhs compare equal.

   Positive value if lhs appears after rhs in lexicographical order.

.SH Notes

   This function is not locale-sensitive, unlike std::wcscoll, and the order may not be
   meaningful when characters from different Unicode blocks are used together or when
   the order of code units does not match collation order.

.SH Example


// Run this code

 #include <algorithm>
 #include <cwchar>
 #include <iostream>
 #include <vector>

 int main()
 {
     std::vector<const wchar_t*> leaders{L"Ленин", L"Сталин", L"Маленков",
         L"Хрущёв", L"Брежнев", L"Андропов", L"Черненко", L"Горбачёв"};

     std::ranges::sort(leaders, [](auto leaderLHS, auto leaderRHS)
     {
         return std::wcscmp(leaderLHS, leaderRHS) < 0;
     });

     std::setlocale(LC_ALL, "en_US.utf8");
     std::wcout.imbue(std::locale("en_US.utf8"));
     for (auto leader : leaders)
         std::wcout << leader << '\\n';
 }

.SH Possible output:

 Андропов
 Брежнев
 Горбачёв
 Ленин
 Маленков
 Сталин
 Хрущёв
 Черненко

.SH See also

   wcsncmp compares a certain amount of characters from two wide strings
           \fI(function)\fP
   wmemcmp compares a certain amount of wide characters from two arrays
           \fI(function)\fP
   strcmp  compares two strings
           \fI(function)\fP
   wcscoll compares two wide strings in accordance to the current locale
           \fI(function)\fP
   C documentation for
   wcscmp
