.TH std::experimental::pmr::monotonic_buffer_resource::~monotonic_buffer_resource 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::pmr::monotonic_buffer_resource::~monotonic_buffer_resource \- std::experimental::pmr::monotonic_buffer_resource::~monotonic_buffer_resource

.SH Synopsis
   virtual ~monotonic_buffer_resource();  (library fundamentals TS)

   Destroys a monotonic_buffer_resource.

   Deallocates all memory owned by this resource by calling this->release().

.SH See also

   release Release all allocated memory
           \fI(public member function)\fP
