.TH std::move_iterator::operator*,-> 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::move_iterator::operator*,-> \- std::move_iterator::operator*,->

.SH Synopsis
   reference operator* () const; \fB(1)\fP
   pointer   operator->() const; \fB(2)\fP

   Returns a rvalue-reference or pointer to the current element.

   1) Equivalent to std::move(*current);              (until C++17)
   1) Equivalent to static_cast<reference>(*current); (since C++17)

   2) Equivalent to current.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Rvalue-reference or pointer to the current element.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator[] accesses an element by index
              \fI(public member function)\fP 

.SH Category:

     * Todo no example
