.TH std::queue::swap 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::queue::swap \- std::queue::swap

.SH Synopsis
   void swap( queue& other ) noexcept(/* see below */);  \fI(since C++11)\fP

   Exchanges the contents of the container adaptor with those of other. Effectively
   calls using std::swap; swap(c, other.c);

.SH Parameters

   other - container adaptor to exchange the contents with

.SH Return value

   \fI(none)\fP

.SH Exceptions

   In the noexcept expressions below, the identifier swap is looked up in the
   same manner as the C++17 std::is_nothrow_swappable trait.                     (until
                                                                                 C++17)
   noexcept specification:
   noexcept(noexcept(swap(c, other.c)))
   noexcept specification:                                                       (since
   noexcept(std::is_nothrow_swappable<Container>::value)                         C++17)

.SH Complexity

   Same as underlying container (typically constant)

.SH See also

   std::swap(std::queue) specializes the std::swap algorithm
                         \fI(function template)\fP

.SH Category:

     * conditionally noexcept
