.TH std::isalnum(std::locale) 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::isalnum(std::locale) \- std::isalnum(std::locale)

.SH Synopsis
   Defined in header <locale>
   template< class charT >
   bool isalnum( charT ch, const locale& loc );

   Checks if the given character classified as an alphanumeric character by the given
   locale's std::ctype facet.

.SH Parameters

   ch  - character
   loc - locale

.SH Return value

   Returns true if the character is classified as alphanumeric, false otherwise.

.SH Possible implementation

   template< class charT >
   bool isalnum( charT ch, const std::locale& loc ) {
       return std::use_facet<std::ctype<charT>>(loc).is(std::ctype_base::alnum, ch);
   }

.SH Example

   Demonstrates the use of isalnum() with different locales (OS-specific).


// Run this code

 #include <iostream>
 #include <locale>
 int main()
 {
     const wchar_t c = L'\\u2135'; // mathematical symbol aleph

     std::locale loc1("C");
     std::cout << "isalnum('ℵ', C locale) returned "
                << std::boolalpha << std::isalnum(c, loc1) << '\\n';

     std::locale loc2("en_US.UTF-8");
     std::cout << "isalnum('ℵ', Unicode locale) returned "
               << std::boolalpha << std::isalnum(c, loc2) << '\\n';
 }

.SH Output:

 isalnum('ℵ', C locale) returned false
 isalnum('ℵ', Unicode locale) returned true

.SH See also

   isalnum  checks if a character is alphanumeric
            \fI(function)\fP
   iswalnum checks if a wide character is alphanumeric
            \fI(function)\fP
