.TH std::basic_string_view::empty 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string_view::empty \- std::basic_string_view::empty

.SH Synopsis
   constexpr bool empty() const;  \fI(since C++17)\fP

   Checks if the view has no characters, i.e. whether size() == 0.

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if the view is empty, false otherwise

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH Complexity

   Constant.

.SH See also

   size     returns the number of characters
   length   \fI(public member function)\fP 
   max_size returns the maximum number of characters
            \fI(public member function)\fP 

.SH Category:

     * unconditionally noexcept
