.TH std::chrono::year::max 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year::max \- std::chrono::year::max

.SH Synopsis
   static constexpr year max() noexcept;  \fI(since C++20)\fP

   Returns the largest possible year, that is, std::chrono::year(32767).

.SH Return value

   std::chrono::year(32767)

.SH Example


// Run this code

 #include <iostream>
 #include <chrono>

 int main()
 {
     std::cout << "The maximum year is: " << (int)std::chrono::year::max() << '\\n';
 }

.SH Output:

 The maximum year is: 32767
