.TH std::vwprintf,std::vfwprintf,std::vswprintf 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cwchar>
   int vwprintf( const wchar_t* format, va_list vlist );                           \fB(1)\fP
   int vfwprintf( std::FILE* stream, const wchar_t* format, va_list vlist );       \fB(2)\fP
   int vswprintf( const wchar_t* buffer, std::size_t size, const wchar_t* format,  \fB(3)\fP
   va_list vlist );

   Loads the data from locations, defined by vlist,, converts them to wide string
   equivalents and writes the results to a variety of sinks.

   1) Writes the results to stdout.
   2) Writes the results to a file stream stream.
   3) Writes the results to a wide string buffer.

.SH Parameters

    This section is incomplete

.SH Return value

   Number of wide characters written if successful or negative value if an error
   occurred.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   wprintf  prints formatted wide character output to stdout, a file stream or a buffer
   fwprintf \fI(function)\fP 
   swprintf
   C documentation for
   vwprintf,
   vfwprintf,
   vswprintf

   Categories:

     * Todo without reason
     * Todo no example
