.TH std::ranges::enumerate_view::iterator::operator* 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::enumerate_view::iterator::operator* \- std::ranges::enumerate_view::iterator::operator*

.SH Synopsis
   constexpr auto operator*() const;  (since C++23)

   Returns the current element in the enumerate_view.

   Equivalent to: return reference-type(pos_, *current_);.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The current element.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator[] accesses an element by index
   (C++23)    \fI(public member function)\fP

.SH Category:
     * Todo no example
