.TH std::valarray::swap 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::valarray::swap \- std::valarray::swap

.SH Synopsis
   void swap( valarray& other );

   Swaps the contents with those of other.

.SH Parameters

   other - another valarray to swap the contents with

.SH Return value

   \fI(none)\fP

.SH Exceptions

   \fI(none)\fP                    \fI(until C++11)\fP
   noexcept specification:  
   noexcept                  \fI(since C++11)\fP
     

.SH Category:

     * unconditionally noexcept

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
