.TH std::filesystem::directory_iterator::operator= 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::directory_iterator::operator= \- std::filesystem::directory_iterator::operator=

.SH Synopsis
   directory_iterator& operator++()
                                                         \fI(since C++17)\fP
   directory_iterator& increment( std::error_code& ec )

   Advances the iterator to the next entry.

    This section is incomplete

.SH Parameters

   ec - error code to store error status to

.SH Return value

   *this

.SH Exceptions

   1)

    This section is incomplete

   2)
   noexcept specification:  
   noexcept
     
   Categories:

     * Todo without reason
     * unconditionally noexcept
