.TH std::multimap::count 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::multimap::count \- std::multimap::count

.SH Synopsis
   size_type count( const Key& key ) const; \fB(1)\fP
   template< class K >                      \fB(2)\fP \fI(since C++14)\fP
   size_type count( const K& x ) const;

   Returns the number of elements with key that compares equivalent to the specified
   argument.

   1) Returns the number of elements with key key.
   2) Returns the number of elements with key that compares equivalent to the value x.
   This overload only participates in overload resolution if the qualified-id
   Compare::is_transparent is valid and denotes a type. They allow calling this
   function without constructing an instance of Key.

.SH Parameters

   key - key value of the elements to count
   x   - alternative value to compare to the keys

.SH Return value

   Number of elements with key that compares equivalent to key or x.

.SH Complexity

   Logarithmic in the size of the container plus linear in the number of the elements
   found.

.SH See also

   find        finds element with specific key
               \fI(public member function)\fP
   equal_range returns range of elements matching a specific key
               \fI(public member function)\fP
