.TH std::future::share 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::future::share \- std::future::share

.SH Synopsis
   std::shared_future<T> share();

   Transfers the shared state of *this to a std::shared_future object. Multiple
   std::shared_future objects may reference the same shared state, which is not
   possible with std::future.

   After calling share on a std::future, valid() == false.

   The behavior is undefined if valid()== false before the call to this function.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A std::shared_future object containing the shared state previously held by *this

.SH Notes

   The implementations are encouraged to detect the case when valid == false before the
   call and throw a future_error with an error condition of future_errc::no_state.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   shared_future waits for a value (possibly referenced by other futures) that is set
   \fI(C++11)\fP       asynchronously
                 \fI(class template)\fP 

.SH Category:

     * Todo no example
