.TH std::ranges::stride_view::iterator::base 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::stride_view::iterator::base \- std::ranges::stride_view::iterator::base

.SH Synopsis
   constexpr ranges::iterator_t<Base> base() &&;                     \fB(1)\fP (since C++23)
   constexpr const ranges::iterator_t<Base>& base() const& noexcept; \fB(2)\fP (since C++23)

   Returns the underlying iterator. Let current_ be the underlying iterator.

   1) Equivalent to: return std::move(current_);.
   2) Equivalent to: return current_;.

.SH Parameters

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
