.TH std::basic_streambuf::sbumpc 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_streambuf::sbumpc \- std::basic_streambuf::sbumpc

.SH Synopsis
   int_type sbumpc();

   Reads one character and advances the input sequence by one character.

   If the input sequence read position is not available, returns uflow(). Otherwise
   returns Traits::to_int_type(*gptr()).

.SH Parameters

   \fI(none)\fP

.SH Return value

   The value of the character pointed to by the get pointer, or Traits::eof() if the
   read position is not available.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   sgetc  reads one character from the input sequence without advancing the sequence
          \fI(public member function)\fP
   snextc advances the input sequence, then reads one character without advancing again
          \fI(public member function)\fP

.SH Category:

     * Todo no example
