.TH std::experimental::reflect::Scope 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::reflect::Scope \- std::experimental::reflect::Scope

.SH Synopsis
   Defined in header <experimental/reflect>
   template< class T >                            (reflection TS)
   concept Scope = Object<T> && /* see below */;

   The Scope concept is satisfied if and only if T reflects a namespace (including the
   global namespace), class, enumeration, function, or closure-type (Note: Any such T
   that does not reflect the global namespace also satisfies ScopeMember).

.SH Example

    This section is incomplete
    Reason: examples

.SH See also

    This section is incomplete
    Reason: templatization

.SH Category:
     * Todo with reason
