.TH std::chrono::month_weekday::month_weekday 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month_weekday::month_weekday \- std::chrono::month_weekday::month_weekday

.SH Synopsis
   constexpr month_weekday( const std::chrono::month& m,
                            const std::chrono::weekday_indexed& wdi )     \fI(since C++20)\fP
   noexcept;

   Constructs a month_weekday object that stores the month m and the weekday_indexed
   wdi.

.SH Notes

   A more convenient way to construct a month_weekday is with operator/, e.g.,
   std::chrono::April/std::chrono::Sunday[2].

.SH See also

   operator/ conventional syntax for Gregorian calendar date creation
   (C++20)   \fI(function)\fP
