.TH std::basic_string_view::substr 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string_view::substr \- std::basic_string_view::substr

.SH Synopsis
   constexpr basic_string_view                                    \fI(since C++17)\fP
       substr(size_type pos = 0, size_type count = npos ) const;

   Returns a view of the substring [pos, pos + rcount), where rcount is the smaller of
   count and size() - pos.

.SH Parameters

   pos   - position of the first character
   count - requested length

.SH Return value

   View of the substring [pos, pos + rcount).

.SH Exceptions

   std::out_of_range if pos > size()

.SH Complexity

   Constant.

.SH See also

   copy copies characters
        \fI(public member function)\fP 
   find find characters in the view
        \fI(public member function)\fP 
