.TH std::front_inserter 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::front_inserter \- std::front_inserter

.SH Synopsis
   Defined in header <iterator>
   template< class Container >
   std::front_insert_iterator<Container> front_inserter( Container& c );

   front_inserter is a convenience function template that constructs a
   std::front_insert_iterator for the container c with the type deduced from the type
   of the argument.

.SH Parameters

   c - container that supports a push_front operation

.SH Return value

   A std::front_insert_iterator which can be used to add elements to the beginning of
   the container c

.SH Possible implementation

   template< class Container >
   std::front_insert_iterator<Container> front_inserter( Container& c )
   {
       return std::front_insert_iterator<Container>(c);
   }

.SH Example

   
// Run this code

 #include <iostream>
 #include <deque>
 #include <algorithm>
 #include <iterator>
  
 int main()
 {
     std::deque<int> v{1,2,3,4,5,6,7,8,9,10};
     std::fill_n(std::front_inserter(v), 3, -1);
     for (int n : v)
         std::cout << n << ' ';
 }

.SH Output:

 -1 -1 -1 1 2 3 4 5 6 7 8 9 10

.SH See also

   front_insert_iterator iterator adaptor for insertion at the front of a container
                         \fI(class template)\fP 
                         creates a std::back_insert_iterator of type inferred from the
   back_inserter         argument
                         \fI(function template)\fP 
                         creates a std::insert_iterator of type inferred from the
   inserter              argument
                         \fI(function template)\fP 
