.TH std::experimental::observer_ptr::swap 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::observer_ptr::swap \- std::experimental::observer_ptr::swap

.SH Synopsis
   constexpr void swap(observer_ptr& other);  (library fundamentals TS v2)

   Swaps the watched object of *this and another observer_ptr object other, by invoking
   swap on the stored pointers of *this and other.

.SH Parameters

   other - another observer_ptr object to swap the watched object with

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH Example

    This section is incomplete
    Reason: no example

   Categories:

     * unconditionally noexcept
     * Todo no example
