.TH std::suspend_never 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::suspend_never \- std::suspend_never

.SH Synopsis
   Defined in header <coroutine>
   struct suspend_never;          \fI(since C++20)\fP

   suspend_never is an empty class which can be used to indicate that an await
   expression never suspends and does not produce a value.

.SH Member functions

   await_ready   indicates that an await expression never suspends
   (C++20)       \fI(public member function)\fP
   await_suspend no-op
   (C++20)       \fI(public member function)\fP
   await_resume  no-op
   (C++20)       \fI(public member function)\fP

std::suspend_never::await_ready

   constexpr bool await_ready() const noexcept { return true; }  \fI(since C++20)\fP

   Always returns true, indicating that an await expression never suspends.

std::suspend_never::await_suspend

   constexpr void await_suspend( std::coroutine_handle<> ) const          \fI(since C++20)\fP
   noexcept {}

   Does nothing.

std::suspend_never::await_resume

   constexpr void await_resume() const noexcept {}  \fI(since C++20)\fP

   Does nothing. An await expression does not produce a value if suspend_never is used.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   suspend_always indicates that an await-expression should always suspend
   (C++20)        \fI(class)\fP

.SH Category:
     * Todo no example
