.TH std::lognormal_distribution::lognormal_distribution 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   explicit lognormal_distribution( RealType m = 0.0, RealType s =    \fB(1)\fP \fI(since C++11)\fP
   1.0 );
   explicit lognormal_distribution( const param_type& params );       \fB(2)\fP \fI(since C++11)\fP

   Constructs a new distribution object. The first version uses m and s as the
   distribution parameters, the second version uses params as the distribution
   parameters.

.SH Parameters

   m      - the m distribution parameter (log-scale)
   s      - the s distribution parameter (shape)
   params - the distribution parameter set
