.TH std::gamma_distribution::gamma_distribution 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::gamma_distribution::gamma_distribution \- std::gamma_distribution::gamma_distribution

.SH Synopsis
   gamma_distribution() : gamma_distribution(1.0) {}                  \fB(1)\fP \fI(since C++11)\fP
   explicit gamma_distribution( RealType alpha, RealType beta = 1.0   \fB(2)\fP \fI(since C++11)\fP
   );
   explicit gamma_distribution( const param_type& params );           \fB(3)\fP \fI(since C++11)\fP

   Constructs a new distribution object.

   2) Uses alpha and beta as the distribution parameters.
   3) Uses params as the distribution parameters.

.SH Parameters

   alpha  - the α distribution parameter (shape)
   beta   - the β distribution parameter (scale)
   params - the distribution parameter set

   Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to      Behavior as published       Correct behavior
   P0935R0 C++11      default constructor was explicit made implicit
