.TH std::swap(std::map) 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::swap(std::map) \- std::swap(std::map)

.SH Synopsis
   template< class Key, class T, class Compare, class Alloc >

   void swap( map<Key,T,Compare,Alloc>& lhs,

   map<Key,T,Compare,Alloc>& rhs );

   Specializes the std::swap algorithm for std::map. Swaps the contents of lhs and rhs.
   Calls lhs.swap(rhs).

.SH Parameters

   lhs, rhs - containers whose contents to swap

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH Exceptions
                                     \fI(since C++17)\fP
   noexcept specification:
   noexcept(noexcept(lhs.swap(rhs)))

.SH See also

   swap swaps the contents
        \fI(public member function)\fP

.SH Category:

     * conditionally noexcept
