.TH std::filesystem::path::is_absolute,is_relative 3 "2022.07.31" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::path::is_absolute,is_relative \- std::filesystem::path::is_absolute,is_relative

.SH Synopsis
   bool is_absolute() const; \fB(1)\fP \fI(since C++17)\fP
   bool is_relative() const; \fB(2)\fP \fI(since C++17)\fP

   Checks whether the path is absolute or relative. An absolute path is a path that
   unambiguously identifies the location of a file without reference to an additional
   starting location. The first version returns true if the path, in native format, is
   absolute, false otherwise; the second version the other way round.

.SH Parameters

   \fI(none)\fP

.SH Return value

   1) true if the path is absolute, false otherwise.
   2) false if the path is absolute, true otherwise.

.SH Exceptions

   May throw implementation-defined exceptions.

.SH Notes

   The path "/" is absolute on a POSIX OS, but is relative on Windows.

.SH See also

   absolute composes an absolute path
   \fI(C++17)\fP  \fI(function)\fP
