.TH std::messages<CharT>::messages 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::messages<CharT>::messages \- std::messages<CharT>::messages

.SH Synopsis
   Defined in header <locale>
   explicit messages( std::size_t refs = 0 );

   Creates a std::messages facet and forwards the starting reference count refs to the
   base class constructor, locale::facet::facet()

.SH Parameters

   refs - starting reference count
