.TH std::filesystem::directory_options 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::directory_options \- std::filesystem::directory_options

.SH Synopsis
   Defined in header <filesystem>
   enum class directory_options {

   none = /* unspecified */,
   follow_directory_symlink = /* unspecified */,  \fI(since C++17)\fP
   skip_permission_denied = /* unspecified */

   };

   This type represents available options that control the behavior of the
   directory_iterator and recursive_directory_iterator.

   directory_options satisfies the requirements of BitmaskType (which means the bitwise
   operators operator&, operator|, operator^, operator~, operator&=, operator|=, and
   operator^= are defined for this type). none represents the empty bitmask; every
   other enumerator represents a distinct bitmask element.

.SH Member constants

       Member constant                                Meaning
   none                     (Default) Skip directory symlinks, permission denied is
                            error.
   follow_directory_symlink Follow rather than skip directory symlinks.
   skip_permission_denied   Skip directories that would otherwise result in permission
                            denied errors.

.SH See also

   constructor   constructs a directory iterator
                 \fI(public member function of std::filesystem::directory_iterator)\fP
                 constructs a recursive directory iterator
   constructor   \fI\fI(public member\fP function of\fP
                 std::filesystem::recursive_directory_iterator)
