.TH std::system_error::code 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::system_error::code \- std::system_error::code

.SH Synopsis
   const std::error_code& code() const;  \fI(since C++11)\fP

   Returns the stored error code.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The stored error code.

.SH Exceptions

   noexcept specification:
   noexcept

.SH See also

   what      returns explanatory string
   \fB[virtual]\fP \fI(virtual public member function)\fP

.SH Category:

     * unconditionally noexcept
