.TH std::ranges::common_range 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::common_range \- std::ranges::common_range

.SH Synopsis
   Defined in header <ranges>
   template< class T >

   concept common_range =                                                 \fI(since C++20)\fP

   ranges::range<T> && std::same_as<ranges::iterator_t<T>,
   ranges::sentinel_t<T>>;

   The common_range concept is a refinement of range for which std::ranges::begin() and
   std::ranges::end() return the same type (e.g. all standard library containers).
