.TH std::basic_string::pop_back 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string::pop_back \- std::basic_string::pop_back

.SH Synopsis
   void pop_back();  \fI(since C++11)\fP

   Removes the last character from the string.

   Equivalent to erase(size()-1, 1), except the behavior is undefined if the string is
   empty.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Complexity

   Constant.

.SH Exceptions

   Does not throw

.SH See also

   push_back appends a character to the end
             \fI(public member function)\fP
   erase     removes characters
             \fI(public member function)\fP
