.TH std::packaged_task::swap 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   void swap( packaged_task& other );  \fI(since C++11)\fP

   Exchanges the shared states and stored tasks of *this and other.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Exceptions
     * 4 See also

.SH Parameters

   other - packaged task whose state to swap with

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept

.SH See also

   std::swap(std::packaged_task) specializes the std::swap algorithm
   \fI(C++11)\fP                       \fI(function template)\fP
