.TH std::tm 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::tm \- std::tm

.SH Synopsis
   Defined in header <ctime>
   struct tm;

   Structure holding a calendar date and time broken down into its components.

.SH Member objects

                seconds after the minute –
                [0, 61]
   int tm_sec   \fI(until C++11)\fP
                [0, 60]
                \fI(since C++11)\fP^[note 1]
                \fI(public member object)\fP
   int tm_min   minutes after the hour – [0, 59]
                \fI(public member object)\fP
   int tm_hour  hours since midnight – [0, 23]
                \fI(public member object)\fP
   int tm_mday  day of the month – [1, 31]
                \fI(public member object)\fP
   int tm_mon   months since January – [0, 11]
                \fI(public member object)\fP
   int tm_year  years since 1900
                \fI(public member object)\fP
   int tm_wday  days since Sunday – [0, 6]
                \fI(public member object)\fP
   int tm_yday  days since January 1 – [0, 365]
                \fI(public member object)\fP
                Daylight Saving Time flag. The value is positive if DST is in effect,
   int tm_isdst zero if not and negative if no information is available
                \fI(public member object)\fP

.SH Notes

   The Standard mandates only the presence of the aforementioned members in either
   order. The implementations usually add more data-members to this structure.

    1. ↑ Range allows for a positive leap second. Two leap seconds in the same minute
       are not allowed (the range 0..61 was a defect introduced in C89 and corrected in
       C99)

.SH Example

   Show the start of calendar time.


// Run this code

 #include <ctime>
 #include <iostream>

 int main()
 {
     std::tm start{};
     start.tm_mday = 1;

     std::mktime(&start);
     std::cout << std::asctime(&start)
               << "sizeof(std::tm) = "
               << sizeof(std::tm) << '\\n';
 }

.SH Possible output:

 Mon Jan  1 00:00:00 1900
 sizeof(std::tm) = 56

.SH See also

   localtime converts time since epoch to calendar time expressed as local time
             \fI(function)\fP
             converts time since epoch to calendar time expressed as Universal
   gmtime    Coordinated Time
             \fI(function)\fP
