.TH std::basic_string::get_allocator 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string::get_allocator \- std::basic_string::get_allocator

.SH Synopsis
   allocator_type get_allocator() const;

   Returns the allocator associated with the string.

.SH Parameters

   \fI(none)\fP

.SH Return value

   the associated allocator

.SH Complexity

   Constant

.SH See also

   allocator        the default allocator
                    \fI(class template)\fP 
   allocator_traits provides information about allocator types
   \fI(C++11)\fP          \fI(class template)\fP 
   uses_allocator   checks if the specified type supports uses-allocator construction
   \fI(C++11)\fP          \fI(class template)\fP 
