.TH std::function_ref::operator() 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::function_ref::operator() \- std::function_ref::operator()

.SH Synopsis
   R operator()( Args... args ) const noexcept(/*noex*/);  (since C++26)

   Invokes the stored thunk-ptr with bound-entity as its first parameter and the rest
   of the parameters args. The /*noex*/ part of operator() is identical to those of the
   template parameter of std::function_ref.

   Equivalent to return thunk-ptr(bound-entity, std::forward<Args>(args)...);.

.SH Parameters

   args - rest parameters to pass to the stored thunk-ptr

.SH Return value

   thunk-ptr(bound-entity, std::forward<Args>(args)...).

.SH Exceptions

   Propagates the exception thrown by the underlying function call.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator() invokes the target
              \fI(public member function of std::function<R(Args...)>)\fP
   operator() calls the stored function
              \fI(public member function of std::reference_wrapper<T>)\fP

.SH Category:
     * Todo no example
