.TH std::basic_istringstream::operator= 3 "Nov 25 2015" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_istringstream::operator= \- std::basic_istringstream::operator=

.SH Synopsis
   basic_istringstream& operator=( basic_istringstream&& other );  \fI(since C++11)\fP

   Moves the string stream. The source stream becomes of invalid state after the
   operation.

.SH Parameters

   other - string stream to move. other becomes of invalid state after the operation.

.SH Return value

   *this

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   swap    swaps two string streams
   \fI(C++11)\fP \fI(public member function)\fP 

.SH Category:

     * Todo no example
