.TH std::Semiregular 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::Semiregular \- std::Semiregular

.SH Synopsis
   Defined in header <concepts>
   template <class T>
   concept Semiregular = std::Copyable<T> &&                              \fI(since C++20)\fP
   std::DefaultConstructible<T>;

   The Semiregular concept specifies that a type is both copyable and default
   constructible. It is satisfied by types that behave similarly to built-in types like
   int, except that they need not support comparison with ==.
