.TH std::isunordered 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cmath>
   bool isunordered( float x, float y );              \fI(since C++11)\fP
   bool isunordered( double x, double y );            \fI(since C++11)\fP
   bool isunordered( long double x, long double y );  \fI(since C++11)\fP

   Determines if the floating point numbers x and y are unordered, that is, one or both
   are NaN and thus cannot be meaningfully compared with each other.

.SH Parameters

   x - floating point value
   y - floating point value

.SH Return value

   true if either x or y is NaN, false otherwise

.SH See also

   fpclassify categorizes the given floating point value
   \fI(C++11)\fP    \fI(function)\fP
   isnan      checks if the given number is NaN
   \fI(C++11)\fP    \fI(function)\fP
