.TH std::basic_streambuf::showmanyc 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   protected:
   virtual std::streamsize showmanyc();

   Estimates the number of characters available for input in the associated character
   sequence. underflow() is guaranteed not to return Traits::eof() until at least that
   many characters are extracted.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Example
     * 4 See also

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of characters that are certainly available in the associated character
   sequence, or -1 if showmanyc can determine, without blocking, that no characters are
   available. If showmanyc returns -1, underflow() and uflow() will definitely return
   Traits::eof.

   The base class version returns 0, which has the meaning of "unsure if there are
   characters available in the associated sequence".

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   in_avail  obtains the number of characters immediately available in the get area
             \fI(public member function)\fP
   showmanyc optionally provides the number of characters available for input from the
   \fB[virtual]\fP file
             \fI(virtual protected member function of std::basic_filebuf)\fP

.SH Category:

     * Todo no example
