.TH std::function::~function 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::function::~function \- std::function::~function

.SH Synopsis
   ~function();  \fI(since C++11)\fP

   Destroys the std::function instance. If the std::function is not empty, its target
   is destroyed also.
