.TH std::hash(std::string,std::wstring,std::u16string,std::u32string) 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <string>
   template<> struct hash<std::string>;

   template<> struct hash<std::wstring>;    \fI(since C++11)\fP
   template<> struct hash<std::u16string>;

   template<> struct hash<std::u32string>;

   The template specializations of std::hash for the various string classes allow users
   to obtain hashes of strings.

.SH Example

   The following code shows one possible output of a hash function used on a string:

   
// Run this code

 #include <iostream>
 #include <string>
 #include <functional>

 int main()
 {
     std::string s = "Stand back! I've got jimmies!";
     std::hash<std::string> hash_fn;

     size_t hash = hash_fn(s);

     std::cout << hash << '\\n';
 }

.SH Output:

 325378910

.SH See also

   hash    hash function object
   \fI(C++11)\fP \fI(class template)\fP
