.TH std::chrono::year::is_leap 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year::is_leap \- std::chrono::year::is_leap

.SH Synopsis
   constexpr bool is_leap() const noexcept;  \fI(since C++20)\fP

   Determines if *this represents a leap year in the proleptic Gregorian calendar.

   *this represents a leap year if the stored year value

     * is divisible by 4 and not divisible by 100; or
     * is divisible by 400.

.SH Return value

   true if *this represents a leap year, otherwise false.

.SH Example


// Run this code

 #include <iostream>
 #include <chrono>

 int main()
 {
     using namespace std::chrono;

     for (const year y : {2020y, 2021y, 2000y, 3000y}) {
         std::cout
             << static_cast<int>(y) << " is "
             << (y.is_leap() ? "" : "not ")
             << "a leap year\\n";
     }
 }

.SH Output:

 2020 is a leap year
 2021 is not a leap year
 2000 is a leap year
 3000 is not a leap year
