.TH std::chrono::operator<<(std::chrono::weekday) 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator<<(std::chrono::weekday) \- std::chrono::operator<<(std::chrono::weekday)

.SH Synopsis
   template <class CharT, class Traits>

   std::basic_ostream<CharT, Traits>&                                     \fI(since C++20)\fP

   operator<<(std::basic_ostream<CharT, Traits>& os, const
   std::chrono::weekday& wd);

   If !wd.ok(), equivalent to os << unsigned(wd) << " is not a valid weekday";.
   Otherwise, forms a std::basic_string<CharT> s consisting of the abbreviated weekday
   name for the weekday represented by wd, determined using the locale associated with
   os, and inserts s into os.

.SH Return value

   os.

.SH Notes

   This operator<< is primarily intended for debugging use. For control over
   formatting, use std::chrono::format.

.SH See also

   format    formats a streamable chrono object for insertion
   (C++20)   \fI(function template)\fP
   to_stream outputs a weekday into a stream according to the provided format
             \fI(function template)\fP
