.TH std::basic_string::back 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string::back \- std::basic_string::back

.SH Synopsis
   CharT& back();             \fB(1)\fP (constexpr since C++20)
   const CharT& back() const; \fB(2)\fP (constexpr since C++20)

   Returns reference to the last character in the string. The behavior is undefined if
   empty() is true.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reference to the last character, equivalent to operator[](size() - 1).

.SH Complexity

   Constant.

.SH Notes

   In libstdc++, back() is not available in C++98 mode.

.SH Example


// Run this code

 #include <iostream>
 #include <string>

 int main()
 {
     std::string s("Exemplary");
     char& back1 = s.back();
     back1 = 's';
     std::cout << s << '\\n'; // "Exemplars"

     std::string const c("Exemplary");
     char const& back2 = c.back();
     std::cout << back2 << '\\n'; // 'y'
 }

.SH Output:

 Exemplars
 y

   Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to              Behavior as published               Correct behavior
   LWG 534 C++98      std::basic_string did not have the member        added
                      function back()

.SH See also

   front accesses the first character
   (DR*) \fI(public member function)\fP
   back  accesses the last character
         \fI(public member function of std::basic_string_view<CharT,Traits>)\fP
