.TH std::regex_token_iterator::operator*,operator-> 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::regex_token_iterator::operator*,operator-> \- std::regex_token_iterator::operator*,operator->

.SH Synopsis
   const value_type& operator*() const;   \fI(since C++11)\fP
   const value_type* operator->() const;  \fI(since C++11)\fP

   Returns a pointer or reference to the current match.

   The behavior is undefined if the iterator is end-of-sequence iterator.

.SH Return value

   A pointer or reference to the current match.
