.TH std::unique_ptr::get 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   pointer get() const;  \fI(since C++11)\fP

   Returns a pointer to the managed object or nullptr if no object is owned.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Pointer to the managed object or nullptr if no object is owned.

.SH Exceptions

   noexcept specification:
   noexcept

.SH Example

   
// Run this code

 #include <iostream>
 #include <string>
 #include <memory>

 int main()
 {
     std::unique_ptr<std::string> s_p(new std::string("Hello, world!"));
     std::string *s = s_p.get();
     std::cout << *s << '\\n';
 }

.SH Output:

 Hello, world!

.SH See also

   release returns a pointer to the managed object and releases the ownership
           \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept
