.TH std::numeric_limits::has_denorm 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::numeric_limits::has_denorm \- std::numeric_limits::has_denorm

.SH Synopsis
   static const std::float_denorm_style has_denorm;      \fI(until C++11)\fP
   static constexpr std::float_denorm_style has_denorm;  \fI(since C++11)\fP
                                                         (deprecated in C++23)

   The value of std::numeric_limits<T>::has_denorm identifies the floating-point types
   that support subnormal values.

.SH Standard specializations

   T                                value of std::numeric_limits<T>::has_denorm
   /* non-specialized */            std::denorm_absent
   bool                             std::denorm_absent
   char                             std::denorm_absent
   signed char                      std::denorm_absent
   unsigned char                    std::denorm_absent
   wchar_t                          std::denorm_absent
   char8_t \fI(since C++20)\fP            std::denorm_absent
   char16_t \fI(since C++11)\fP           std::denorm_absent
   char32_t \fI(since C++11)\fP           std::denorm_absent
   short                            std::denorm_absent
   unsigned short                   std::denorm_absent
   int                              std::denorm_absent
   unsigned int                     std::denorm_absent
   long                             std::denorm_absent
   unsigned long                    std::denorm_absent
   long long \fI(since C++11)\fP          std::denorm_absent
   unsigned long long \fI(since C++11)\fP std::denorm_absent
   float                            usually std::denorm_present
   double                           usually std::denorm_present
   long double                      usually std::denorm_present

.SH See also

   denorm_min         returns the smallest positive subnormal value of the given
   \fB[static]\fP           floating-point type
                      \fI(public static member function)\fP
   float_denorm_style indicates floating-point denormalization modes
                      \fI(enum)\fP
