.TH std::experimental::reflect::GlobalScope 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::reflect::GlobalScope \- std::experimental::reflect::GlobalScope

.SH Synopsis
   Defined in header <experimental/reflect>
   template< class T >                                     (reflection TS)
   concept GlobalScope = Namespace<T> && /* see below */;

   The GlobalScope concept is satisfied if and only if T reflects the global namespace
   (Note: Any such T does not satisfy ScopeMember).

.SH Example

    This section is incomplete
    Reason: examples

.SH See also

    This section is incomplete
    Reason: templatization

.SH Category:
     * Todo with reason
