.TH std::chrono::operator<<(std::chrono::month_weekday_last) 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator<<(std::chrono::month_weekday_last) \- std::chrono::operator<<(std::chrono::month_weekday_last)

.SH Synopsis
   template <class CharT, class Traits>

   std::basic_ostream<CharT, Traits>&                                     \fI(since C++20)\fP

   operator<<(std::basic_ostream<CharT, Traits>& os, const
   std::chrono::month_weekday_last& mwdl);

   Outputs a textual representation of mwdl into os, as if by os << mwdl.month() << '/'
   << mwdl.weekday_last();

.SH Return value

   os.

.SH Notes

   This operator<< is primarily intended for debugging use. When used with non-default
   stream flags, the output may be surprising:

 using namespace std::chrono;
 auto mwdl = February/Sunday[last];
 std::cout.width\fB(10)\fP;
 std::cout.fill('-');
 std::cout << std::left << mwdl; // may output "Feb-------/Sun[last]"
