.TH std::istreambuf_iterator<CharT,Traits>::istreambuf_iterator 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::istreambuf_iterator<CharT,Traits>::istreambuf_iterator \- std::istreambuf_iterator<CharT,Traits>::istreambuf_iterator

.SH Synopsis
   istreambuf_iterator() throw();                                         \fI(until C++11)\fP
   constexpr istreambuf_iterator() noexcept;                              \fI(since C++11)\fP
   istreambuf_iterator( std::basic_istream<CharT,Traits>& is )        \fB(2)\fP
   noexcept;
   istreambuf_iterator( std::basic_streambuf<CharT,Traits>* s )   \fB(1)\fP \fB(3)\fP
   noexcept;
   istreambuf_iterator( const /* proxy */& p ) noexcept;              \fB(4)\fP
   istreambuf_iterator( const istreambuf_iterator& ) noexcept =       \fB(5)\fP \fI(since C++11)\fP
   default;

   1) Constructs an end-of-stream iterator.
   2) Initializes the iterator and stores the value of is.rdbuf() in a data member. If
   is.rdbuf() is null, then end-of-stream iterator is constructed.
   3) Initializes the iterator and stores the value of s in a data member. If s is
   null, then end-of-stream iterator is constructed.
   4) Effectively call \fB(3)\fP with the streambuf_type* pointer p holds.
   5) The copy constructor is explicitly defaulted.

.SH Parameters

   is - stream to obtain the stream buffer from
   s  - stream buffer to initialize the iterator with
   p  - object with implementation defined proxy type
