.TH std::atomic_notify_one 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::atomic_notify_one \- std::atomic_notify_one

.SH Synopsis
   Defined in header <atomic>
   template< class T >
   void atomic_notify_one( std::atomic<T>* object );           \fI(since C++20)\fP
   template< class T >
   void atomic_notify_one( volatile std::atomic<T>* object );

   Performs atomic notifying operations.

   If there is a thread blocked in atomic waiting operation (i.e. std::atomic_wait(),
   std::atomic_wait_explicit(), or std::atomic::wait()) on *object, then unblocks at
   least one such thread; otherwise does nothing.

   Equivalent to object->notify_one().

.SH Parameters

   object - pointer to the atomic object to notify

.SH Return value

   \fI(none)\fP

.SH Notes

   This form of change-detection is often more efficient than simple polling or pure
   spinlocks.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   notify_one           notifies at least one thread waiting on the atomic object
   (C++20)              \fI(public member function of std::atomic<T>)\fP
   notify_all           notifies all threads blocked waiting on the atomic object
   (C++20)              \fI(public member function of std::atomic<T>)\fP
   atomic_notify_all    notifies all threads blocked in atomic_wait
   (C++20)              \fI(function template)\fP
   atomic_wait
   atomic_wait_explicit blocks the thread until notified and the atomic value changes
   (C++20)              \fI(function template)\fP
   (C++20)
