.TH std::basic_stringstream::operator= 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_stringstream::operator= \- std::basic_stringstream::operator=

.SH Synopsis
   basic_stringstream& operator=( basic_stringstream&& other );  \fI(since C++11)\fP

   Move assigns the string stream other to *this, effectively move-assigning both the
   std::basic_iostream base class and the associated std::basic_stringbuf.

   Note that the base class move assignment swaps all stream state variables (except
   for rdbuf) between *this and other.

.SH Parameters

   other - string stream to move from

.SH Return value

   *this

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   swap      swaps two string streams
   \fI(C++11)\fP   \fI(public member function)\fP 
   operator= assigns a basic_stringbuf object
   \fI(C++11)\fP   \fI(public member function of std::basic_stringbuf)\fP 
   operator= move-assigns another basic_iostream
   \fI(C++11)\fP   \fI(protected member function)\fP 

.SH Category:

     * Todo no example
