.TH std::stack::size 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::stack::size \- std::stack::size

.SH Synopsis
   size_type size() const;

   Returns the number of elements in the underlying container, that is, c.size().

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of elements in the container.

.SH Complexity

   Constant.

.SH See also

   empty checks whether the underlying container is empty
         \fI(public member function)\fP 
