.TH std::priority_queue<T,Container,Compare>::~priority_queue 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::priority_queue<T,Container,Compare>::~priority_queue \- std::priority_queue<T,Container,Compare>::~priority_queue

.SH Synopsis
   ~priority_queue();

   Destructs the container adaptor. The destructors of the elements are called and the
   used storage is deallocated. Note, that if the elements are pointers, the pointed-to
   objects are not destroyed.

.SH Complexity

   Linear in the size of the container adaptor.
