.TH std::stack::empty 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::stack::empty \- std::stack::empty

.SH Synopsis
   bool empty() const;                \fI(until C++20)\fP
   [[nodiscard]] bool empty() const;  \fI(since C++20)\fP

   Checks if the underlying container has no elements, i.e. whether c.empty().

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if the underlying container is empty, false otherwise

.SH Complexity

   Constant

.SH See also

   size returns the number of elements
        \fI(public member function)\fP 
