.TH std::move_iterator::base 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::move_iterator::base \- std::move_iterator::base

.SH Synopsis
   Iterator base() const;            \fI(until C++17)\fP
   constexpr Iterator base() const;  \fI(since C++17)\fP

   Returns the underlying base iterator.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The underlying iterator.

.SH Exceptions

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator*  accesses the pointed-to element
   operator-> \fI(public member function)\fP

.SH Category:

     * Todo no example
