.TH std::auto_ptr::reset 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::auto_ptr::reset \- std::auto_ptr::reset

.SH Synopsis
   void reset( T* p = 0 ) throw();  (deprecated in C++11)
                                    (removed in C++17)

   Replaces the held pointer by p. If the currently held pointer is not null pointer,
   delete get() is called.

.SH Parameters

   p - a pointer to an object to manage

.SH Return value

   \fI(none)\fP

.SH See also

   release releases ownership of the managed object
           \fI(public member function)\fP
