.TH std::experimental::ranges::Readable 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::Readable \- std::experimental::ranges::Readable

.SH Synopsis
   Defined in header <experimental/ranges/iterator>
   template < class In >

   concept bool Readable =
     requires {
       typename ranges::value_type_t<In>;
       typename ranges::reference_t<In>;
       typename ranges::rvalue_reference_t<In>;
     } &&                                                                   (ranges TS)
     ranges::CommonReference<ranges::reference_t<In>&&,
   ranges::value_type_t<In>&> &&
     ranges::CommonReference<ranges::reference_t<In>&&,
   ranges::rvalue_reference_t<In>&&> &&

     ranges::CommonReference<ranges::rvalue_reference_t<In>&&, const
   ranges::value_type_t<In>&>;

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
