.TH std::reverse_iterator::operator*,-> 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::reverse_iterator::operator*,-> \- std::reverse_iterator::operator*,->

.SH Synopsis
   reference operator*() const;                   \fI(until C++17)\fP
   constexpr reference operator*() const; \fB(1)\fP     \fI(since C++17)\fP
   pointer operator->() const;                \fB(2)\fP               \fI(until C++17)\fP
   constexpr pointer operator->() const;                        \fI(since C++17)\fP

   Returns a reference or pointer to the element previous to current.

   1) Equivalent to Iterator tmp = current; return *--tmp;
   2) Equivalent to std::addressof(operator*()).

.SH Parameters

   \fI(none)\fP

.SH Return value

   Reference or pointer to the element previous to current.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   operator[] accesses an element by index
              \fI(public member function)\fP

.SH Category:

     * Todo no example
