.TH std::regex_token_iterator::operator= 3 "Nov 16 2016" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::regex_token_iterator::operator= \- std::regex_token_iterator::operator=

.SH Synopsis
   regex_token_iterator& operator=( const regex_token_iterator& other );  \fI(since C++11)\fP

   Assigns the contents of other.

.SH Parameters

   other - regex iterator to assign

.SH Return value

   *this.
