.TH std::experimental::ranges::WeaklyEqualityComparable 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::WeaklyEqualityComparable \- std::experimental::ranges::WeaklyEqualityComparable

.SH Synopsis
   Defined in header <experimental/ranges/concepts>
   template <class T, class U>

   concept bool WeaklyEqualityComparable() {
       return requires(const T& t, const U& u) {
                  { t == u } -> ranges::Boolean;
                  { u == t } -> ranges::Boolean;     (ranges TS)
                  { t != u } -> ranges::Boolean;
                  { u != t } -> ranges::Boolean;
       };

   }

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
