.TH std::experimental::optional::operatorbool 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   constexpr explicit operator bool() const;  (library fundamentals TS)

   Checks whether *this contains a value.

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if *this contains a value, false if *this does not contain a value.

.SH Exceptions

   noexcept specification:
   noexcept
.SH Category:

     * unconditionally noexcept
