.TH std::mask_array::mask_array 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::mask_array::mask_array \- std::mask_array::mask_array

.SH Synopsis
   private:                                       \fI(until C++11)\fP
   mask_array();
   public:                                \fB(1)\fP     \fI(since C++11)\fP
   mask_array() = delete;
   public:                                    \fB(2)\fP
   mask_array( const mask_array& other );

   1) The default constructor is
   declared private and not defined
   \fI(until C++11)\fP
   explicitly defined as deleted
   \fI(since C++11)\fP: mask_array is not DefaultConstructible.
   2) Constructs a mask_array from another mask_array other.

.SH Parameters

   other - mask_array to initialize with

   Defect reports

   The following behavior-changing defect reports were applied retroactively to
   previously published C++ standards.

     DR    Applied to      Behavior as published       Correct behavior
   LWG 253 C++98      the copy constructor was private made public
