.TH std::pmr::memory_resource::is_equal 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::pmr::memory_resource::is_equal \- std::pmr::memory_resource::is_equal

.SH Synopsis
   bool is_equal( const memory_resource& other ) const noexcept;  \fI(since C++17)\fP

   Compares *this for equality with other. Two memory_resources compare equal if and
   only if memory allocated from one memory_resource can be deallocated from the other
   and vice versa.

   Equivalent to return do_is_equal(other);.

.SH See also

   do_is_equal compare for equality with another memory_resource
   \fB[virtual]\fP   (virtual private member function)
