.TH std::experimental::filesystem::file_status::permissions 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   perms permissions() const;      \fB(1)\fP (filesystem TS)
   void permissions( perms perm ); \fB(2)\fP (filesystem TS)

   Accesses the file permissions information.

   1) Returns file permissions information.
   2) Sets file type to perm.

.SH Parameters

   perm - file permissions to set to

.SH Return value

   1) File permissions information.
   2) \fI(none)\fP

.SH Exceptions

   noexcept specification:  
   noexcept
     
