.TH std::experimental::ranges::Writable 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::ranges::Writable \- std::experimental::ranges::Writable

.SH Synopsis
   Defined in header <experimental/ranges/iterator>
   template < class Out, class T >

   concept bool Writable =
     requires(Out&& o, T&& t) {
       *o = std::forward<T>(t);
       *std::forward<Out>(o) = std::forward<T>(t);
       const_cast<const ranges::reference_t<Out>&&>(*o) =
         std::forward<T>(t);                                                (ranges TS)
       const_cast<const ranges::reference_t<Out>&&>(*std::forward<Out>(o))
   =
         std::forward<T>(t);
     };

     /* none of the four expressions above are required to be
   equality-preserving */

    This section is incomplete
    Reason: add description and extra caveats

.SH Category:

     * Todo with reason
