.TH std::asinh(std::complex) 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <complex>
   template< class T >                       \fI(since C++11)\fP
   complex<T> asinh( const complex<T>& z );

   Computes complex area hyperbolic sine of a complex value z.

.SH Parameters

   z - complex value

.SH Return value

   Complex area hyperbolic sine of z

.SH See also

   sin(std::complex)  computes sine of a complex number (sin(z))
                      \fI(function template)\fP
   sinh(std::complex) computes hyperbolic sine of a complex number (sh(z))
                      \fI(function template)\fP
   asin(std::complex) computes arc sine of a complex number (arcsin(z))
   \fI(C++11)\fP            \fI(function template)\fP
