.TH std::unique_lock::operatorbool 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   explicit operator bool() const;  \fI(since C++11)\fP

   Checks whether *this owns a locked mutex or not. Effectively calls owns_lock().

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Exceptions
     * 4 See also

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if *this has an associated mutex and has acquired ownership of it, false
   otherwise.

.SH Exceptions

   noexcept specification:
   noexcept

.SH See also

   owns_lock tests whether the lock owns its associated mutex
             \fI(public member function)\fP
