.TH std::exponential_distribution<RealType>::lambda 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::exponential_distribution<RealType>::lambda \- std::exponential_distribution<RealType>::lambda

.SH Synopsis
   RealType lambda() const;  \fI(since C++11)\fP

   Returns the λ distribution parameter the distribution was constructed with. The
   parameter defines the rate of events, per unit. The default value is 1.0.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Floating point value identifying the rate of events per unit

.SH See also

   param gets or sets the distribution parameter object
         \fI(public member function)\fP
