.TH std::unordered_map::bucket 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_map::bucket \- std::unordered_map::bucket

.SH Synopsis
   size_type bucket( const Key& key ) const;  \fI(since C++11)\fP

   Returns the index of the bucket for key key. Elements (if any) with keys equivalent
   to key are always found in this bucket. The returned value is valid only for
   instances of the container for which bucket_count() returns the same value.

   The behavior is undefined if bucket_count() is zero.

.SH Parameters

   key - the value of the key to examine

.SH Return value

   Bucket index for the key key.

.SH Complexity

   Constant.

.SH See also

   bucket_size returns the number of elements in specific bucket
               \fI(public member function)\fP 
