.TH std::bad_exception::operator= 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::bad_exception::operator= \- std::bad_exception::operator=

.SH Synopsis
   bad_exception& operator=( const bad_exception& other );

   Assigns the contents of other.

.SH Parameters

   other - another bad_exception object to assign

.SH Return value

   *this.

.SH Exceptions

   noexcept specification:
   noexcept
.SH Category:

     * unconditionally noexcept

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
