.TH std::forward_list::emplace_after 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::forward_list::emplace_after \- std::forward_list::emplace_after

.SH Synopsis
   template< class... Args >                                      \fI(since C++11)\fP
   iterator emplace_after( const_iterator pos, Args&&... args );

   Inserts a new element into a position after the specified position in the container.
   The element is constructed in-place, i.e. no copy or move operations are performed.
   The constructor of the element is called with exactly the same arguments, as
   supplied to the function.

   No iterators or references are invalidated.

.SH Parameters

   pos  - iterator after which the new element will be constructed
   args - arguments to forward to the constructor of the element

.SH Return value

   iterator to the new element.

.SH Complexity

   Constant.

.SH Exceptions

   If an exception is thrown (e.g. by the constructor), the container is left
   unmodified, as if this function was never called \fI(strong exception guarantee)\fP.

.SH See also

   insert_after inserts elements after an element
                \fI(public member function)\fP 
