.TH std::chrono::leap::date 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::leap::date \- std::chrono::leap::date

.SH Synopsis
   constexpr std::chrono::sys_seconds date() const noexcept;

   Obtains the date and time of the leap second insertion.

.SH Return value

   A std::chrono::sys_seconds representing the date and time at which the leap second
   was inserted.
