.TH std::remove 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cstdio>
   int remove( const char *fname );

   Deletes the file identified by character string pointed to by fname.

.SH Contents

     • 1 Parameters
     • 2 Return value
     • 3 Notes
     • 4 Example
     • 5 See also

.SH Parameters

   fname - pointer to a null-terminated string containing the path identifying the file
           to delete

.SH Return value

   0 upon success or non-zero value on error.

.SH Notes

   In POSIX the behavior for file types other than regular files is unspecified.

.SH Example

   
// Run this code

 #include <cstdio>
 #include <iostream>
  
 int main()
 {
     const char* file_name = "C:\\\\file.txt";
     int ret_code = std::remove(file_name);
     if (ret_code == 0) {
         std::cout << "File was successfully deleted\\n";
     } else {
         std::cerr << "Error during the deletion: " << ret_code << '\\n';
     }
 }

.SH Possible output:

 Error during the deletion: 1

.SH See also

   rename renames a file
          \fI(function)\fP
   C documentation for
   remove
