.TH std::multimap::size 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::multimap::size \- std::multimap::size

.SH Synopsis
   size_type size() const;

   Returns the number of elements in the container, i.e. std::distance(begin(), end()).

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of elements in the container.

.SH Exceptions

   \fI(none)\fP                    \fI(until C++11)\fP
   noexcept specification:  
   noexcept                  \fI(since C++11)\fP
     

.SH Complexity

   Constant.

.SH Example

   

   The following code uses size to display the number of elements in a std::multimap:

   
// Run this code

 #include <map>
 #include <iostream>
  
 int main()
 {
     std::multimap<int,char> nums {{1, 'a'}, {3, 'b'}, {5, 'c'}, {7, 'd'}};
  
     std::cout << "nums contains " << nums.size() << " elements.\\n";
 }

.SH Output:

 nums contains 4 elements.

.SH See also

   empty    checks whether the container is empty
            \fI(public member function)\fP 
   max_size returns the maximum possible number of elements
            \fI(public member function)\fP 
