.TH std::weak_ptr::swap 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   void swap( weak_ptr& r );  \fI(since C++11)\fP

   Exchanges the contents of *this and r

.SH Parameters

   r - smart pointer to exchange the contents with

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:  
   noexcept
     
