.TH std::ranges::join_with_view::join_with_view 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::join_with_view::join_with_view \- std::ranges::join_with_view::join_with_view

.SH Synopsis
   join_with_view()

     requires std::default_initializable<V> &&                        \fB(1)\fP (since C++23)

              std::default_initializable<Pattern> = default;
   constexpr explicit join_with_view( V base, Pattern pattern );      \fB(2)\fP (since C++23)
   template< ranges::input_range R >

     requires std::constructible_from<V, views::all_t<R>> &&
              std::constructible_from<Pattern,
                  ranges::single_view<ranges::range_value_t<
                                                                      \fB(3)\fP (since C++23)
   ranges::range_reference_t<V>>>>
   constexpr explicit
       join_with_view( R&& r, ranges::range_value_t<

                                  ranges::range_reference_t<V>> e );

   Constructs a join_with_view.

   1) Default constructor. Value-initializes the underlying view and the pattern.
   2) Initializes the underlying view with std::move(base) and the stored pattern with
   std::move(pattern).
   3) Initializes the underlying view with views::all(std::forward<R>(r)) and the
   stored pattern with views::single(std::move(e)).

.SH Parameters

   base    - a view of ranges to be flattened
   pattern - view to be used as the delimiter
   e       - element to be used as the delimiter

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
