.TH std::filesystem::recursive_directory_iterator::pop 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::recursive_directory_iterator::pop \- std::filesystem::recursive_directory_iterator::pop

.SH Synopsis
   void pop();  \fI(since C++17)\fP

   Moves the iterator one level up in the directory hierarchy.

   If the parent directory is outside directory hierarchy that is iterated on (i.e.
   depth() == 0), sets *this to an end directory iterator.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP

.SH Exceptions

    This section is incomplete

.SH Category:

     * Todo without reason
