.TH std::get_new_handler 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <new>
   std::new_handler get_new_handler();  \fI(since C++11)\fP

   Returns the currently installed new-handler, which may be a null pointer.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The currently installed new-handler, which may be a null pointer value.

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH See also

   operator new    allocation functions
   operator new[]  \fI(function)\fP 
   set_new_handler registers a new handler
                   \fI(function)\fP 
   new_handler     function pointer type of the new handler
                   \fI(typedef)\fP 
