.TH std::logical_or 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::logical_or \- std::logical_or

.SH Synopsis
   Defined in header <functional>
   template<>                      \fI(since C++14)\fP
   class logical_or<void>;

   std::logical_or<void> is a specialization of std::logical_or with parameter and
   return type deduced.

.SH Member functions

   operator() applies operator|| to lhs and rhs
              \fI(public member function)\fP

std::logical_or<void>::operator()

   template< class T, class U >

   constexpr auto operator()( T&& lhs, U&& rhs ) const

       -> decltype(std::forward<T>(lhs) || std::forward<U>(rhs));

   Returns the result of std::forward<T>(lhs) || std::forward<U>(rhs).

.SH Parameters

   lhs, rhs - values to logical OR

.SH Return value

   std::forward<T>(lhs) || std::forward<U>(rhs).

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
