.TH std::error_code::default_error_condition 3 "Nov 25 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_code::default_error_condition \- std::error_code::default_error_condition

.SH Synopsis
   std::error_condition default_error_condition() const;  \fI(since C++11)\fP

   Returns the default error condition for the current error value.

   Equivalent to category().default_error_condition(value()).

.SH Parameters

   \fI(none)\fP

.SH Return value

   The default error condition for the current error value.

.SH Exceptions

   noexcept specification:  
   noexcept
     
.SH Category:

     * unconditionally noexcept
