.TH std::swap(std::function) 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::swap(std::function) \- std::swap(std::function)

.SH Synopsis
   template< class R, class... Args >
   void swap( function<R(Args...)> &lhs, function<R(Args...)> &rhs );

   Overloads the std::swap algorithm for std::function. Exchanges the state of lhs with
   that of rhs. Effectively calls lhs.swap(rhs).

.SH Parameters

   lhs, rhs - polymorphic function wrappers whose states to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   \fI(none)\fP                    \fI(until C++17)\fP
   noexcept specification:  
   noexcept                  \fI(since C++17)\fP
     

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   swap swaps the contents
        \fI(public member function)\fP 

   Categories:

     * unconditionally noexcept
     * Todo no example

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
