.TH std::chrono::year_month_day 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year_month_day \- std::chrono::year_month_day

.SH Synopsis
   Defined in header <chrono>
   class year_month_day;       \fI(since C++20)\fP

   The class year_month_day represents a specific year, month, and day. It is a
   field-based time point, with a resolution of std::chrono::days. std::chrono::years-
   and std::chrono::months-oriented arithmetic are supported directly. An implicit
   conversion to and from std::chrono::sys_days allows std::chrono::days-oriented
   arithmetic to be performed efficiently.

   year_month_day is a TriviallyCopyable StandardLayoutType.

.SH Member functions

   constructor         constructs a year_month_day
                       \fI(public member function)\fP 
   operator+=          modifies the time point by some number of months or years
   operator-=          \fI(public member function)\fP 
   year                accesses the year, month, and day stored in this object
   month               \fI(public member function)\fP 
   day
   operator sys_days   converts to a std::chrono::time_point
   operator local_days \fI(public member function)\fP 
   ok                  checks if the year_month_day represents a valid date
                       \fI(public member function)\fP 

   Nonmember functions

   operator==
   operator!=
   operator<   compares two year_month_day objects
   operator<=  \fI(function)\fP 
   operator>
   operator>=
   operator+   adds or subtracts a year_month_day and some number of years or months
   operator-   \fI(public member function)\fP 
   operator<<  outputs a year_month_day into a stream
               \fI(function template)\fP 
   to_stream   outputs a year_month_day into a stream according to the provided format
               \fI(function template)\fP 
   from_stream parses a year_month_day from a stream according to the provided format
               \fI(function template)\fP 
