.TH std::unordered_multimap::max_bucket_count 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_multimap::max_bucket_count \- std::unordered_multimap::max_bucket_count

.SH Synopsis
   size_type max_bucket_count() const;  \fI(since C++11)\fP

   Returns the maximum number of buckets the container is able to hold due to system or
   library implementation limitations.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Maximum number of buckets.

.SH Complexity

   Constant.

.SH See also

   bucket_count returns the number of buckets
                \fI(public member function)\fP
