.TH std::raw_storage_iterator::operator= 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   raw_storage_iterator& operator=( const T& el );

   Constructs a value at the location the iterator points to from el.

.SH Parameters

   el - the value to copy

.SH Return value

   *this
