.TH std::pair::swap 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   void swap(pair& other);  \fI(since C++11)\fP

   Swaps first with other.first and second with other.second.

.SH Parameters

   other - pair of values to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept(

   noexcept(std::swap(first, other.first)) &&
   noexcept(std::swap(second, other.second))

   )

.SH Example

   
// Run this code

 #include <iostream>
 #include <utility>
 #include <string>
 int main()
 {
     std::pair<int, std::string> p1, p2;
     p1 = std::make_pair(10, "test");
     p2.swap(p1);
     std::cout << "(" << p2.first << ", " << p2.second << ")\\n";
 }

.SH Output:

 (10, test)

.SH See also

   swap swaps the values of two objects
        \fI(function template)\fP

.SH Category:

     * conditionally noexcept
