.TH std::match_results::size 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   size_type size() const;  \fI(since C++11)\fP

   Returns the number of submatches, i.e. std::distance(begin(), end()).

.SH Contents

     • 1 Parameters
     • 2 Return value
     • 3 Exceptions
     • 4 Complexity
     • 5 See also
     • 6 Example

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of submatches

.SH Exceptions

   noexcept specification:  
   noexcept
     

.SH Complexity

   Constant

.SH See also

.SH Example

   
// Run this code

 #include <iostream>
 #include <regex>
 #include <string>
  
 int main()
 {
     std::regex re("a(a)*b");
     std::string target("aaab");
     std::smatch sm;
  
     std::regex_match(target, sm, re);
     std::cout << sm.size() << '\\n';
 }

.SH Output:

 2
