.TH std::filesystem::directory_entry::is_other 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::directory_entry::is_other \- std::filesystem::directory_entry::is_other

.SH Synopsis
   bool is_other() const;                                \fI(since C++17)\fP
   bool is_other( std::error_code& ec ) const noexcept;

   Checks whether the pointed-to object is an other file (not a regular file, directory
   or symlink). Effectively returns std::filesystem::is_other(status()) or
   std::filesystem::is_other(status(ec)), respectively

.SH Parameters

   ec - out-parameter for error reporting in the non-throwing overload

.SH Return value

   true if the referred-to filesystem object is an other file, false otherwise.

.SH Exceptions

   The overload that does not take a std::error_code& parameter throws filesystem_error
   on underlying OS API errors, constructed with p as the first path argument and the
   OS error code as the error code argument. The overload taking a std::error_code&
   parameter sets it to the OS API error code if an OS API call fails, and executes
   ec.clear() if no errors occur. Any overload not marked noexcept may throw
   std::bad_alloc if memory allocation fails.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   is_other checks whether the argument refers to an other file
   \fI(C++17)\fP  \fI(function)\fP
