.TH std::shared_ptr::~shared_ptr 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   ~shared_ptr();

   If *this owns an object and it is the last shared_ptr owning it, the object is
   destroyed through the owned deleter. Otherwise does nothing.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also


.SH Category:

     • Todo no example
