.TH std::ranges::take_view::size 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::take_view::size \- std::ranges::take_view::size

.SH Synopsis
   constexpr auto size() requires ranges::sized_range<V>;             \fB(1)\fP \fI(since C++20)\fP
   constexpr auto size() const requires ranges::sized_range<const V>; \fB(2)\fP \fI(since C++20)\fP

   Returns the number of elements, which is the smaller of the count passed to the
   constructor and the size of the underlying view.

   Let base_ be the underlying view, count_ be the number passed to the constructor (0
   if default constructed). Equivalent to

 auto n = ranges::size(base_);
 return ranges::min(n, static_cast<decltype(n)>(count_));

.SH Parameters

   \fI(none)\fP

.SH Return value

   The number of elements.

.SH Example


// Run this code

 #include <ranges>
 #include <iostream>

 int main()
 {
     constexpr int arr[] {1, 2, 3};

     for (int i = 0; i != 6; ++i) {
         const auto tv = std::ranges::take_view{arr, i};
         std::cout << tv.size() << ' ';
     }
 }

.SH Output:

 0 1 2 3 3 3
