.TH std::shared_ptr::operator<< 3 "Nov 25 2015" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::shared_ptr::operator<< \- std::shared_ptr::operator<<

.SH Synopsis
   template <class T, class U, class V>
       basic_ostream<U, V>& operator<<(basic_ostream<U, V>& os, const shared_ptr<T>&
   ptr);

   Inserts a shared_ptr<T> into a std::basic_ostream.

   Equivalent to os << ptr.get().

.SH Parameters

   os  - a std::basic_ostream to insert ptr into
   ptr - the data to be inserted into os

.SH Return value

   os

.SH Example

   
// Run this code

 #include <iostream>
 #include <memory>
  
 class Foo {};
  
 int main()
 {
     auto sp = std::make_shared<Foo>();
     std::cout << sp << std::endl;
     std::cout << sp.get() << std::endl;
 }

.SH Possible output:

 0x6d9028
 0x6d9028

.SH See also

   get returns a pointer to the managed object
       \fI(public member function)\fP 
