.TH std::hash<std::type_index> 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <typeindex>
   struct hash<type_index>;       \fI(since C++11)\fP

   The template specialization of std::hash for std::type_index allows users to obtain
   hashes of objects of type std::type_index.

.SH Return value

   Effectively returns the same value as hash_code().

.SH See also

   hash_code returns hashed code
             \fI(public member function)\fP 
