.TH std::error_code::assign 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_code::assign \- std::error_code::assign

.SH Synopsis
   void assign( int val, const error_category& cat ) noexcept;  \fI(since C++11)\fP

   Replaces the contents with error code value val and corresponding category cat.

.SH Parameters

   val - platform-dependent error code value to assign
   cat - error category corresponding to val

.SH Return value

   \fI(none)\fP

.SH See also

   operator= assigns another error code
             \fI(public member function)\fP
