.TH std::chrono::year::is_leap 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year::is_leap \- std::chrono::year::is_leap

.SH Synopsis
   constexpr bool is_leap() const noexcept;  \fI(since C++20)\fP

   Determines if *this represents a leap year in the proleptic Gregorian calendar.

   *this represents a leap year if the stored year value

     * is divisible by 4 and not divisible by 100; or
     * is divisible by 400.

.SH Return value

   true if *this represents a leap year, otherwise false.
