.TH std::shuffle_order_engine::base 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   const Engine& base() const;  \fI(since C++11)\fP

   Returns the underlying engine.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The underlying engine.

.SH Exceptions

   noexcept specification:  
   noexcept
     
