.TH std::basic_regex::imbue 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   locale_type imbue( locale_type loc );  \fI(since C++11)\fP

   Replaces the current locale with loc. The regular expression does not match any
   character sequence after the call.

   Effectively calls traits_i.imbue(loc) where traits_i is a default initialized
   instance of the type Traits stored within the regular expression object.

.SH Contents

     * 1 Parameters
     * 2 Return value
     * 3 Exceptions
     * 4 Example
     * 5 See also

.SH Parameters

   loc - new locale to use

.SH Return value

   The locale before the call to this function. Effectively returns the result of
   expression traits_i.imbue(loc).

.SH Exceptions

   \fI(none)\fP

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   getloc get locale information
          \fI(public member function)\fP

.SH Category:

     * Todo no example
