.TH std::experimental::element_aligned_tag,std::experimental::element_aligned 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::element_aligned_tag,std::experimental::element_aligned \- std::experimental::element_aligned_tag,std::experimental::element_aligned

.SH Synopsis
   Defined in header <experimental/simd>
   struct element_aligned_tag {};                           (parallelism TS v2)
   inline constexpr element_aligned_tag element_aligned{};

   This tag type indicates that the buffer of copy_from and copy_to is aligned to its
   element alignment.

.SH See also

   vector_aligned_tag  tag type that indicates the alignment of the vector type
   vector_aligned      \fI(class)\fP
   (parallelism TS v2)
   overaligned_tag     tag type that indicates the specified alignment
   overaligned         \fI(class template)\fP
   (parallelism TS v2)
