.TH std::ungetwc 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <cwchar>
   wint_t ungetwc( wint_t ch, std::FILE* stream );

   Puts the wide character ch back to the given file stream. Only one wide character
   pushback is guaranteed.

.SH Parameters

   ch     - wide character to be put back
   stream - file stream to put the wide character back to

.SH Return value

   On success ch is returned.

   On failure WEOF is returned and the given stream remains unchanged.

.SH See also

   ungetc puts a character back into a file stream
          \fI(function)\fP
   fgetwc gets a wide character from a file stream
   getwc  \fI(function)\fP
   C documentation for
   ungetwc
