.TH std::ranges::transform_view::iterator::operator* 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::transform_view::iterator::operator* \- std::ranges::transform_view::iterator::operator*

.SH Synopsis
   constexpr decltype(auto) operator*() const;  \fI(since C++20)\fP

   Returns the transformed element.

   Effectively returns std::invoke(*parent_->fun_, *current_), where *parent_->fun_ is
   the transformation function stored in the parent transform_view, and current_ is the
   underlying iterator into V.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The transformed element.

.SH Notes

   operator-> is not provided.

   The behavior is undefined if the pointer to parent transform_view is null (e.g. if
   *this is default constructed), or if the parent transform_view does not hold a
   transformation function (e.g. if the parent transform_view is default constructed,
   and the transformation function is not default constructible).

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:

     * Todo no example
