.TH std::move_sentinel::move_sentinel 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::move_sentinel::move_sentinel \- std::move_sentinel::move_sentinel

.SH Synopsis
   constexpr move_sentinel();                                         \fB(1)\fP \fI(since C++20)\fP
   constexpr explicit move_sentinel( S x );                           \fB(2)\fP \fI(since C++20)\fP
   template< class S2 >

       requires std::convertible_to<const S2&, S>                     \fB(3)\fP \fI(since C++20)\fP

           constexpr move_sentinel( const std::move_sentinel<S2>&
   other );

   Constructs a new sentinel adaptor.

   1) Default constructor. The underlying sentinel is value-initialized.
   2) The underlying sentinel is initialized with x.
   3) The underlying sentinel is initialized with that of other.

.SH Parameters

   x     - sentinel to adapt
   other - sentinel adaptor to copy

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   constructor   constructs a new iterator adaptor
   \fI(C++11)\fP       \fI(public member function of std::move_iterator<Iter>)\fP

.SH Category:
     * Todo no example
