.TH std::undeclare_no_pointers 3 "Sep  4 2015" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   Defined in header <memory>
   void undeclare_no_pointers( char *p, std::size_t n );  \fI(since C++11)\fP

   Unregisters a range earlier registered with std::declare_no_pointers().

.SH Parameters

   p - pointer to the beginning of the range previosly registered with
       std::declare_no_pointers
   n - the number of bytes in the range, same value as previously used with
       std::declare_no_pointers

.SH Return value

   \fI(none)\fP

.SH Exceptions

   None

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   declare_no_pointers declares that a memory area does not contain traceable pointers
   \fI(C++11)\fP             \fI(function)\fP

.SH Category:

     * Todo no example
