.TH std::time_put::time_put 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::time_put::time_put \- std::time_put::time_put

.SH Synopsis
   Defined in header <locale>
   explicit time_put( std::size_t refs = 0 );

   Creates a std::time_put facet and forwards the starting reference count refs to the
   base class constructor, locale::facet::facet().

.SH Parameters

   refs - starting reference count
