.TH std::chrono::time_zone::name 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::time_zone::name \- std::chrono::time_zone::name

.SH Synopsis
   std::string_view name() const noexcept;  \fI(since C++20)\fP

   Obtains the name of this time zone.

.SH Return value

   The name of this time zone (e.g., "America/New_York").
