.TH std::experimental::optional::operator->,std::experimental::optional::operator* 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   constexpr const T* operator->() const; \fB(1)\fP (library fundamentals TS)
   T* operator->();                       \fB(1)\fP (library fundamentals TS)
   constexpr const T& operator*() const;  \fB(2)\fP (library fundamentals TS)
   T& operator*();                        \fB(2)\fP (library fundamentals TS)

   Accesses the contained value.

   1) Returns a pointer to the contained value.
   2) Returns a reference to the contained value.

   The behavior is undefined if *this is in disengaged state.

.SH Parameters

   \fI(none)\fP

.SH Return value

   Pointer or reference to the contained value.

.SH Exceptions

   \fI(none)\fP
