.TH std::stop_token::stop_token 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::stop_token::stop_token \- std::stop_token::stop_token

.SH Synopsis
   stop_token() noexcept;                          \fB(1)\fP \fI(since C++20)\fP
   stop_token( const stop_token& other ) noexcept; \fB(2)\fP \fI(since C++20)\fP
   stop_token( stop_token&& other ) noexcept;      \fB(3)\fP \fI(since C++20)\fP

   Constructs a new stop_token object.

   1) Constructs an empty stop_token with no associated stop-state.
   2) Copy constructor. Constructs a stop_token whose associated stop-state is the same
   as that of other.
   3) Move constructor. Constructs a stop_token whose associated stop-state is the same
   as that of other; other is left empty.

.SH Parameters

   other - another stop_token object to construct this stop_token object with

.SH Postconditions

   1) stop_possible() and stop_requested() are both false.
   2) *this and other share the same associated stop-state and compare equal.
   3) *this has other's previously associated stop-state, and other.stop_possible() is
   false.
