.TH std::experimental::memory_alignment 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::memory_alignment \- std::experimental::memory_alignment

.SH Synopsis
   Defined in header <experimental/simd>
   template< class T, class U = typename T::value_type >  (parallelism TS v2)
   struct memory_alignment;

   If is_simd_mask_v<T> is true and U is bool, or if is_simd_v<T> is true and U is a
   vectorizable type, provides the member constant value equal to the minimum alignment
   of a pointer passed to a load constructor, copy_from function, or copy_to function.
   For any other types T and U, there is no member value.

   If the program adds specializations for std::memory_alignment
   or std::memory_alignment_v
   \fI(since C++17)\fP, the behavior is undefined.

.SH Member constants

   value    the minimum alignment of a pointer passed to a load constructor, copy_from
   \fB[static]\fP function, or copy_to function
            \fI(public static member constant)\fP

.SH Member functions

   operator std::size_t converts the object to  std::size_t, returns value
                        \fI(public member function)\fP
   operator()           returns value
   \fI(C++14)\fP              \fI(public member function)\fP

.SH Member types

   Type       Definition
   value_type  std::size_t
   type       std::integral_constant< std::size_t, value>

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   vector_aligned_tag  flag indicating alignment of the load/store address to vector
   vector_aligned      alignment
   (parallelism TS v2) \fI(class)\fP
   constructor         constructs a simd object
   (parallelism TS v2) \fI(public member function of std::experimental::simd<T,Abi>)\fP

   copy_from           loads simd elements from contiguous memory
   (parallelism TS v2) \fI(public member function of std::experimental::simd<T,Abi>)\fP

   copy_to             stores simd elements to contiguous memory
   (parallelism TS v2) \fI(public member function of std::experimental::simd<T,Abi>)\fP

   constructor         constructs a simd_mask object
   (parallelism TS v2) \fI(public member function of std::experimental::simd_mask<T,Abi>)\fP

   copy_from           loads simd_mask elements from contiguous memory
   (parallelism TS v2) \fI(public member function of std::experimental::simd_mask<T,Abi>)\fP

   copy_to             stores simd_mask elements to contiguous memory
   (parallelism TS v2) \fI(public member function of std::experimental::simd_mask<T,Abi>)\fP


.SH Category:
     * Todo no example
