.TH std::basic_streambuf::pubimbue,std::basic_streambuf::imbue 3 "Jun 28 2014" "2.0 | http://cppreference.com" "C++ Standard Libary"
.SH Synopsis
   std::locale pubimbue( const std::locale& loc ); \fB(1)\fP
   protected:                                      \fB(2)\fP
   virtual void imbue( const std::locale& loc );

   Changes the associated locale.

   1) Calls imbue(loc) of the most derived class

   2) The base class version of this function has no effect. The derived classes may
   override this function in order to be informed about the changes of the locale. The
   derived class may cache the locale and member facets between calls to imbue().

.SH Parameters

   loc - locale object to associate

.SH Return value

   1) Previous associated locale.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   getloc obtains a copy of the associated locale
          \fI(public member function)\fP 

.SH Category:

     * Todo no example
