.TH std::filesystem::file_type 3 "2019.08.27" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::file_type \- std::filesystem::file_type

.SH Synopsis
   Defined in header <filesystem>
   enum class file_type {

   none = /* unspecified */,
   not_found = /* unspecified */,
   regular = /* unspecified */,
   directory = /* unspecified */,
   symlink = /* unspecified */,
   block = /* unspecified */,      \fI(since C++17)\fP
   character = /* unspecified */,
   fifo = /* unspecified */,
   socket = /* unspecified */,
   unknown = /* unspecified */,
   /* implementation-defined */

   };

   file_type defines constants that indicate a type of a file or directory a path
   refers to. The value of the enumerators are distinct.

    This section is incomplete

.SH Constants

   Constant               Meaning
   none                   indicates that the file status has not been evaluated yet, or
                          an error occurred when evaluating it
   not_found              indicates that the file was not found (this is not considered
                          an error)
   regular                a regular file
   directory              a directory
   symlink                a symbolic link
   block                  a block special file
   character              a character special file
   fifo                   a FIFO (also known as pipe) file
   socket                 a socket file
   implementation-defined an additional implementation-defined constant for each
                          additional file type supported by the implementation
   unknown                the file exists but its type could not be determined

.SH See also

    This section is incomplete
