.TH std::locale::operator= 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::locale::operator= \- std::locale::operator=

.SH Synopsis
   Defined in header <locale>
   const locale& operator=( const locale& other ) throw();   \fI(until C++11)\fP
   const locale& operator=( const locale& other ) noexcept;  \fI(since C++11)\fP

   Creates a copy of other, replacing the contents of *this. The reference counts of
   all facets held by other are incremented. The reference counts of all facets
   previously held by *this are decremented, and those facets whose reference count
   becomes zero are deleted.

.SH Return value

   Returns *this, which is now a copy of other.

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   constructor   constructs a new locale
                 \fI(public member function)\fP 

.SH Category:

     * Todo no example
