.TH std::system_error::operator= 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::system_error::operator= \- std::system_error::operator=

.SH Synopsis
   system_error& operator=( const system_error& other ) noexcept;  \fI(since C++11)\fP

   Assigns the contents with those of other. If *this and other both have dynamic type
   std::system_error then std::strcmp(what(), other.what()) == 0 after assignment.

.SH Parameters

   other - another system_error object to assign with

.SH Return value

   *this

.SH Example

    This section is incomplete
    Reason: no example
