.TH std::unordered_map::empty 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_map::empty \- std::unordered_map::empty

.SH Synopsis
   bool empty() const;  \fI(since C++11)\fP

   Checks if the container has no elements, i.e. whether begin() == end().

.SH Parameters

   \fI(none)\fP

.SH Return value

   true if the container is empty, false otherwise

.SH Exceptions

   noexcept specification:
   noexcept

.SH Complexity

   Constant.

.SH Example

   The following code uses empty to check if a std::unordered_map<int,int> contains any
   elements:

   
// Run this code

 #include <unordered_map>
 #include <iostream>
 #include <utility>

 int main()
 {
     std::unordered_map<int, int> numbers;
     std::cout << "Initially, numbers.empty(): " << numbers.empty() << '\\n';

     numbers.emplace(42, 13);
     numbers.insert(std::make_pair(13317, 123));
     std::cout << "After adding elements, numbers.empty(): " << numbers.empty() << '\\n';
 }

.SH Output:

 Initially, numbers.empty(): 1
 After adding elements, numbers.empty(): 0

.SH See also

   size returns the number of elements
        \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
