.TH std::linear_congruential_engine::operator() 3 "2017.04.02" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::linear_congruential_engine::operator() \- std::linear_congruential_engine::operator()

.SH Synopsis
   result_type operator()();  \fI(since C++11)\fP

   Generates a pseudo-random value. The state of the engine is advanced by one
   position.

    This section is incomplete

.SH Parameters

   \fI(none)\fP

.SH Return value

   A pseudo-random number in [min(), max()].

.SH Complexity

   Amortized constant.

.SH See also

   discard advances the engine's state by a specified amount
           \fI(public member function)\fP 

.SH Category:

     * Todo without reason
