.TH std::experimental::swap(std::experimental::packaged_task) 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::swap(std::experimental::packaged_task) \- std::experimental::swap(std::experimental::packaged_task)

.SH Synopsis
   template< class R, class... Args >

   void swap( std::experimental::packaged_task<R(Args...)> &lhs,

   std::experimental::packaged_task<R(Args...)> &rhs );

   Overloads the swap algorithm for std::experimental::packaged_task. Exchanges the
   state of lhs with that of rhs. Effectively calls lhs.swap(rhs).

.SH Parameters

   lhs, rhs - packaged_tasks whose states to swap

.SH Return value

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   swap swaps two task objects
        \fI(public member function of std::packaged_task)\fP

   Categories:

     * unconditionally noexcept
     * Todo no example

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
