.TH std::ranges::zip_view::iterator::operator++,--,+=,-= 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::ranges::zip_view::iterator::operator++,--,+=,-= \- std::ranges::zip_view::iterator::operator++,--,+=,-=

.SH Synopsis
   constexpr /*iterator*/& operator++();                   \fB(1)\fP (since C++23)
   constexpr void operator++( int );                       \fB(2)\fP (since C++23)
   constexpr /*iterator*/ operator++( int )                \fB(3)\fP (since C++23)
     requires /*all-forward*/<Const, Views...>;
   constexpr /*iterator*/& operator--()                    \fB(4)\fP (since C++23)
     requires /*all-bidirectional*/<Const, Views...>;
   constexpr /*iterator*/ operator--( int )                \fB(5)\fP (since C++23)
     requires /*all-bidirectional*/<Const, Views...>;
   constexpr /*iterator*/& operator+=( difference_type n ) \fB(6)\fP (since C++23)
     requires /*all-random-access*/<Const, Views...>;
   constexpr /*iterator*/& operator-=( difference_type n ) \fB(7)\fP (since C++23)
     requires /*all-random-access*/<Const, Views...>;

   Increments or decrements each of the underlying is_... iterators in the underlying
   tuple-like object current_.

   1) Equivalent to /*tuple-for-each*/([](auto& i) { ++i; }, current_); return *this;
   2) Equivalent to ++*this;
   3) Equivalent to auto tmp = *this; ++*this; return tmp;
   4) Equivalent to /*tuple-for-each*/([](auto& i) { --i; }, current_); return *this;
   5) Equivalent to auto tmp = *this; --*this; return tmp;
   6) Equivalent to /*tuple-for-each*/([&]<class I>(I& i) { i +=
   iter_difference_t<I>(x); }, current_); return *this;
   7) Equivalent to /*tuple-for-each*/([&]<class I>(I& i) { i -=
   iter_difference_t<I>(x); }, current_); return *this;

.SH Parameters

   n - position relative to current location

.SH Return value

   1,4,6,7) *this
   2) \fI(none)\fP
   3,5) a copy of *this that was made before the change

.SH Example

    This section is incomplete
    Reason: no example

.SH Category:
     * Todo no example
