.TH std::fetestexcept 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::fetestexcept \- std::fetestexcept

.SH Synopsis
   Defined in header <cfenv>
   int fetestexcept( int excepts );  \fI(since C++11)\fP

   Determines which of the specified subset of the floating point exceptions are
   currently set. The argument excepts is a bitwise OR of the floating point exception
   macros.

.SH Parameters

   excepts - bitmask listing the exception flags to test

.SH Return value

   Bitwise OR of the floating-point exception macros that are both included in excepts
   and correspond to floating-point exceptions currently set.

.SH Example

   
// Run this code

 #include <iostream>
 #include <cfenv>
 #include <cmath>

 #pragma STDC FENV_ACCESS ON

 volatile double zero = 0.0; // volatile not needed where FENV_ACCESS is supported
 volatile double one = 1.0;  // volatile not needed where FENV_ACCESS is supported

 int main()
 {
     std::feclearexcept(FE_ALL_EXCEPT);
     std::cout <<  "1.0/0.0 = " << 1.0 / zero << '\\n';
     if(std::fetestexcept(FE_DIVBYZERO)) {
         std::cout << "division by zero reported\\n";
     } else {
         std::cout << "divsion by zero not reported\\n";
     }

     std::feclearexcept(FE_ALL_EXCEPT);
     std::cout << "1.0/10 = " << one/10 << '\\n';
     if(std::fetestexcept(FE_INEXACT)) {
         std::cout << "inexact result reported\\n";
     } else {
         std::cout << "inexact result not reported\\n";
     }

     std::feclearexcept(FE_ALL_EXCEPT);
     std::cout << "sqrt(-1) = " << std::sqrt(-1) << '\\n';
     if(std::fetestexcept(FE_INVALID)) {
         std::cout << "invalid result reported\\n";
     } else {
         std::cout << "invalid result not reported\\n";
     }
 }

.SH Output:

 1.0/0.0 = inf
 division by zero reported
 1.0/10 = 0.1
 inexact result reported
 sqrt(-1) = -nan
 invalid result reported

.SH See also

   feclearexcept clears the specified floating-point status flags
   \fI(C++11)\fP       \fI(function)\fP
