.TH std::span::operator= 3 "2019.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::span::operator= \- std::span::operator=

.SH Synopsis
   constexpr span& operator=( const span& other ) noexcept = default;

   Assigns other to *this. This defaulted assignment operator performs a shallow copy
   of the data pointer and the size, i.e., after a call to this function, data() ==
   other.data() and size() == other.size().

.SH Parameters

   other - another span to copy from

.SH Return value

   *this.

.SH See also

   constructor   constructs a span
                 \fI(public member function)\fP 
   data          returns a pointer to the beginning of the sequence of elements
                 \fI(public member function)\fP 
   size          returns the number of elements in the sequence
                 \fI(public member function)\fP 
