.TH std::error_condition::operator= 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_condition::operator= \- std::error_condition::operator=

.SH Synopsis
   error_condition& operator=( const error_condition& other   \fB(1)\fP \fI(since C++11)\fP
   );                                                             (implicitly declared)
   template< class ErrorConditionEnum >                       \fB(2)\fP \fI(since C++11)\fP
   error_condition& operator=( ErrorConditionEnum e );

   Assigns contents to an error condition.

   1) Copy assignment operator. Assigns the contents of other.
   2) Assigns error condition for enum e. Effectively calls make_error_condition().
   Does not participate in the overload resolution unless
   is_error_condition_enum<ErrorConditionEnum>::value is true.

.SH Parameters

   other - another error condition to initialize with
   e     - error condition enum

.SH Return value

   *this.

.SH Exceptions

   noexcept specification:
   noexcept
.SH Category:

     * unconditionally noexcept

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
