.TH std::mersenne_twister_engine 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <random>
   template<

   class UIntType,
   size_t w, size_t n, size_t m, size_t r,
   UIntType a, size_t u, UIntType d, size_t s,  \fI(since C++11)\fP
   UIntType b, size_t t,
   UIntType c, size_t l, UIntType f

   > class mersenne_twister_engine;

   mersenne_twister_engine is a random number engine based on Mersenne Twister
   algorithm. It produces high quality unsigned integer random numbers.

   The following typedefs define the random number engine with two commonly used
   parameter sets:

   Defined in header <random>
   Type       Definition
              std::mersenne_twister_engine<std::uint_fast32_t, 32, 624, 397, 31,

              0x9908b0df, 11,
   mt19937    0xffffffff, 7,
              0x9d2c5680, 15,
              0xefc60000, 18, 1812433253>

              32-bit Mersenne Twister by Matsumoto and Nishimura, 1998
              std::mersenne_twister_engine<uint_fast64_t, 64, 312, 156, 31,

              0xb5026f5aa96619e9, 29,
   mt19937_64 0x5555555555555555, 17,
              0x71d67fffeda60000, 37,
              0xfff7eee000000000, 43, 6364136223846793005>

              64-bit Mersenne Twister by Matsumoto and Nishimura, 2000

.SH Contents

     • 1 Member types
     • 2 Member functions

          • 2.1 Construction and Seeding
          • 2.2 Generation
          • 2.3 Characteristics

     • 3 Non-member functions
     • 4 Member objects

.SH Member types

   Member type Definition
   result_type The integral type generated by the engine. Results are undefined if this
               is not an unsigned integral type.

.SH Member functions

.SH Construction and Seeding
   constructor   constructs the engine
                 \fI(public member function)\fP
   seed          sets the current state of the engine
                 \fI(public member function)\fP
.SH Generation
   operator()    advances the engine's state and returns the generated value
                 \fI(public member function)\fP
   discard       advances the engine's state by a specified amount
                 \fI(public member function)\fP
.SH Characteristics
   min           gets the smallest possible value in the output range
   \fB[static]\fP      \fI(public static member function)\fP
   max           gets the largest possible value in the output range
   \fB[static]\fP      \fI(public static member function)\fP

.SH Non-member functions

   operator== compares the internal states of two pseudo-random number engines
   operator!= \fI(function)\fP
   operator<< performs stream input and output on pseudo-random number engine
   operator>> \fI(function)\fP

.SH Member objects

   constexpr size_t word_size                    This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t state_size                   This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t shift_size                   This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t mask_bits                    This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr UIntType xor_mask                   This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t tempering_u                  This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr UIntType tempering_d                This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t tempering_s                  This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr UIntType tempering_b                This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t tempering_t                  This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr UIntType tempering_c                This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr size_t tempering_l                  This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr UIntType initialization_multiplier  This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP
   constexpr UIntType default_seed               This section is incomplete
   \fB[static]\fP
                                                \fI(public static member constant)\fP

.SH Category:

     • Todo without reason
