.TH std::pmr::unsynchronized_pool_resource::~unsynchronized_pool_resource 3 "Apr  2 2017" "2.1 | http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::pmr::unsynchronized_pool_resource::~unsynchronized_pool_resource \- std::pmr::unsynchronized_pool_resource::~unsynchronized_pool_resource

.SH Synopsis
   virtual ~unsynchronized_pool_resource();  \fI(since C++17)\fP

   Destroys a unsynchronized_pool_resource.

   Deallocates all memory owned by this resource by calling this->release().

.SH See also

   release Release all allocated memory
           \fI(public member function)\fP
