.TH std::experimental::basic_string_view::rfind 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::basic_string_view::rfind \- std::experimental::basic_string_view::rfind

.SH Synopsis
   constexpr size_type rfind(basic_string_view v,         \fB(1)\fP (library fundamentals TS)
   size_type pos = npos) const;
   constexpr size_type rfind(CharT c, size_type pos =     \fB(2)\fP (library fundamentals TS)
   npos) const;
   constexpr size_type rfind(const CharT* s, size_type    \fB(3)\fP (library fundamentals TS)
   pos, size_type count) const;
   constexpr size_type rfind(const CharT* s, size_type    \fB(4)\fP (library fundamentals TS)
   pos = npos) const;

   Finds the last substring equal to the given character sequence.

   1) Finds the last occurence of v in this view, starting at position pos.
   2) Equivalent to rfind(basic_string_view(&c, 1), pos).
   3) Equivalent to rfind(basic_string_view(s, count), pos).
   4) Equivalent to rfind(basic_string_view(s), pos).

.SH Parameters

   v     - view to search for
   pos   - position at which to start the search
   count - length of substring to search for
   s     - pointer to a character string to search for
   ch    - character to search for

.SH Return value

   Position of the first character of the found substring or npos if no such substring
   is found.

.SH Exceptions

   1-2)
   noexcept specification:
   noexcept

.SH Complexity

   O(size() * v.size()) at worst.

.SH See also

   find              find characters in the view
                     \fI(public member function)\fP
   find_first_of     find first occurrence of characters
                     \fI(public member function)\fP
   find_last_of      find last occurrence of characters
                     \fI(public member function)\fP
   find_first_not_of find first absence of characters
                     \fI(public member function)\fP
   find_last_not_of  find last absence of characters
                     \fI(public member function)\fP

.SH Category:

     * unconditionally noexcept

   Hidden categories:

     * Pages with unreviewed unconditional noexcept template
     * Pages with unreviewed noexcept template
