.TH std::iswpunct 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::iswpunct \- std::iswpunct

.SH Synopsis
   Defined in header <cwctype>
   int iswpunct( std::wint_t ch );

   Checks if the given wide character is a punctuation character, i.e. it is one of
   !"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ or any punctuation character specific to the
   current locale.

   If the value of ch is neither representable as a wchar_t nor equal to the value of
   the macro WEOF, the behavior is undefined.

.SH Parameters

   ch - wide character

.SH Return value

   Non-zero value if the wide character is a punctuation character, zero otherwise.

.SH Notes

   ISO 30112 specifies which Unicode characters are include in POSIX punct category.

.SH Example


// Run this code

 #include <iostream>
 #include <cwctype>
 #include <clocale>

 int main()
 {
     wchar_t c = L'\\u2051'; // Two asterisks ('‚Åë')

     std::cout << std::hex << std::showbase << std::boolalpha;
     std::cout << "in the default locale, iswpunct(" << (std::wint_t)c << ") = "
               << (bool)std::iswpunct(c) << '\\n';
     std::setlocale(LC_ALL, "en_US.utf8");
     std::cout << "in Unicode locale, iswpunct(" << (std::wint_t)c << ") = "
               << (bool)std::iswpunct(c) << '\\n';
 }

.SH Output:

 in the default locale, iswpunct(0x2051) = false
 in Unicode locale, iswpunct(0x2051) = true

.SH See also

   ispunct(std::locale) checks if a character is classified as punctuation by a locale
                        \fI(function template)\fP
   ispunct              checks if a character is a punctuation character
                        \fI(function)\fP

          ASCII values              characters    iscntrl  isprint  isspace  isblank  isgraph  ispunct  isalnum  isalpha  isupper  islower  isdigit  isxdigit
 decimal  hexadecimal    octal                    iswcntrl iswprint iswspace iswblank iswgraph iswpunct iswalnum iswalpha iswupper iswlower iswdigit iswxdigit
0‚Äì8     \\x0‚Äì\\x8   \\0‚Äì\\10    control codes   ‚â 0     0        0        0        0        0        0        0        0        0        0        0
                                  (NUL, etc.)
9         \\x9         \\11         tab (\\t)        ‚â 0     0        ‚â 0     ‚â 0     0        0        0        0        0        0        0        0
                                  whitespaces
10‚Äì13   \\xA‚Äì\\xD   \\12‚Äì\\15   (\\n, \\v, \\f,    ‚â 0     0        ‚â 0     0        0        0        0        0        0        0        0        0
                                  \\r)
14‚Äì31   \\xE‚Äì\\x1F  \\16‚Äì\\37   control codes   ‚â 0     0        0        0        0        0        0        0        0        0        0        0
32        \\x20        \\40         space           0        ‚â 0     ‚â 0     ‚â 0     0        0        0        0        0        0        0        0
33‚Äì47   \\x21‚Äì\\x2F \\41‚Äì\\57   !"#$%&'()*+,-./ 0        ‚â 0     0        0        ‚â 0     ‚â 0     0        0        0        0        0        0
48‚Äì57   \\x30‚Äì\\x39 \\60‚Äì\\71   0123456789      0        ‚â 0     0        0        ‚â 0     0        ‚â 0     0        0        0        ‚â 0     ‚â 0
58‚Äì64   \\x3A‚Äì\\x40 \\72‚Äì\\100  :;<=>?@         0        ‚â 0     0        0        ‚â 0     ‚â 0     0        0        0        0        0        0
65‚Äì70   \\x41‚Äì\\x46 \\101‚Äì\\106 ABCDEF          0        ‚â 0     0        0        ‚â 0     0        ‚â 0     ‚â 0     ‚â 0     0        0        ‚â 0
71‚Äì90   \\x47‚Äì\\x5A \\107‚Äì\\132 GHIJKLMNOP      0        ‚â 0     0        0        ‚â 0     0        ‚â 0     ‚â 0     ‚â 0     0        0        0
                                  QRSTUVWXYZ
91‚Äì96   \\x5B‚Äì\\x60 \\133‚Äì\\140 [\\]^_`          0        ‚â 0     0        0        ‚â 0     ‚â 0     0        0        0        0        0        0
97‚Äì102  \\x61‚Äì\\x66 \\141‚Äì\\146 abcdef          0        ‚â 0     0        0        ‚â 0     0        ‚â 0     ‚â 0     0        ‚â 0     0        ‚â 0
103‚Äì122 \\x67‚Äì\\x7A \\147‚Äì\\172 ghijklmnop      0        ‚â 0     0        0        ‚â 0     0        ‚â 0     ‚â 0     0        ‚â 0     0        0
                                  qrstuvwxyz
123‚Äì126 \\x7B‚Äì\\x7E \\172‚Äì\\176 {|}~            0        ‚â 0     0        0        ‚â 0     ‚â 0     0        0        0        0        0        0
127       \\x7F        \\177        backspace       ‚â 0     0        0        0        0        0        0        0        0        0        0        0
                                  character (DEL)
