.TH std::span::end 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::span::end \- std::span::end

.SH Synopsis
   constexpr iterator end() const noexcept;

   Returns an iterator to the element following the last element of the span.

   This element acts as a placeholder; attempting to access it results in undefined
   behavior.

   range-begin-end.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the element following the last element.

.SH Complexity

   Constant.

.SH Example


// Run this code

 #include <span>
 #include <iostream>

 void print(std::span<const int> sp)
 {
     for(auto it = sp.begin(); it != sp.end(); ++it) {
         std::cout << *it << ' ';
     }
     std::cout << '\\n';
 }

 void transmogrify(std::span<int> sp)
 {
     if (!sp.empty()) {
         std::cout << *sp.begin() << '\\n';
         *sp.begin() = 2;
     }
 }

 int main()
 {
     int array[] { 1, 3, 4, 5 };
     print(array);
     transmogrify(array);
     print(array);
 }

.SH Output:

 1 3 4 5
 1
 2 3 4 5

.SH See also

   begin   returns an iterator to the beginning
   (C++20) \fI(public member function)\fP
