.TH std::experimental::filesystem::recursive_directory_iterator::options 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::filesystem::recursive_directory_iterator::options \- std::experimental::filesystem::recursive_directory_iterator::options

.SH Synopsis
   directory_options options() const;  (filesystem TS)

   Returns the options that affect the directory iteration. The options can only be
   supplied when constructing the directory iterator.

   If the options argument was not supplied, returns options::none.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The effective options that affect the directory iteration.

.SH Exceptions

   Throws nothing.

.SH Category:
     * Noindexed pages
