.TH std::basic_stacktrace::begin,std::basic_stacktrace::cbegin 3 "2024.06.10" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_stacktrace::begin,std::basic_stacktrace::cbegin \- std::basic_stacktrace::begin,std::basic_stacktrace::cbegin

.SH Synopsis
   const_iterator begin()  const noexcept; \fB(1)\fP (since C++23)
   const_iterator cbegin() const noexcept; \fB(2)\fP (since C++23)

   Returns an iterator to the first entry of the basic_stacktrace.

   If the basic_stacktrace is empty, the returned iterator is equal to end().

   range-begin-end.svg

.SH Parameters

   \fI(none)\fP

.SH Return value

   Iterator to the first entry.

.SH Complexity

   Constant.

.SH Example


// Run this code

 #include <algorithm>
 #include <iostream>
 #include <stacktrace>

 int main()
 {
     auto trace       = std::stacktrace::current();
     auto empty_trace = std::stacktrace{};

     // Print stacktrace.
     std::for_each(trace.begin(), trace.end(),
                   [](const auto& f) { std::cout << f << '\\n'; });

     if (empty_trace.begin() == empty_trace.end())
         std::cout << "stacktrace 'empty_trace' is indeed empty.\\n";
 }

.SH Possible output:

 0x0000000000402BA8 in ./prog.exe
 __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 0x0000000000402A29 in ./prog.exe
 stacktrace 'empty_trace' is indeed empty.

.SH See also

   end  returns an iterator to the end
   cend \fI(public member function)\fP
