.TH std::imag(std::complex) 3 "2018.03.28" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::imag(std::complex) \- std::imag(std::complex)

.SH Synopsis
   Defined in header <complex>
   template< class T >                                   \fI(until C++14)\fP
   T imag( const std::complex<T>& z );
   template< class T >                                   \fI(since C++14)\fP
   constexpr T imag( const std::complex<T>& z );
   float imag( float z );

   template< class DoubleOrInteger >                                   \fI(since C++11)\fP
   double imag( DoubleOrInteger z );             \fB(1)\fP                   \fI(until C++14)\fP

   long double imag( long double z );                \fB(2)\fP
   constexpr float imag( float z );

   template< class DoubleOrInteger >                                   \fI(since C++14)\fP
   constexpr double imag( DoubleOrInteger z );

   constexpr long double imag( long double z );

   1) Returns the imaginary component of the complex number z, i.e. z.imag().

   2) Additional overloads are provided for float, double, long double,
   and all integer types, which are treated as complex numbers with zero  \fI(since C++11)\fP
   imaginary component.

.SH Parameters

   z - complex value

.SH Return value

   the imaginary component of z

.SH See also

   imag accesses the imaginary part of the complex number
        \fI(public member function)\fP 
   real returns the real component
        \fI(function template)\fP 
   C documentation for
   cimag
