.TH std::chrono::operator<<(std::chrono::weekday_indexed) 3 "2020.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator<<(std::chrono::weekday_indexed) \- std::chrono::operator<<(std::chrono::weekday_indexed)

.SH Synopsis
   template <class CharT, class Traits>

   std::basic_ostream<CharT, Traits>&                                     \fI(since C++20)\fP

   operator<<(std::basic_ostream<CharT, Traits>& os, const
   std::chrono::weekday_indexed& wdi);

   Outputs a textual representation of wdi into the stream os, as if by:

 os << wdi.weekday() << '[' << wdi.index();
 if(wdi.index() >=1 && wdi.index <= 5) {
     os << ']';
 }
 else {
     os << " is not a valid index]";
 }

.SH Return value

   os.

.SH Notes

   This operator<< is primarily intended for debugging use. When used with non-default
   stream flags, the output may be surprising:

 auto wdi = std::chrono::Sunday[1];
 std::cout.width\fB(10)\fP;
 std::cout.fill('-');
 std::cout << std::left << wdi; // may output "Sun-------[1]"
