.TH std::chrono::year::operatorint 3 "2021.11.17" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::year::operatorint \- std::chrono::year::operatorint

.SH Synopsis
   explicit constexpr operator int() const noexcept;  \fI(since C++20)\fP

   Returns the year value stored in *this.

.SH Return value

   The year value stored in *this.

.SH Example


// Run this code

 #include <iostream>
 #include <chrono>

 int main()
 {

     std::chrono::year y {2020};
     auto year = (int)y;
     std::cout << "The year is: " << year << "\\n";

 }

.SH Output:

 The year is: 2020
