.TH std::experimental::filesystem::filesystem_error 3 "2022.03.29" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::filesystem::filesystem_error \- std::experimental::filesystem::filesystem_error

.SH Synopsis
   Defined in header <experimental/filesystem>
   class filesystem_error;                      (filesystem TS)

   An exception type thrown when errors are encountered.

   std-experimental-filesystem-filesystem error-inheritance.svg

                                   Inheritance diagram

.SH Member functions

   constructor   constructs the error object
                 \fI(public member function)\fP
   path1         returns the paths that were involved in the operation that caused the
   path2         error
                 \fI(public member function)\fP
   what          returns the explanatory string
                 \fI(public member function)\fP

.SH See also

    This section is incomplete
