#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: do_generate
# Author: Jesse 'Jeaye' Wilkerson

# XXX: Do not call this script directly: use `make generate`
set -o nounset

echo "$ECHO_PREFIX Generating from $REFERENCE to $TMP_MAN"
echo "  $ECHO_PREFIX Removing previous files"
rm -f $TMP_MAN/*.3
echo "  $ECHO_PREFIX Parsing documentation"
for file in $(find $REFERENCE -name '*.html') ; do
  echo "    $ECHO_PREFIX $file" ;
  ./bin/stdman -d $TMP_MAN $file > /dev/null 2>&1 || true;
done

echo "  $ECHO_PREFIX Removing unwanted pages"
for file in $(find $TMP_MAN -name '*.3') ; do
  std=$(echo $file | grep "std::")
  if [ ! "$?" -eq "0" ];
  then
    rm -f $file;
  fi
done

echo "  $ECHO_PREFIX Creating links for common typedefs"
./do_link
echo "$ECHO_PREFIX Done"
