#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: do_generate
# Author: Jesse 'Jeaye' Wilkerson

# XXX: Do not call this script directly: use `make generate`
set -o nounset

echo "$echo_prefix Generating from $reference to $tmp_man"
echo "  $echo_prefix Removing previous files"
rm -f $tmp_man/*.3
echo "  $echo_prefix Parsing documentation on $threads threads"
find $reference -name '*.html' -print0 | xargs -0 -n 1 -P $threads -I % \
./bin/stdman -d $tmp_man % > /dev/null 2>&1

echo "  $echo_prefix Removing unwanted pages"
for file in $(find $tmp_man -name '*.3' | grep -v "std::") ; do
  rm -f $file;
done

echo "  $echo_prefix Creating links for common typedefs"
./do_link
echo "$echo_prefix Done generating"
