#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: do_install
# Author: Jesse 'Jeaye' Wilkerson

# XXX: Do not call this script directly: use `sudo make install`
set -o errexit
set -o nounset

echo "$ECHO_PREFIX Installing from $REFERENCE to $PREFIX"
for file in $(find $TMP_MAN -name '*.3') ; do
  out=$PREFIX/$(basename $file);
  echo "  $ECHO_PREFIX $file -> $out";
  install -g 0 -o 0 -m 0644 "$file" "$out";
  gzip -f "$out";
done
echo "$ECHO_PREFIX Done"
