#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: do_install
# Author: Jesse 'Jeaye' Wilkerson

# XXX: Do not call this script directly: use `sudo make install`
set -o errexit
set -o nounset

echo "$echo_prefix Installing from $reference to $prefix"
for file in $(find $tmp_man -name '*.3') ; do
  out=$prefix/$(basename $file);
  echo "  $echo_prefix $file -> $out";
  install -g 0 -o 0 -m 0644 "$file" "$out";
  gzip -f "$out";
done
echo "$echo_prefix Done"
