#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: do_link
# Author: Jesse 'Jeaye' Wilkerson

# XXX: Do not call this script directly: use `make generate`
set -o errexit
set -o nounset

# Map basic types to their common typedefs and create links
# for each of the occurring patterns in the man pages.
# NOTE: There is likely a better way to do this. I realize.
declare -a TYPEDEFS=('basic_string'\
                     'basic_istringstream' 'basic_ostringstream' 'basic_stringstream'\
                     'basic_istream' 'basic_ostream' 'basic_iostream'\
                     'basic_ifstream' 'basic_ofstream' 'basic_fstream'\
                     'basic_stringbuf' 'basic_streambuf' 'basic_ios'\
                     'basic_filebuf' 'basic_regex'
                    )
declare -a ALIAS_basic_string=('string' 'wstring' 'u16string' 'u32string')
declare -a ALIAS_basic_stringstream=('stringstream' 'wstringstream')
declare -a ALIAS_basic_istringstream=('istringstream' 'wistringstream')
declare -a ALIAS_basic_ostringstream=('ostringstream' 'wostringstream')
declare -a ALIAS_basic_istream=('istream' 'wistream')
declare -a ALIAS_basic_ostream=('ostream' 'wostream')
declare -a ALIAS_basic_iostream=('iostream' 'wiostream')
declare -a ALIAS_basic_ifstream=('ifstream' 'wifstream')
declare -a ALIAS_basic_ofstream=('ofstream' 'wofstream')
declare -a ALIAS_basic_fstream=('fstream' 'wfstream')
declare -a ALIAS_basic_stringbuf=('stringbuf' 'wstringbuf')
declare -a ALIAS_basic_streambuf=('streambuf' 'wstreambuf')
declare -a ALIAS_basic_ios=('ios' 'wios')
declare -a ALIAS_basic_filebuf=('filebuf' 'wfilebuf')
declare -a ALIAS_basic_regex=('regex' 'wregex')

for td in "${TYPEDEFS[@]}"
do
  # Link class pages (eg. std::string.3)
  tmp=ALIAS_$td[@]
  for al in "${!tmp}"
  do
    file=./man/std::$td.3
    out="${file/$td/$al}"
    rm -f $out
    ln -s $(basename $file) $out
  done

  # Link member pages (eg. std::string::erase.3)
  for file in $(find ./man -name "*$td::*");
  do
    tmp=ALIAS_$td[@]
    for al in "${!tmp}"
    do
      out="${file/$td/$al}"
      rm -f $out
      ln -s $(basename $file) $out
    done
  done
done
