#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: link
# Author: Jesse 'Jeaye' Wilkerson

declare -a TYPEDEFS=('basic_string'\
                     'basic_stringstream' 'basic_ostringstream' 'basic_istringstream'\
                     'basic_istream' 'basic_ostream' 'basic_iostream'\
                    )
declare -a ALIAS_basic_string=('string' 'wstring' 'u16string' 'u32string')
declare -a ALIAS_basic_stringstream=('stringstream' 'wstringstream')
declare -a ALIAS_basic_istringstream=('istringstream' 'wistringstream')
declare -a ALIAS_basic_ostringstream=('ostringstream' 'wostringstream')
declare -a ALIAS_basic_istream=('istream' 'wistream')
declare -a ALIAS_basic_ostream=('ostream' 'wostream')
declare -a ALIAS_basic_iostream=('iostream' 'wiostream')
declare -a ALIAS_basic_ifstream=('ifstream' 'wifstream')
declare -a ALIAS_basic_ofstream=('ofstream' 'wofstream')
declare -a ALIAS_basic_fstream=('fstream' 'wfstream')
declare -a ALIAS_basic_stringbuf=('stringbuf' 'wstringbuf')
declare -a ALIAS_basic_streambuf=('streambuf' 'wstreambuf')
declare -a ALIAS_basic_ios=('ios' 'wios')
declare -a ALIAS_basic_filebuf=('filebuf' 'wfilebuf')
declare -a ALIAS_basic_regex=('regex' 'wregex')

for td in "${TYPEDEFS[@]}"
do
  for file in $(find ./man -name "*$td::*");
  do
    tmp=ALIAS_$td[@]
    for al in "${!tmp}"
    do
      out="${file/$td/$al}"
      rm -f $out
      ln -s $(basename $file) $out
    done
  done
done
